// Iron Frontier — rts.html is BUILT from rts.src.html + art/units/, and only that.
//
// The page every tool, test and deploy loads is generated by
// tools/rts-build.py (run first by run-tests.sh and shell/install.sh); the unit
// files and rts.src.html are the only copy of the art. This gate pins the
// build's contract: the output on disk is what a build produces, every unit
// file is included exactly once, a hand-edited output is refused, and a unit
// file that no longer parses is caught before a browser has to.
//
//     node --test apps/games/rts/rts-build.test.js
const { test } = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { spawnSync } = require("node:child_process");

const RTS = __dirname;
const BUILD = path.join(RTS, "tools", "rts-build.py");
const SRC = path.join(RTS, "rts.src.html");
const UNITS = path.join(RTS, "art", "units");
const run = (...args) => spawnSync("python3", [BUILD, ...args], { encoding: "utf8" });

function unitFiles() {
  const out = [];
  (function walk(d) {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      const p = path.join(d, e.name);
      if (e.isDirectory()) walk(p);
      else if (e.name.endsWith(".js")) out.push(path.relative(RTS, p));
    }
  })(UNITS);
  return out.sort();
}
const includes = () => [...fs.readFileSync(SRC, "utf8").matchAll(/^ *\/\/ @@include (\S+)\s*$/gm)].map((m) => m[1]);

test("rts.html on disk is what a build produces (run: python3 apps/games/rts/tools/rts-build.py)", () => {
  const r = run("--check");
  assert.strictEqual(r.status, 0, r.stderr);
  const head = fs.readFileSync(path.join(RTS, "rts.html"), "utf8").split("\n", 2);
  assert.match(head[1], /^<!-- GENERATED by apps\/games\/rts\/tools\/rts-build\.py/);
});

test("every unit file is included by rts.src.html exactly once, and every include resolves", () => {
  const inc = includes();
  assert.deepStrictEqual([...inc].sort(), unitFiles());
  assert.strictEqual(new Set(inc).size, inc.length, "a unit included twice");
  assert.ok(inc.length >= 60, `only ${inc.length} includes`);
  assert.ok(!/\/\/ @@(ART|END) /.test(fs.readFileSync(SRC, "utf8")), "stray split-era markers in rts.src.html");
});

test("the build refuses to overwrite a hand-edited rts.html, and --force discards it", () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "rts-build-"));
  const out = path.join(dir, "rts.html"), stamp = path.join(dir, "stamp");
  const args = ["--src", SRC, "--out", out, "--stamp", stamp, "-q"];
  assert.strictEqual(run(...args).status, 0);
  fs.chmodSync(out, 0o644); fs.appendFileSync(out, "\n// a change made in the output\n");
  const r = run(...args);
  assert.strictEqual(r.status, 2);
  assert.match(r.stderr, /REFUSING to overwrite/);
  assert.strictEqual(run("--check", ...args).status, 1);
  assert.strictEqual(run("--force", ...args).status, 0);
  assert.strictEqual(run("--check", ...args).status, 0);
  fs.rmSync(dir, { recursive: true });
});

test("a unit file that is not included, or an include that does not resolve, fails the build loudly", () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "rts-build-"));
  // a private copy of the tree: src + units, so the real one is untouched
  fs.cpSync(UNITS, path.join(dir, "art", "units"), { recursive: true });
  const src = path.join(dir, "rts.src.html");
  const text = fs.readFileSync(SRC, "utf8");
  fs.writeFileSync(src, text);
  const args = ["--src", src, "--out", path.join(dir, "rts.html"), "--stamp", path.join(dir, "stamp"), "-q"];
  assert.strictEqual(run(...args).status, 0);
  fs.writeFileSync(path.join(dir, "art", "units", "vehicles", "orphan.js"), "// nobody includes me\n");
  let r = run(...args);
  assert.strictEqual(r.status, 1); assert.match(r.stderr, /not included by rts.src.html: art\/units\/vehicles\/orphan.js/);
  fs.rmSync(path.join(dir, "art", "units", "vehicles", "orphan.js"));
  fs.writeFileSync(src, text.replace("// @@include art/units/vehicles/rhino.js", "// @@include art/units/vehicles/rhinoceros.js"));
  r = run(...args);
  assert.strictEqual(r.status, 1); assert.match(r.stderr, /rhinoceros\.js: no such unit file/);
  fs.rmSync(dir, { recursive: true });
});

test("every unit file parses as a strict function body (what the bake function is)", () => {
  const bad = [];
  for (const f of unitFiles()) {
    try { new Function('"use strict";\n' + fs.readFileSync(path.join(RTS, f), "utf8")); }
    catch (e) { bad.push(`${f}: ${e.message}`); }
  }
  assert.deepStrictEqual(bad, []);
  // and the check is real: a broken copy is rejected
  assert.throws(() => new Function('"use strict";\n' + fs.readFileSync(path.join(RTS, "art/units/vehicles/rhino.js"), "utf8").replace("barrel(", "barrel(,")));
});
