// Iron Frontier — entities.js
// GENERATED by apps/games/rts/tools/modularize from rts.src.html + art/units/**.

import { MCV_T, lcg } from './bake/states.js';
import { BLDS } from './blds.js';
import { bspecFor, bspecOfB, harvKey } from './combat-tables.js';
import { boom, damage, dist, near } from './combat.js';
import { facOf, keyFac } from './factions.js';
import { padSlot } from './geom.js';
import { findPad } from './move.js';
import { killOccupants } from './neutral.js';
import { canPlace, standSpot, waterSpot } from './production.js';
import { UNITS } from './roster.js';
import { headless, idx, inMap } from './state.js';
import { P_AI, P_HUMAN, neutral } from './world.js';

// --------------------------------------------------------------------- //
//  Entity factories. Every field read anywhere is declared here.
// --------------------------------------------------------------------- //
export function spawnUnit(g, type, p, gx, gy) {
  if (type === 'harvester') type = harvKey(facOf(g, p));      // the role resolves to this side's miner
  var d = UNITS[type];
  var u = {
    id: g.nextId++, kind: 'u', type: type, p: p,
    x: gx, y: gy, hp: d.hp, maxhp: d.hp, dead: false,
    face: ((gx + gy) & 7) * 4, fsub: 0, tsub: 0, cool: 0, target: null, order: null,     // order: {t:'move'|'attack'|'harvest', x,y,id}
    path: null, pi: 0, repath: 0, repathAt: -999, stuck: 0, lastx: gx, lasty: gy,
    cargo: 0, cargoV: 0, mineAt: null, homeRef: null, forcedDock: false, state: 'idle', fleeAt: -999, noGo: null, noProg: 0,
    pax: [],                                                       // RA2 Passengers=: who is riding in this hull
    bestD: 1e9, stallAt: 0, holdUntil: 0, movedAt: -99, tface: null, aimAt: 0,
    kills: 0, rank: 0, wp: null,                                   // veterancy: 3 kills veteran, 6 elite
    sel: false, aggro: null, guardX: gx, guardY: gy, born: g.tick, hov: 0,
    // air layer: air = flies; landed/rtb/pad/slot/ammo are the Harrier's pad cycle
    air: !!d.air, landed: false, rtb: false, pad: 0, slot: 0, ammo: d.ammo || 0
  };
  g.units.push(u);
  g.byId[u.id] = u;
  g.side[p].made++;
  if (d.ammo) {
    var fp = findPad(g, u);
    if (fp) { u.pad = fp.b.id; u.slot = fp.slot; var sl = padSlot(fp.b, fp.slot); u.x = sl.x; u.y = sl.y; u.landed = true; u.face = 0; u.fsub = 0; }
  }
  return u;
}

export var MAKE_T = 0;                               // no build-up animation: the user wants placed structures to appear complete (asked twice)

// Production doors. RA2's [GAWEAP] DoorStages=10: the door opens, the
// vehicle comes out of the mouth, the door shuts behind it. Only the War
// Factory and the Barracks have one (the Airforce Command lowers a Harrier
// onto its pad instead), and the whole thing is PRESENTATION -- a headless
// sim never opens a door and gets its unit on the tick it finished.
export var DOORED = { factory: 1, barracks: 1 };

export var DOOR_OPEN = 22, DOOR_HOLD = 26, DOOR_SHUT = 22;

export var DOOR_T = DOOR_OPEN + DOOR_HOLD + DOOR_SHUT;

export function doorPos(el) {
  if (el <= 0) return 0;
  if (el < DOOR_OPEN) return el / DOOR_OPEN;
  if (el < DOOR_OPEN + DOOR_HOLD) return 1;
  return Math.max(0, 1 - (el - DOOR_OPEN - DOOR_HOLD) / DOOR_SHUT);
}

export function placeBld(g, key, p, gx, gy) {
  // The faction-resolved spec, not the raw table: footprints differ by
  // faction (RA2 Foundation=), so a Soviet Battle Lab must occupy 3x3.
  // The faction is the STRUCTURE'S, stamped here once and never rewritten:
  // its own where the key belongs to one side, otherwise its builder's.
  // Everything about the building afterwards — its art, its footprint, its
  // power draw, its name, and whether it unlocks a build list — reads this
  // stamp, so an Engineer changes the owner and nothing else. The neutral
  // house is not stamped (see bfacOf).
  var fk = neutral(p) ? null : keyFac(g, p, key, true);
  var d = bspecFor(key, fk || facOf(g, p));
  var b = {
    id: g.nextId++, kind: 'b', type: key, p: p, fac: fk,
    x: gx, y: gy, gw: d.gw, gh: d.gh,
    hp: d.hp, maxhp: d.hp, dead: false,
    cool: 0, target: null, sel: false,
    cx: gx + (d.gw - 1) / 2, cy: gy + (d.gh - 1) / 2, rally: null,
    builtAt: g.tick,
    // RA2 plays a ~2.5s MAKE before the structure is a structure: it is
    // inert (no firing, no repair bay) while `make` counts down. Purely
    // presentational, so a headless sim never pays for it and the balance
    // tests keep firing on the tick they place a defence.
    make: headless ? 0 : MAKE_T, charging: 0, chgT: null, sup: 0, tube: 0,
    // door: ticks left in the production-door sequence; hold: the finished
    // unit waiting inside the bay; unpack: MCV folding out in front of the
    // yard's MAKE; sell: this MAKE is running BACKWARDS.
    door: 0, hold: null, unpack: 0, sell: false
  };
  g.blds.push(b);
  g.byId[b.id] = b;
  if (!neutral(p) && !d.neut && !d.wall && !d.gate) g.side[p].bmade++;   // score screen: structures built
  for (var yy = gy; yy < gy + d.gh; yy++) for (var xx = gx; xx < gx + d.gw; xx++) {
    if (inMap(xx, yy)) g.occ[idx(xx, yy)] = b.id;
  }
  // Anyone standing inside the new footprint is nudged out to the nearest
  // free cell, as RA2 does — otherwise they are entombed with a live order.
  for (var ui = 0; ui < g.units.length; ui++) {
    var su = g.units[ui];
    if (su.dead || su.air) continue;
    if (Math.round(su.x) < gx || Math.round(su.x) >= gx + d.gw || Math.round(su.y) < gy || Math.round(su.y) >= gy + d.gh) continue;
    var out = (UNITS[su.type].nav ? waterSpot(g, Math.round(su.x), Math.round(su.y))
                                  : standSpot(g, Math.round(su.x), Math.round(su.y)));
    if (out) { su.x = out.x; su.y = out.y; su.path = null; su.noProg = 0; if (su.order && su.order.t === 'move') su.repathAt = -999; }
  }
  recalcPower(g, p);
  return b;
}

// MCV deploy (RA2): the 3x3 Construction Yard lands CENTRED on the tile the
// MCV occupies, the MCV is consumed, and the new yard inherits its damage.
// The footprint is checked with canPlace so terrain, other buildings and
// other units all still veto it — only the build radius and the MCV's own
// body are exempted.
// The yard lands centred on the MCV's tile, using the same rounding rule the
// placement ghost uses, so a 4x4 Foundation= sits where the cursor said.
function mcvSpot(u) {
  var yd = BLDS[UNITS[u.type].deploysInto];
  return { x: Math.round(u.x) - Math.floor((yd.gw - 1) / 2), y: Math.round(u.y) - Math.floor((yd.gh - 1) / 2) };
}

export function canDeployMcv(g, u) {
  if (!u || u.dead || !UNITS[u.type].deploysInto) return false;
  var sp = mcvSpot(u);
  return canPlace(g, u.p, UNITS[u.type].deploysInto, sp.x, sp.y, { anywhere: true, ignore: u });
}

export function deployMcv(g, u) {
  if (!canDeployMcv(g, u)) return null;
  var sp = mcvSpot(u), frac = u.hp / u.maxhp;
  // The unit dies BEFORE the yard is placed so its tile is free the moment
  // the occupancy grid is written.
  u.dead = true; u.sel = false;
  var b = placeBld(g, UNITS[u.type].deploysInto, u.p, sp.x, sp.y);
  b.hp = Math.max(1, b.maxhp * frac);
  b.builtAt = g.tick;
  // The unpack plays IN FRONT OF the yard's build-up: `make` is lengthened
  // by the unpack, so the yard is inert for both and the sim is untouched
  // (a headless deploy still has make === 0 and no unpack at all).
  if (!headless) { b.unpack = MCV_T; b.unpackFace = u.face || 0; b.make = MAKE_T + MCV_T; }
  return b;
}

// RA2 building death: `Explosion=` names FIVE anims at once, `DebrisAnims=`
// throws 2-10 chunks, and the tile keeps a crater, a scorch and rubble
// (passable, and it weathers away). None of that existed -- the building
// simply vanished.
var RUBBLE_LIFE = 60 * 60;                       // a minute at 60 ticks/s

export function killBld(g, b, quiet) {
  b.dead = true;
  if (!neutral(b.p) && !BLDS[b.type].neut && !BLDS[b.type].wall && !BLDS[b.type].gate) {
    g.side[b.p].blost++;                                    // score screen: structures lost...
    g.side[b.p ? P_HUMAN : P_AI].bkilled++;                 // ...is the other side's "destroyed"
  }
  // RA2 kills every occupant when an occupied building falls — the whole
  // risk of holding a city block.
  killOccupants(g, b);
  // `Explodes=yes` + `DeathWeapon=OilExplosion` on [CAOILD], and the fuel
  // station is a tank farm: both go up and take what is beside them.
  if (BLDS[b.type].explodes) {
    near(b.cx, b.cy, 3.2, function (o) {
      if (o.dead || o === b) return;
      var dd = dist(b, o);
      if (dd > 2.6) return;
      damage(g, b, o, 300 * (1 - dd / 3.2), 'HE');
    });
    if (!headless) { boom(g, b.cx, b.cy, 34); g.fx.push({ x: b.cx, y: b.cy, t: 4, life: 30, size: 24 }); }
  }
  for (var yy = b.y; yy < b.y + b.gh; yy++) for (var xx = b.x; xx < b.x + b.gw; xx++) {
    if (inMap(xx, yy) && g.occ[idx(xx, yy)] === b.id) g.occ[idx(xx, yy)] = 0;
  }
  recalcPower(g, b.p);
  if (headless) return;
  // A SOLD structure is not a destroyed one: RA2 folds it away and leaves
  // clean ground, so the blasts, the debris and the rubble decal are all
  // skipped -- only the dust of the last panel coming down.
  if (quiet) {
    for (var qd = 0; qd < 5; qd++)
      g.fx.push({ x: b.cx + (qd - 2) * b.gw * 0.22, y: b.cy + (2 - qd) * b.gh * 0.22,
                  t: -qd * 2, life: 26, dust: true, size: 0 });
    return;
  }
  g.rubble.push({ x: b.cx, y: b.cy, gw: b.gw, gh: b.gh, t: 0, life: RUBBLE_LIFE });
  // Staggered blasts across the footprint, biggest at the centre.
  var area = b.gw * b.gh, n = Math.min(5, 3 + (area > 4 ? 2 : (area > 1 ? 1 : 0))), i;
  var rnd = lcg((b.id * 2654435761) >>> 0);
  for (i = 0; i < n; i++) {
    var ox = i === 0 ? 0 : (rnd() - 0.5) * b.gw * 0.9, oy = i === 0 ? 0 : (rnd() - 0.5) * b.gh * 0.9;
    g.fx.push({ x: b.cx + ox, y: b.cy + oy, t: -i * 4, life: 32, size: i === 0 ? 20 + area * 2.2 : 12 + rnd() * 10 });
  }
  // Debris: chunks thrown out on ballistic arcs.
  for (i = 0; i < 6 + area; i++) {
    var da = rnd() * 6.2832, dv = 0.45 + rnd() * 1.1;
    g.fx.push({ x: b.cx, y: b.cy, t: -((i * 2) % 8), life: 34 + (rnd() * 14) | 0, deb: true,
                vx: Math.cos(da) * dv, vy: Math.sin(da) * dv * 0.5, vz: 2.2 + rnd() * 2.4,
                dw: 2 + rnd() * 3.5, spin: (rnd() - 0.5) * 0.5 });
  }
  // A smoke column that stands over the wreck long after the fire is out.
  for (i = 0; i < 7; i++) {
    g.fx.push({ x: b.cx, y: b.cy, t: -i * 9, life: 150, smoke: true, big: 1 + area * 0.12,
                ox: (rnd() - 0.5) * 10, oy: -6 - rnd() * 10, lift: 0 });
  }
}

export function stepRubble(g) {
  for (var i = g.rubble.length - 1; i >= 0; i--) {
    if (++g.rubble[i].t >= g.rubble[i].life) g.rubble.splice(i, 1);
  }
}

export function recalcPower(g, p) {
  if (neutral(p)) return;                       // the neutral house has no grid
  var made = 0, use = 0;
  for (var i = 0; i < g.blds.length; i++) {
    var b = g.blds[i];
    if (b.dead || b.p !== p) continue;
    if (b.offline) continue;      // switched off by the player (RA2's Power toggle)
    var pw = bspecOfB(g, b).power;
    if (pw > 0) made += pw; else use += -pw;
  }
  g.side[p].powerMade = made;
  g.side[p].powerUse = use;
}

export function powered(g, p) {
  var s = g.side[p];
  // A Spy in the Power Plant ([General] SpyPowerBlackout=1000) takes the
  // whole grid down for a minute — not one building, the GRID.
  if (s.blackout > g.tick) return false;
  return s.powerUse === 0 || s.powerMade >= s.powerUse;
}
