// Iron Frontier — hooks.js
// GENERATED by apps/games/rts/tools/modularize from rts.src.html + art/units/**.

import { AI_NAVAL_ADJ, AI_TEAMS, aiCanMake, aiDefencePlan, aiPickTarget, aiSwTarget, aiSwValue, hasShore, nearestWater, newAI } from './ai.js';
import { COL, bakeBuilding } from './bake/buildings.js';
import { SPR, bakeDecal, bakeGroundSheet, bakeOre, bakeTree, cliffEdgeId, cliffSeams } from './bake/terrain.js';
import { gateSprite, wallSprite } from './bake/walls.js';
import { BLDS } from './blds.js';
import { ARMOURS, VERSES, bspecFor, bspecOfB, eliteOf, harvKey, isHarv, isWall, psiImmune, reachOf, uspd, verses, versesVs, vetArmour, vetFire, vetRof, vetRofAt, vetRofU, vetSpeed, weaponFor } from './combat-tables.js';
import { damage, detected, findTarget, fire, hash, hashAt, isDisguised, shipSinks, stateHash, swFire } from './combat.js';
import { canDeployMcv, deployMcv, killBld, placeBld, powered, spawnUnit } from './entities.js';
import { FACTIONS, bfacOf, facAllows, hasFacBld, keyFac, panelKeys, producerOf, unitOrderFor } from './factions.js';
import { SUB_SURFACE, altOf, canHit, dirtAt, hullZone, isAir, isNaval, isSensor, isSub, labelWater, moverOf, navReach, padSlot, subSeen, surfaced, waterZoneAt } from './geom.js';
import { MAPS, genMap, indexBridges, placeNeutrals } from './mapgen.js';
import { LAND_T } from './move.js';
import { BcBus, LOCKSTEP_DELAY, LoopBus, NET, SP_DELAY, applyCmd, cmd, idsOf, netBind, netLoad, netStash, netStep, netUse, setLOCKSTEP_DELAY, simStep } from './net.js';
import { ORE_SPREAD_T, canOccupy, collapseSpan, damageBridge, ejectGarrison, enterGarrison, garrisonable, occCapOf, occCount, openCrate, paraDrop, repairBridgeFrom, stepCrates, stepOreSpread } from './neutral.js';
import { normOpts } from './opts.js';
import { CHRONO_DELAY, findOre, findRefinery, refDock } from './ore.js';
import { astar, blocked, gateOpen, pathQ, requestPath } from './path.js';
import { adjOf, buildFactor, buildMask, canBuild, canPlace, cancelLast, countBld, countUnit, dockSpot, freeWaterNear, hasBld, isPrimary, prodSpeed, setPrimary, waterPlot } from './production.js';
import { _seed } from './rng.js';
import { IFV_MODE, IFV_MODES, UNITS, ifvModeOf, ifvSpec, ifvTurret } from './roster.js';
import { applyGaps, cloneVatsOf, entSeen, gapped, spySatUp, tileSeen } from './shroud.js';
import { COIL_BOOST, IVAN_BOMB_T, PARASITE_DMG, RAD_MAX, SPY_BLACKOUT, addRad, beginWarp, chronoDelayFor, coilCharged, defuseBomb, engineerDefuse, infest, killDrone, mindControl, plantBomb, popDrone, radAt, releaseMind, spyInfiltrate, startErase } from './special.js';
import { DIFF, G, headless, newState, setG, setHeadless, setState, state } from './state.js';
import { SW, SW_KEYS, reqMet, swBld } from './supers.js';
import { boardTransport, canBoard, killPassengers, paxCapOf, paxCount, unloadTransport } from './transport.js';
import { MUS, PLAY, REPORT, SPEC, VOX, VOXPAT, aLog, aStat, eva, evaLog, live, musicOn, setAckAt, setSfxAt, soundOn, unitAck, vol, voxLine } from './ui/audio.js';
import { CURSORS, buildCursors, curKind, pickCursor } from './ui/cursors.js';
import { cvH, cvW } from './ui/dom.js';
import { EDGE_BANDS, GUT, clickSelect, edgeTarget, linkWall, mouse, nextWaypoint, orderAttack, orderUnitsTo, ownTargetOrder, pickAtW, placeOrigin, rightOrder, views } from './ui/input.js';
import { MP, mapPlate, mpClose, mpStart, mpWire, onA, onB, opts, ovA, ovP, ovT, scoreOf, setMpMode, setOpts, stallOn, togglePause } from './ui/menus.js';
import { render } from './ui/render.js';
import { RESUME_KEY, autosaveForReload, loadGame, lsGet, lsSet, reloadKeepMatch, restoreGame, restoreSession, resumeWanted, saveGame, saveSlots, serialiseGame, setClosedByUser } from './ui/save.js';
import { cam, centerOn, clampCam, groups, hoverTile, placing, sel, setZoom, sx, sy, zoom } from './ui/screen.js';
import { economyDead, openingForce, techCount } from './watch.js';
import { FOE, MAP, ME, MV_AMPH, MV_LAND, MV_NAVAL, P_AI, P_HUMAN, T_BRIDGE, T_CIV, T_CLIFF, T_GEM, T_GROUND, T_ORE, T_RAMP, T_ROAD, T_ROCK, T_TREE, T_WATER, isAiSide, terrPass } from './world.js';

// --------------------------------------------------------------------- //
//  Test hooks — a canvas game cannot be asserted from the DOM, so the
//  tests read these instead of pixels.
// --------------------------------------------------------------------- //
window.__rts = function () {
  if (!G) return null;
  return {
    tick: G.tick, state: state, over: G.over, diff: G.diff, seed: G.seed,
    credits: G.side[ME].credits,
    power: G.side[ME].powerMade - G.side[ME].powerUse,
    units: countUnit(G, ME, null), enemyUnits: countUnit(G, FOE, null),
    blds: G.blds.filter(function (b) { return !b.dead && b.p === ME; }).length,
    enemyBlds: G.blds.filter(function (b) { return !b.dead && b.p === FOE; }).length,
    sel: sel.length, placing: placing, queue: G.side[ME].queues.b.list.slice(),
    ready: G.side[ME].queues.b.ready,
    defQueue: G.side[ME].queues.d.list.slice(), defReady: G.side[ME].queues.d.ready, ai: G.ai ? G.ai.posture : null
  };
};

// --------------------------------------------------------------------- //
//  Lockstep test hooks. `match` builds N in-page clients on one LoopBus,
//  each with its OWN `G` and its own derived caches, and drives them
//  through the barrier — which is the whole of what a real networked
//  build does, minus the socket.
// --------------------------------------------------------------------- //
window.__rtsNet = {
  delay: function (n) { if (n !== undefined) setLOCKSTEP_DELAY(n | 0); return LOCKSTEP_DELAY; },
  emit: function (type, payload) { return cmd(type, payload); },
  active: function () { return NET.active; },
  scheduled: function () {
    var c = NET.active, n = 0, k;
    if (!c) return 0;
    for (k in c.q) n += c.q[k].length;
    return n;
  },
  hash: function (g) { return stateHash(g); },
  seat: function () { return { me: ME, foe: FOE }; },
  mp: function () { return MP; },
  wire: function (m) { mpWire(m); },
  press: function (b) { var f = b === 'B' ? onB : onA; if (f) f(); },
  card: function () { return { t: ovT.textContent, p: ovP.textContent, a: ovA.textContent }; },
  start: function (mode) { setMpMode(mode); mpStart(); },
  leave: function () { mpClose(); },
  state: function () { return state; },
  stalled: function () { return stallOn; },
  pause: function (force, remote) { togglePause(force, remote); return state; },
  bcbus: function (lats) { return new BcBus(lats); },
  aiSide: function (g, p) { return isAiSide(g || G, p); },
  match: function (seed, cfg) {
    cfg = cfg || {};
    var lats = cfg.lat || [0, 0], np = lats.length;
    // `wire: 'bc'` runs the very transport the two tabs use, over a
    // scriptable channel group instead of a real BroadcastChannel.
    var bc = cfg.wire === 'bc';
    var bus = bc ? new BcBus(lats) : new LoopBus(), cl = [], i;
    setHeadless(true);
    for (i = 0; i < np; i++) {
      netStash();
      var g = newState(seed >>> 0, cfg.diff || 'normal', cfg.map, cfg.opt);
      g.side[P_HUMAN].fac = cfg.facA || 'dir';
      g.side[P_AI].fac = cfg.facB || 'col';
      // An AI is NOT a peer: it runs inside simStep on every client from
      // the same seed, so both worlds reach the same decisions with
      // nothing on the wire. Attaching one here is a determinism test in
      // its own right.
      if (cfg.ai) { g.ai = newAI(cfg.ai); g.focusFor[P_AI] = g.ai.cfg.focus; }
      if (cfg.ai2) { g.ai2 = newAI(cfg.ai2); g.focusFor[P_HUMAN] = g.ai2.cfg.focus; }
      [P_HUMAN, P_AI].forEach(function (pp) { openingForce(g, pp); });
      cl.push(netBind(bc ? bus.link(np) : bus.link(lats[i]), i, np));
    }
    var M = {
      bus: bus, clients: cl,
      game: function (i) { return cl[i].g; },
      hash: function (i) { netUse(cl[i]); return stateHash(cl[i].g); },
      desync: function () {
        for (var j = 0; j < cl.length; j++) if (cl[j].desync) return cl[j].desync;
        return null;
      },
      // One client emits a command as itself.
      as: function (i, type, payload) { netUse(cl[i]); return cmd(type, payload); },
      // Corrupt a command AFTER it has been queued on one client only —
      // the cleanest possible stand-in for a client that has cheated, or a
      // build whose sim differs by one line.
      corrupt: function (i, fn) {
        var c = cl[i], k, j;
        for (k in c.q) for (j = 0; j < c.q[k].length; j++) if (fn(c.q[k][j])) return true;
        return false;
      },
      // Drive every client one tick. `script(client, tick, index)` runs
      // BEFORE the bundle for that tick goes out, so anything it emits
      // travels with it.
      run: function (ticks, script) {
        for (var t = 0; t < ticks; t++) {
          var j, done = 0, guard = 0;
          for (j = 0; j < cl.length; j++) { netUse(cl[j]); cl[j]._did = 0; if (script) script(cl[j], cl[j].g.tick, j); }
          while (done < cl.length && guard++ < 512) {
            for (j = 0; j < cl.length; j++) {
              if (!cl[j]._did && netStep(cl[j])) { cl[j]._did = 1; done++; }
            }
            if (done < cl.length) bus.pump();
          }
          bus.pump();                              // let hashes and late bundles land
          if (M.desync()) return t + 1;
        }
        return ticks;
      },
      // Which seat a client is sitting in, and what its OWN screen thinks
      // it owns — the two questions the identity split exists to keep apart.
      wire: function () { return bc ? 'bc' : 'loop'; },
      seat: function (i) { netUse(cl[i]); return { me: ME, foe: FOE, p: cl[i].p }; },
      view: function (i) { netUse(cl[i]); return window.__rts(); },
      end: function () { bus.drain(); setLOCKSTEP_DELAY(SP_DELAY); }
    };
    return M;
  }
};

window.__rtsDamage = damage;                 // art harness: kill by a chosen warhead

window.__rtsTest = {
  // NOTE: these are the SIM API, not the player's input path. They call
  // `orderUnitsTo` / `placeBld` / `swFire` directly and so bypass the
  // lockstep command layer on purpose — a fixture wants the world in a
  // state on the tick it asks for, not two ticks later. The command layer
  // itself is driven through `__rtsNet`.
  // Drop entities into a specific situation instead of playing into it.
  spawn: function (type, p, x, y) { return G ? spawnUnit(G, type, p, x, y) : null; },
  build: function (key, p, x, y) { return G ? placeBld(G, key, p, x, y) : null; },
  give: function (p, n) { if (G) G.side[p].credits += n; },
  setPrimary: function (b) { return G ? setPrimary(G, b) : false; },
  orderMove: function (units, gx, gy) { return G ? orderUnitsTo(G, units, gx, gy) : 0; },
  orderAttack: function (units, tgt, focus, queue) { return G ? orderAttack(G, units, tgt, false, !!focus, !!queue) : 0; },
  nextWaypoint: function (u) { return G ? nextWaypoint(G, u) : false; },
  padSlot: padSlot,
  // Cliff seam profiles, exposed so the seam property can be tested as a
  // PROPERTY rather than by pattern-matching the source text.
  cliffSeams: function (x, y, mask) { return cliffSeams(x, y, mask); },
  cliffEdgeId: function (ax, ay, bx, by) { return cliffEdgeId(ax, ay, bx, by); },
  // Pick whatever is under the CENTRE of a grid cell, the way a click on
  // that cell would. Exposed for the footprint-geometry test.
  pickCell: function (gx, gy) { return pickAtW(sx(gx, gy), sy(gx, gy)); },
  toScreen: function (gx, gy) { return { x: (sx(gx, gy) - cvW / 2) * zoom + cvW / 2, y: (sy(gx, gy) - cvH / 2) * zoom + cvH / 2 }; },
  zoom: function (z) { if (z) setZoom(z, cvW / 2, cvH / 2); return zoom; },
  isPrimary: function (b) { return G ? isPrimary(G, b) : false; },
  killBld: function (b) { if (G) killBld(G, b); },
  kill: function (p) {
    if (!G) return;
    G.blds.forEach(function (b) { if (b.p === p && !b.dead) killBld(G, b); });
  },
  deployMcv: function (u) { return G ? deployMcv(G, u) : null; },
  centerOn: function (gx, gy) { centerOn(gx, gy); },
  // Read-only camera, so a test can tell "the view moved" from "the scene
  // animated" — a canvas screenshot cannot.
  cam: function () { return { x: cam.x, y: cam.y }; },
  edgeTarget: edgeTarget, edgeBands: function () { return EDGE_BANDS; }, gutter: function () { return GUT; },
  clampCam: function () { clampCam(); return { x: cam.x, y: cam.y }; },
  setCam: function (x, y) { cam.x = x; cam.y = y; },
  // Cursors are CSS, so a screenshot never shows them: these let the art
  // review render the whole set as a contact sheet and assert the context
  // picker chose the right one.
  // Frame cost: the renderer on its own, so a perf check measures drawing
  // and not the browser's idle time between animation frames.
  render: function () { render(); },
  // THE PLAYER'S OWN INPUT PATH, addressed by grid cell instead of by pixel.
  // `orderOwn` above reaches applyCmd but starts from a building the test
  // handed it, so it can only ever prove that an order WORKS once issued —
  // never that clicking the thing on screen issues it. Every reported miner
  // failure so far has been in the half these skip: the click resolved to
  // bare ground, the order was a `move`, and the miner parked. These run the
  // real `clickSelect` / `rightOrder` at the pixel the cell projects to, so
  // the pick is under test too. Commands still travel the lockstep layer —
  // step `__rtsNet.delay() + 1` after one.
  clickCell: function (gx, gy, shift) { clickSelect(sx(gx, gy), sy(gx, gy), !!shift); return sel.slice(); },
  rightClickCell: function (gx, gy, shift, ctrl) { rightOrder(sx(gx, gy), sy(gx, gy), !!shift, !!ctrl); return sel.slice(); },
  selected: function () { return sel.slice(); },
  // Where the game thinks the pointer is. A browser test that computes a
  // pixel, moves the mouse and then asserts on the cursor is really making
  // two claims at once; this separates them, so "the cursor is wrong" can be
  // told apart from "the test aimed at the wrong tile".
  hover: function () { return { x: hoverTile.x, y: hoverTile.y, mx: mouse.x, my: mouse.y, in: mouse.in }; },
  // What the cursor WOULD be over a given cell, without a pointer. pickCursor
  // reads `mouse`/`hoverTile` and bails headless, so a test cannot ask it
  // anything; this sets the hover the way a real pointermove does and reads
  // the answer back. The cursor is the only cue the game gives about what a
  // right-click will do, so it is worth an assertion of its own.
  cursorAt: function (gx, gy) {
    var was = headless; setHeadless(false);
    try {
      mouse.in = true; mouse.x = sx(gx, gy); mouse.y = sy(gx, gy);
      hoverTile.x = Math.round(gx); hoverTile.y = Math.round(gy);
      pickCursor();
    } finally { setHeadless(was); }        // a throw in here must not leave the sim rendering
    return curKind;
  },
  cursorKind: function () { return curKind; },
  cursorSet: function () { buildCursors(); return CURSORS; },
  // Every module-level cache the SIMULATION reads back. A match must start
  // from the same derived state a fresh page does, or the second match in a
  // process plays differently from the first (see design-decisions.md).
  derived: function () {
    var keys = 0, entries = 0;
    for (var k in hash) { keys++; entries += hash[k].length; }
    return { hashAt: hashAt, hashKeys: keys, hashEntries: entries, pathQ: pathQ.length };
  },
  api: { astar: astar, linkWall: function (x, y, k) { return linkWall(x, y, k); }, damage: damage, canPlace: canPlace, canDeployMcv: canDeployMcv, economyDead: economyDead,
         countUnit: countUnit, hasBld: hasBld, genMap: genMap, newState: newState, findOre: findOre, canHit: canHit, isAir: isAir, altOf: altOf, countBld: countBld,
         findTarget: findTarget, isDisguised: isDisguised, prodSpeed: prodSpeed, weaponFor: weaponFor, reachOf: reachOf,
         // veterancy, so a test can ask the game its own multipliers rather
         // than re-deriving them and then agreeing with itself.
         vetFire: vetFire, vetRof: vetRof, vetRofU: vetRofU, vetRofAt: vetRofAt,
         vetSpeed: vetSpeed, vetArmour: vetArmour, eliteOf: eliteOf,
         canBuild: canBuild, swBld: swBld, techCount: techCount,
         // RA2's captured-production rule: the one faction gate, the
         // structure's own faction, and the sidebar list that follows it.
         bfacOf: bfacOf, facAllows: facAllows, hasFacBld: hasFacBld,
         producerOf: producerOf, keyFac: keyFac, bspecOfB: bspecOfB,
         panelKeys: panelKeys, reqMet: reqMet,
         // Which of the theatre's two grounds a cell wears. Exposed so the
         // "ore never lies on pavement" guard can ask the renderer's own
         // question instead of re-deriving it and agreeing with itself.
         dirtAt: dirtAt,
         blocked: blocked, adjOf: adjOf, buildMask: buildMask, gateOpen: gateOpen, applyGaps: applyGaps,
         gapped: gapped, tileSeen: tileSeen, entSeen: entSeen, versesVs: versesVs, isWall: isWall, detected: detected,
         aiSwTarget: aiSwTarget, aiSwValue: aiSwValue, aiPickTarget: aiPickTarget, aiDefencePlan: aiDefencePlan,
         bspecFor: bspecFor },
  // Phase 8 navy: the mover classes, the underwater visibility model and
  // the water-placement rule, so a test can ask the same questions the sim
  // asks rather than inferring them from a match.
  apiN: { MV_LAND: MV_LAND, MV_NAVAL: MV_NAVAL, MV_AMPH: MV_AMPH,
          terrPass: terrPass, moverOf: moverOf, isNaval: isNaval, isSub: isSub,
          isSensor: isSensor, subSeen: subSeen, surfaced: surfaced,
          waterPlot: waterPlot, nearestWater: nearestWater, hasShore: hasShore,
          dockSpot: dockSpot, freeWaterNear: freeWaterNear, shipSinks: shipSinks,
          SUB_SURFACE: SUB_SURFACE, AI_NAVAL_ADJ: AI_NAVAL_ADJ,
          labelWater: labelWater, waterZoneAt: waterZoneAt, hullZone: hullZone,
          navReach: navReach, orderUnitsTo: orderUnitsTo, collapseSpan: collapseSpan,
          aiCanMake: aiCanMake, unloadTransport: unloadTransport, paxCount: paxCount },
  // Baked sprite atlas, so art work can be reviewed as a contact sheet
  // instead of by hunting for one building in a live match.
  spr: function () { return SPR; },
  // An ISOLATED wall/gate segment. `SPR.bld[..].wall` is the four-way
  // cameo piece, which is not what the RA2 SHP frame shows, so the art
  // harness measures this instead (landing/games/rts/art/cmp.js -> aspect.py).
  wallSeg: function (p, fk, mask) { return wallSprite(p, fk, mask || 0); },
  gateSeg: function (p, fk, vert, openF) { return gateSprite(p, fk, !!vert, openF || 0); },

  // Start a bare match (no opening units) that the other hooks act on.
  // `live` (5th arg) leaves the RENDERER on, so an art or QA pass can drive
  // a set-piece and screenshot it instead of only asserting on numbers.
  begin: function (seed, diff) {
    setHeadless(!arguments[4]);
    setG(newState((seed >>> 0) || 1, diff || 'normal', arguments[2]));
    G.debug = !!arguments[3];
    setState('play');
    return G;
  },
  get: function () { return G; },
  // Attach an AI to one side only, so a test can play the other side by
  // hand (or not at all — "how long does a beginner who only builds
  // economy survive?" is a real question about the opening grace).
  attachAI: function (p, diff) {
    if (!G) return null;
    var a = newAI(diff || 'normal');
    if (p === P_AI) { G.ai = a; } else { G.ai2 = a; }
    G.focusFor[p] = a.cfg.focus;
    return a;
  },
  // Superweapons: read the timers, force one charged, fire one by hand.
  sw: function (p) { return G ? G.side[p].sw : null; },
  swCharge: function (p, k) { if (G) { G.side[p].sw[k].t = SW[k].charge; G.side[p].sw[k].ready = true; } },
  swFire: function (p, k, x, y, x2, y2) { return G ? swFire(G, p, k, x, y, x2, y2) : false; },
  credits: function (p) { return G ? G.side[p].credits : 0; },
  ore: function (x, y) { return G ? G.ore[y * MAP + x] : 0; },
  findOre: function (x, y) { return G ? findOre(G, x, y) : null; },
  buildFactor: function (p, lane) { return G ? buildFactor(G, p, lane) : 1; },
  // Phase 4b: the neutral house. Every one of these is the same call the
  // game itself makes, so a test cannot pass against a path the player
  // never takes.
  // Match flow: the skirmish strip, the save format and a state hash the
  // save/load round-trip test compares.
  opts: function () { return G ? G.opt : null; },
  setOpts: function (o) { setOpts(normOpts(o)); return opts; },
  startWith: function (seed, diff, map, o) {
    setHeadless(true);
    setG(newState((seed >>> 0) || 1, diff || 'normal', map, o));
    setState('play');
    [P_HUMAN, P_AI].forEach(function (p) { openingForce(G, p); });
    return G;
  },
  step: function (n) { for (var i = 0; i < (n || 1); i++) simStep(G); return G; },
  hash: function (g) { return stateHash(g || G); },
  eva: function (line, gap) { return eva(line, gap); },
  evaLog: function () { return evaLog.slice(); },
  save: function (n) { return saveGame(n); },
  load: function (n) { return loadGame(n); },
  saveBlob: function () { return serialiseGame(G); },
  loadBlob: function (blob) { setG(restoreGame(JSON.parse(JSON.stringify(blob)))); return G; },
  slots: function () { return saveSlots(); },
  reloadKeep: function () { reloadKeepMatch(); },
  autosave: function () { autosaveForReload(); },
  resumeFlag: function () { return lsGet(RESUME_KEY); },
  setResumeFlag: function (v) { lsSet(RESUME_KEY, v); },
  world: function () { return G; },
  // Bakers must never touch the SIM's RNG (two tabs desynced the tick one of
  // them first drew a Barracks). Runs the lazy bakers and reports the seed.
  bakeProbe: function () {
    var s0 = _seed;
    bakeBuilding('barracks', COL[0], 'dir', 0, 0, 0);
    bakeBuilding('refinery', COL[1], 'col', 0, 0, 0);
    bakeGroundSheet('grass', 41); bakeTree(0, false); bakeOre(2, 0); bakeDecal('crater', 0);
    return { before: s0, after: _seed };
  },
  setGroup: function (k, units) { groups[k] = units.slice(); },
  group: function (k) { return (groups[k] || []).slice(); },
  setView: function (n, v) { views[n] = v; },
  view: function (n) { return views[n] || null; },
  restoreSession: function () { restoreSession(); },
  ownTargetOrder: ownTargetOrder,
  placeOrigin: placeOrigin,
  cancelLast: function (lane, key) { return G ? cancelLast(G, 0, lane, key) : false; },
  cmd: function (type, payload) { return cmd(type, payload); },
  plate: function (k) { return mapPlate(k); },
  resumeWanted: resumeWanted,
  unclose: function () { setClosedByUser(false); },
  setState: function (st) { setState(st); },
  score: function (p) { return scoreOf(G, p); },
  crates: function () { return G ? G.crates : []; },
  spawnCrate: function (kind, x, y) {
    if (!G) return null;
    var cr = { x: x, y: y, kind: kind, born: G.tick, id: G.nextId++ };
    G.crates.push(cr); return cr;
  },
  bridges: function () { return G ? G.bridges : []; },
  neutrals: function () { return G ? G.blds.filter(function (b) { return !b.dead && BLDS[b.type].neut; }) : []; },
  occupants: function (b) { return b && b.occ ? b.occ.length : 0; },
  garrison: function (b, u) { return G ? enterGarrison(G, b, u) : false; },
  eject: function (b) { return G ? ejectGarrison(G, b) : 0; },
  orderGarrison: function (units, b) {
    var n = 0;
    units.forEach(function (u) {
      if (!canOccupy(u.type) || !garrisonable(G, b, u.p)) return;
      u.order = { t: 'garrison', x: 0, y: 0, id: b.id }; u.repathAt = -999;
      requestPath(G, u, Math.round(b.cx), Math.round(b.cy)); n++;
    });
    return n;
  },
  // Phase 8: transports. Every hook is the same call the game makes.
  passengers: function (tr) { return tr && tr.pax ? tr.pax.slice() : []; },
  board: function (tr, u) { return G ? boardTransport(G, tr, u) : false; },
  unload: function (tr) { return G ? unloadTransport(G, tr).length : 0; },
  orderEnter: function (units, tr) {
    var n = 0, room = paxCapOf(tr) - paxCount(tr);
    units.forEach(function (u) {
      if (n >= room || !canBoard(G, tr, u)) return;
      u.order = { t: 'enter', x: 0, y: 0, id: tr.id }; u.repathAt = -999; u.path = null;
      requestPath(G, u, Math.round(tr.x), Math.round(tr.y)); n++;
    });
    if (n && UNITS[tr.type].air) { tr.landReq = 1; tr.order = null; tr.path = null; }
    return n;
  },
  orderUnload: function (tr) {
    if (!tr) return 0;
    if (UNITS[tr.type].air) { tr.landReq = 1; tr.unloadReq = 1; tr.order = null; tr.path = null; return 0; }
    return unloadTransport(G, tr).length;
  },
  orderCapture: function (units, b) {
    var n = 0;
    units.forEach(function (u) {
      if (!UNITS[u.type].capture) return;
      u.order = { t: 'capture', x: 0, y: 0, id: b.id }; u.repathAt = -999;
      requestPath(G, u, Math.round(b.cx), Math.round(b.cy)); n++;
    });
    return n;
  },
  // Phase 4c: the special-unit mechanics, each reachable the same way the
  // game reaches it (an ORDER, not a poke at the field it sets).
  orderCoil: function (units, b) {
    var n = 0;
    units.forEach(function (u) {
      if (!UNITS[u.type].coiler || !b || b.type !== 'tesla' || b.p !== u.p) return;
      u.order = { t: 'coil', x: 0, y: 0, id: b.id }; u.repathAt = -999; u.path = null;
      requestPath(G, u, Math.round(b.cx), Math.round(b.cy)); n++;
    });
    return n;
  },
  orderInfil: function (units, b) { return G ? orderAttack(G, units, b) : 0; },
  // The player's right-click on one of their OWN buildings. This runs the
  // real `applyCmd` case rather than re-implementing it, because the hooks
  // beside it that DO re-implement their command (orderCoil, orderCapture)
  // can pass while the path the player actually takes is broken — which is
  // how the miner-to-refinery order shipped broken twice.
  orderOwn: function (units, tgt) {
    if (!G || !tgt) return 0;
    applyCmd(G, ME, { t: 'own', u: idsOf(units), id: tgt.id });
    return units.length;
  },
  deploy: function (units, on) {
    units.forEach(function (u) { u.deployed = !!on; u.order = null; u.path = null; });
    return units.length;
  },
  rad: function (x, y) { return G ? radAt(G, x, y) : 0; },
  bombs: function () { return G ? G.bombs : []; },
  api3: { infest: infest, popDrone: popDrone, killDrone: killDrone, uspd: uspd,
          plantBomb: plantBomb, defuseBomb: defuseBomb, engineerDefuse: engineerDefuse,
          mindControl: mindControl, releaseMind: releaseMind, psiImmune: psiImmune,
          startErase: startErase, beginWarp: beginWarp, chronoDelayFor: chronoDelayFor,
          addRad: addRad, radAt: radAt, coilCharged: coilCharged, spyInfiltrate: spyInfiltrate,
          isHarv: isHarv, harvKey: harvKey, powered: powered, unitOrderFor: unitOrderFor,
          paxCapOf: paxCapOf, paxCount: paxCount, canBoard: canBoard, killPassengers: killPassengers,
          ifvModeOf: ifvModeOf, ifvSpec: ifvSpec, ifvTurret: ifvTurret,
          IFV_MODE: IFV_MODE, IFV_MODES: IFV_MODES, AI_TEAMS: AI_TEAMS, LAND_T: LAND_T,
          fire: fire, findRefinery: findRefinery, refDock: refDock,
          IVAN_BOMB_T: IVAN_BOMB_T, RAD_MAX: RAD_MAX, CHRONO_DELAY: CHRONO_DELAY,
          SPY_BLACKOUT: SPY_BLACKOUT, COIL_BOOST: COIL_BOOST, PARASITE_DMG: PARASITE_DMG },
  api2: { damageBridge: damageBridge, collapseSpan: collapseSpan, repairBridgeFrom: repairBridgeFrom,
          garrisonable: garrisonable, canOccupy: canOccupy, occCapOf: occCapOf, occCount: occCount,
          stepOreSpread: stepOreSpread, stepCrates: stepCrates, openCrate: openCrate,
          spySatUp: spySatUp, cloneVatsOf: cloneVatsOf, paraDrop: paraDrop, uspd: uspd,
          placeNeutrals: placeNeutrals, indexBridges: indexBridges, ORE_SPREAD_T: ORE_SPREAD_T }
};

// Headless match runner used by the balance tests: no rendering, no audio.
// Both sides are driven by the same AI code (stepAI is side-agnostic), so
// "hard beats easy" measures the decision layers and nothing else.
// The audio harness drives this: every synth can be rendered offline into
// an OfflineAudioContext and measured, and `log` says which one fired for
// a given game event without anything having to be heard.
window.__rtsAudio = {
  SPEC: SPEC, REPORT: REPORT, VOX: VOX, VOXPAT: VOXPAT,
  kinds: function () { return Object.keys(PLAY); },
  log: function () { return aLog.slice(); },
  // Also drops the 70 ms per-sound throttle, the voice throttle and the
  // live-voice list, so a harness stepping 900 ticks in a millisecond is
  // not measuring wall-clock rate limits it never meant to exercise.
  clear: function () {
    aLog.length = 0; aStat.calls = aStat.played = aStat.dropped = 0; aStat.ms = 0;
    setSfxAt({}); setAckAt(0); live.length = 0;
  },
  stats: function () { return { calls: aStat.calls, played: aStat.played, dropped: aStat.dropped, ms: aStat.ms, live: live.length }; },
  music: function () { return MUS.state(); },
  ack: function (units, kind) { return unitAck(units, kind); },
  vol: function () { return { sfx: vol.sfx, voice: vol.voice, music: vol.music, on: soundOn, musicOn: musicOn }; },
  // One sound, rendered dry into `secs` of mono 44.1 kHz.
  render: function (kind, secs) {
    var OC = window.OfflineAudioContext || window.webkitOfflineAudioContext;
    if (!OC || !PLAY[kind]) return null;
    var c = new OC(1, Math.floor(44100 * (secs || 3)), 44100);
    var g = c.createGain(); g.gain.value = (SPEC[kind] ? SPEC[kind].v : 1);
    g.connect(c.destination);
    PLAY[kind](c, g, 0.02);
    return c.startRendering();
  },
  // One acknowledgement, likewise.
  renderVox: function (type, kind, sov, secs) {
    var OC = window.OfflineAudioContext || window.webkitOfflineAudioContext;
    var vx = VOX[type]; if (!OC || !vx || !vx.f) return null;
    var key = kind === 'select' ? 's' : kind === 'attack' ? 'a' : kind === 'deploy' ? 'd' : kind === 'harvest' ? 'h' : 'm';
    var pats = (vx[key] && vx[key].length) ? vx[key] : vx.m;
    if (!pats || !pats.length) return null;
    var c = new OC(1, Math.floor(44100 * (secs || 3)), 44100);
    var g = c.createGain(); g.gain.value = 1; g.connect(c.destination);
    voxLine(c, g, 0.02, vx.f * (sov ? 0.86 : 1), vx.b * (sov ? 0.94 : 1),
            Math.min(0.75, vx.r + (sov ? 0.12 : 0)), VOXPAT[pats[0]], sov ? 1.12 : 1);
    return c.startRendering();
  },
  renderMusic: function (theme, secs, heat) { return MUS.render(theme, secs || 3, heat); }
};

window.__rtsSim = function (seed, diffA, diffB, maxTicks, facA, facB, everyMinute) {
  var prevG = G, prevHeadless = headless, prevState = state;
  netStash();
  var prevNet = NET.active;                 // the menu/match client, parked
  setHeadless(true);
  try {
    var g = newState(seed >>> 0, diffB || 'normal', arguments[7], arguments[8]);
    g.side[P_HUMAN].fac = FACTIONS[facA] ? facA : 'dir';
    g.side[P_AI].fac = FACTIONS[facB] ? facB : 'col';
    g.ai = newAI(diffB || 'normal');      // player 1
    g.ai2 = newAI(diffA || 'normal');     // player 0
    g.focusFor[P_AI] = g.ai.cfg.focus;
    g.focusFor[P_HUMAN] = g.ai2.cfg.focus;
    [P_HUMAN, P_AI].forEach(function (p) { openingForce(g, p); });

    setG(g);
    var cap = maxTicks || 60 * 60 * 25;
    while (g.tick < cap && !g.over) {
      simStep(g);
      if ((g.tick % 120) === 0) sampleStuck(g);
      if (everyMinute && (g.tick % 3600) === 0) everyMinute(g);
    }
    return {
      ticks: g.tick, over: g.over,
      p0blds: g.blds.filter(function (b) { return !b.dead && b.p === P_HUMAN; }).length,
      p1blds: g.blds.filter(function (b) { return !b.dead && b.p === P_AI; }).length,
      p0units: countUnit(g, P_HUMAN, null), p1units: countUnit(g, P_AI, null),
      p0credits: Math.round(g.side[P_HUMAN].credits),
      p1credits: Math.round(g.side[P_AI].credits),
      p0made: g.side[P_HUMAN].made, p1made: g.side[P_AI].made,
      p0fac: g.side[P_HUMAN].fac, p1fac: g.side[P_AI].fac,
      p0mix: bldMix(g, P_HUMAN), p1mix: bldMix(g, P_AI),
      p0q: queueState(g, P_HUMAN), p1q: queueState(g, P_AI),
      stuck: countStuck(g)
    };
  } finally {
    setG(prevG); setHeadless(prevHeadless); setState(prevState);
    if (prevNet) netLoad(prevNet); else NET.active = null;
  }
};

// Stuck detection has to be sampled over TIME. Checking "did it move on the
// final frame" flags a unit that merely paused to fire, and misses one that
// has been wedged against a rock for four minutes.
function sampleStuck(g) {
  for (var i = 0; i < g.units.length; i++) {
    var u = g.units[i];
    if (u.dead) continue;
    var moved = Math.abs(u.x - u.lastx) > 0.02 || Math.abs(u.y - u.lasty) > 0.02;
    var wants = (!!u.order || u.state === 'tomine' || u.state === 'toref') &&
                u.state !== 'mining';
    // A unit standing still because it is SHOOTING is doing its job. Only
    // a unit that wants to be somewhere and is not getting there is stuck.
    // (Slow, slow-firing units like the Mammoth sit in cooldown for over a
    // second at a time and were being counted as frozen.)
    var fighting = u.cool > 0;
    if (wants && !moved && !fighting) u.stuck++; else u.stuck = 0;
    u.lastx = u.x; u.lasty = u.y;
  }
}

function bldMix(g, p) {
  var m = {};
  for (var i = 0; i < g.blds.length; i++) {
    var b = g.blds[i];
    if (!b.dead && b.p === p) m[b.type] = (m[b.type] || 0) + 1;
  }
  return m;
}

function queueState(g, p) {
  var q = g.side[p].queues;
  return { b: q.b.list.slice(), ready: q.b.ready, i: q.i.list.slice(), v: q.v.list.slice(), a: q.a.list.slice() };
}

function countStuck(g) {
  var n = 0;
  for (var i = 0; i < g.units.length; i++) {
    if (!g.units[i].dead && g.units[i].stuck >= 3) n++;
  }
  return n;
}

window.__rtsFocus = function (gx, gy) { centerOn(gx, gy); clampCam(); };

window.__rtsCam = function () { return { x: Math.round(cam.x), y: Math.round(cam.y) }; };

window.__rtsScreen = function (gx, gy) { return { x: sx(gx, gy), y: sy(gx, gy) }; };

window.__rtsBuildFactor = function (lane) { return G ? buildFactor(G, ME, lane) : 1; };

window.__rtsTables = { AI_TEAMS: AI_TEAMS, SW: SW, SW_KEYS: SW_KEYS, UNITS: UNITS, BLDS: BLDS, DIFF: DIFF, MAP: MAP, FACTIONS: FACTIONS, MAPS: MAPS, TER: { GROUND: T_GROUND, ROCK: T_ROCK, ORE: T_ORE, WATER: T_WATER, CLIFF: T_CLIFF, TREE: T_TREE, ROAD: T_ROAD, RAMP: T_RAMP, BRIDGE: T_BRIDGE, GEM: T_GEM, CIV: T_CIV }, VERSES: VERSES, ARMOURS: ARMOURS, IFV_MODES: IFV_MODES, verses: verses, weaponFor: weaponFor, bspecFor: bspecFor, eliteOf: eliteOf };
