// Iron Frontier — move.js
// GENERATED by apps/games/rts/tools/modularize from rts.src.html + art/units/**.

import { aimHull, aimTurret, faceOf, rotOf, slew, slews } from './bake/kit.js';
import { BLDS } from './blds.js';
import { bspecOfB, depFireTarget, isHarv, isInfArmour, reachOf, uspd, weaponFor } from './combat-tables.js';
import { damage, dist, entX, entY, findTarget, fire, near } from './combat.js';
import { recalcPower } from './entities.js';
import { FACTIONS, bfacOf } from './factions.js';
import { PAD_SLOTS, airborneYet, canHit, edgeDist, moverOf, padSlot, rngVs, tooClose } from './geom.js';
import { enterGarrison, garrisonable, killOccupants, repairBridgeFrom } from './neutral.js';
import { stepHarvester } from './ore.js';
import { gateOpen, requestPath } from './path.js';
import { countBld } from './production.js';
import { UNITS, ifvSpec } from './roster.js';
import { DESO_RAD_LEVEL, DESO_RAD_R, DESO_RAD_T, addRad, beginWarp, coilCrew, dropFromSel, engineerDefuse, spyInfiltrate, stepWarp } from './special.js';
import { headless, idx, inMap } from './state.js';
import { boardTransport, paxCapOf, paxCount, stepRepairIFV, stepSpawned, stepSpawner, unloadTransport } from './transport.js';
import { eva, sfx } from './ui/audio.js';
import { creditPop, say } from './ui/hud.js';
import { fireGround, giveUpEnter, nextWaypoint } from './ui/input.js';
import { GUARD_STRAY, MAP, ME, P_NEUT, isAiSide, neutral, terrPass } from './world.js';

// --------------------------------------------------------------------- //
//  Movement
// --------------------------------------------------------------------- //
// RA2 Crusher=yes / Crushable=yes: a ground vehicle (not the Terror Drone)
// drives straight through enemy infantry and kills what it rolls over; the
// Tesla Trooper's suit is the one uncrushable body.
function crusher(u) { var d = UNITS[u.type]; return d.cls === 'v' && !d.air && !u.air; }

function crushable(o) { return o.kind === 'u' && !o.air && isInfArmour(UNITS[o.type].armour) && o.type !== 'teslatrooper' && o.type !== 'drone'; }

function crush(g, u, o) {
  u.crushKill = true;                                   // picks InfDeath 6 (the splat)
  damage(g, u, o, o.maxhp * 20, 'Super');
  u.crushKill = false;
  if (!headless) sfx('squish', o.x, o.y);   // CrushSound=InfantrySquish
}

function moveAlong(g, u, spd) {
  if (!u.path || u.pi >= u.path.length) return false;
  var wp = u.path[u.pi];
  var dx = wp.x - u.x, dy = wp.y - u.y;
  var d = Math.sqrt(dx * dx + dy * dy);
  if (d < 0.16) {
    u.pi++;
    if (u.pi >= u.path.length) { u.path = null; return false; }
    return true;
  }
  // Separation: nudge apart from neighbours so a group spreads instead of
  // stacking into one tile (also keeps splash from one-shotting a blob).
  var sx = 0, sy = 0;
  var cr = crusher(u) && u.type !== 'drone';
  near(u.x, u.y, 1.1, function (o) {
    if (o === u || o.dead || o.kind !== 'u' || o.air) return;
    if (cr && o.p !== u.p && crushable(o)) return;        // a tank does not step around enemy infantry
    var ox = u.x - o.x, oy = u.y - o.y;
    var od = Math.sqrt(ox * ox + oy * oy);
    if (od > 0.001 && od < 0.85) { sx += ox / od * (0.85 - od); sy += oy / od * (0.85 - od); }
  });

  var vx = dx / d * spd + sx * spd * 0.9;
  var vy = dy / d * spd + sy * spd * 0.9;
  var nx = u.x + vx, ny = u.y + vy;

  // Don't walk into rock or a building; slide along instead.
  var _mv = moverOf(u);
  if (!tilePassable(g, nx, u.y, u.p, _mv)) nx = u.x;
  if (!tilePassable(g, u.x, ny, u.p, _mv)) ny = u.y;
  u.x = Math.max(0, Math.min(MAP - 1, nx)); u.y = Math.max(0, Math.min(MAP - 1, ny));
  if (cr) near(u.x, u.y, 0.7, function (o) {
    if (o.dead || o.p === u.p || !crushable(o)) return;
    var cx = u.x - o.x, cy = u.y - o.y;
    if (cx * cx + cy * cy < 0.2) crush(g, u, o);           // within ~0.45 of a tile: under the tracks
  });

  // The hull turns at its own ROT rather than snapping to the new
  // bearing: a Grizzly pivots onto its heading over about a second. The
  // MOVEMENT vector above is untouched and continuous — only the drawn
  // bearing is quantised, and only to 32.
  if (slews(u)) slew(u, 'face', 'fsub', faceOf(dy, dx), rotOf(u.type));
  else { u.face = faceOf(dy, dx); u.fsub = 0; }
  u.movedAt = g.tick;
  return true;
}

// Aircraft: no path, no terrain, no occupancy — a straight line at altitude,
// with a light separation from other aircraft so a flight does not stack.
export function flyToward(g, u, tx, ty, spd) {
  var dx = tx - u.x, dy = ty - u.y, d = Math.sqrt(dx * dx + dy * dy);
  if (d < 0.12) return false;
  var sx = 0, sy = 0;
  near(u.x, u.y, 1.0, function (o) {
    if (o === u || o.dead || !o.air || o.landed) return;
    var ox = u.x - o.x, oy = u.y - o.y, od = Math.sqrt(ox * ox + oy * oy);
    if (od > 0.001 && od < 0.7) { sx += ox / od * (0.7 - od); sy += oy / od * (0.7 - od); }
  });
  var step = Math.min(spd, d);
  u.x = Math.max(0, Math.min(MAP - 1, u.x + dx / d * step + sx * spd * 0.5));
  u.y = Math.max(0, Math.min(MAP - 1, u.y + dy / d * step + sy * spd * 0.5));
  slew(u, 'face', 'fsub', faceOf(dy, dx), rotOf(u.type));      // [ORCA] ROT=3: a jet banks round
  u.movedAt = g.tick; u.noProg = 0; u.path = null;
  return true;
}

// refresh = ticks between re-plans while a path is already being followed.
// An idle flyer holds a slow hover circle over its post instead of hanging
// motionless in the sky (RA2 Harriers and Rocketeers orbit). A Kirov is too
// big and too slow to orbit — it just sits.
export function hoverIdle(g, u) {
  var d = UNITS[u.type];
  if (!u.air || u.landed || u.order || d.bomb) return;
  if (!airborneYet(u)) return;                     // still climbing off the ground
  if (u.guardX == null) { u.guardX = u.x; u.guardY = u.y; }
  u.hov = (u.hov || 0) + 0.05;
  var c = Math.cos(u.hov), sn = Math.sin(u.hov), r = 0.45;
  u.x = Math.max(0, Math.min(MAP - 1, u.guardX + c * r));
  u.y = Math.max(0, Math.min(MAP - 1, u.guardY + sn * r * 0.6));
  slew(u, 'face', 'fsub', faceOf(c * 0.6, -sn), rotOf(u.type));
  u.movedAt = g.tick;
}

export function advance(g, u, tx, ty, spd, refresh) {
  if (u.prone) {
    // A short shuffle is a crawl (art.ini `Crawl=86,6,6`, and it is slow);
    // anything that is actually going somewhere gets him back on his feet.
    if (Math.abs(tx - u.x) + Math.abs(ty - u.y) > 3.5) { u.prone = false; u.upAt = g.tick; }
    else spd *= 0.45;
  }
  if (u.deployed) {
    // Chasing a target undeploys; a plain hold stays put.
    if (isAiSide(g, u.p) && u.order && u.order.t !== 'attack') u.deployed = false; else return false;   // deployed men do not walk
  }
  if (u.air) return flyToward(g, u, tx, ty, spd);
  if (!u.path) {
    if (g.tick - u.repathAt > 8) { requestPath(g, u, tx, ty); u.repathAt = g.tick; }
  } else if (refresh && g.tick - u.repathAt > refresh) {
    requestPath(g, u, tx, ty); u.repathAt = g.tick;
  }
  // Track failure to make progress HERE. Callers used to test
  // `g.tick - u.repathAt > N`, which can never become true: the lines above
  // reset repathAt every 8 ticks precisely while a unit has no path, so the
  // give-up branches that depended on it were dead code. noProg counts
  // consecutive ticks of getting nowhere and is the honest signal.
  var ok = moveAlong(g, u, spd);
  if (ok) u.noProg = 0; else u.noProg = (u.noProg || 0) + 1;
  return ok;
}

export function tilePassable(g, fx, fy, p, mv) {
  var x = Math.round(fx), y = Math.round(fy);
  if (!inMap(x, y)) return false;
  var i = idx(x, y);
  if (!terrPass(g.terrain[i], mv)) return false;
  if (g.occ[i] === 0) return true;
  // An open gate is a hole in the wall; a shut one your own men may stand
  // in front of, but not walk through, until the leaves have travelled.
  return gateOpen(g, i);
}

// --------------------------------------------------------------------- //
//  Per-unit tick
// --------------------------------------------------------------------- //
export function stepUnit(g, u) {
  var d = UNITS[u.type];
  // A drone that has climbed inside a tank is not on the map at all; a
  // Chrono Legionnaire mid-warp is out of phase; a unit being erased is
  // frozen out of time. None of the three takes a turn.
  if (u.warp) { stepWarp(g, u); if (u.warp) return; }
  if (u.limbo) return;
  if (u.erase > 0) return;
  if (u.cool > 0) u.cool--;
  // [DESO]/[CMIN] SelfHealing=yes — slow, and it never brings a corpse back.
  if (d.selfHeal && u.hp < u.maxhp && (g.tick % 45) === 0) u.hp = Math.min(u.maxhp, u.hp + u.maxhp * 0.004);
  // [ENGINEER] Primary=DefuseKit, BombSight=4: he walks past a ticking
  // bomb and takes it off without being spent.
  if (d.capture && (g.tick % 15) === (u.id % 15)) engineerDefuse(g, u);
  // Four seconds without being shot at and a prone man gets back on his
  // feet (art.ini `Up=276,2,2`). Held here rather than in `damage()` so a
  // trooper pinned by continuous fire never stands up into it.
  if (u.prone && g.tick - (u.hitAt || 0) > 240) { u.prone = false; u.upAt = g.tick; }
  if (u.rank === 2 && u.hp < u.maxhp && (g.tick % 30) === 0) u.hp = Math.min(u.maxhp, u.hp + u.maxhp * 0.005);   // EliteAbilities=SELF_HEAL
  // A turret swings back to the hull's line 1.5 s after it last aimed.
  // ...and it swings back at the same ROT rather than snapping.
  if (u.tface != null && g.tick - (u.aimAt || 0) > 90 &&
      slew(u, 'tface', 'tsub', u.face | 0, rotOf(u.type))) u.tface = null;

  if (isHarv(u)) {
    // Harvesters flee toward the nearest refinery when shot at rather than
    // standing in the open being farmed.
    stepHarvester(g, u);
    return;
  }
  // A hull is fenced in by the shoreline in a way a tank is not: an order
  // aimed at the far side of a headland, or at a second body of water, is
  // one it can NEVER complete, and the chase branch below has no give-up in
  // it (a land unit always has some route). Four seconds of no path and no
  // progress and the ship drops the order and holds station — measured on
  // Coastal, where one Destroyer ordered across a spit re-flagged B1-stuck
  // 419 times in a single match. Naval only, so no land unit's behaviour and
  // no pinned Iron Frontier snapshot can move.
  if (d.nav && u.order && !u.path && u.noProg > 240) {
    u.order = null; u.noProg = 0; u.guardX = u.x; u.guardY = u.y;
    // ...and it STAYS given up for ten seconds. Without the hold the AI's
    // next tactical pass hands the hull the same unreachable order and the
    // pair of them churn for the rest of the match.
    u.navHold = g.tick + 600;
    nextWaypoint(g, u);
    return;
  }
  // [SHAD] Landable=yes, JumpJet locomotor, no `ammo`: the Nighthawk never
  // joins the Airforce Command's pad cycle. It sets down on whatever clear
  // cell it is over to load or unload, and stays down until it is moved.
  if (d.air && d.pax) {
    if (u.order && u.order.t !== 'enter') u.landReq = 0;
    if (u.order && u.landed) { u.landed = false; u.flyAt = g.tick; }
    if (u.landReq && !u.landed && !u.order && airborneYet(u) &&
        tilePassable(g, u.x, u.y, u.p)) { u.landed = true; u.landAt = g.tick; }
    if (u.landed) {
      var down = g.tick - (u.landAt == null ? -9999 : u.landAt) >= LAND_T;
      if (down && u.unloadReq) { unloadTransport(g, u); u.unloadReq = 0; if (!paxCount(u)) u.landReq = 0; }
    }
  }
  if (d.spawned) { stepSpawned(g, u); return; }
  if (d.spawns) stepSpawner(g, u);
  if (d.ammo) { stepAircraft(g, u); return; }

  // [RadEruptionWeapon] AreaFire / FireOnce=no: a deployed Desolator does
  // nothing but keep the ground under him lethal, for as long as he stands.
  if (u.deployed && d.deployRad) {
    if ((g.tick % DESO_RAD_T) === 0) addRad(g, u.x, u.y, DESO_RAD_LEVEL, DESO_RAD_R);
    return;
  }
  // Teleport locomotor ([CLEG] Locomotor={...2747}): it does not walk to
  // where it was sent, it warps, after ChronoTrigger's distance-scaled delay.
  if (d.teleport) {
    var tw = null;
    if (u.order && (u.order.t === 'move' || u.order.t === 'amove')) tw = { x: u.order.x, y: u.order.y };
    else if (u.order && u.order.t === 'attack') {
      var ot0 = entById(g, u.order.id);
      if (ot0 && dist(u, ot0) > d.rng) {
        // Land just inside weapon range, not on top of what we came to erase.
        var tx0 = entX(ot0), ty0 = entY(ot0), dl = dist(u, ot0) || 1;
        tw = { x: tx0 + (u.x - tx0) / dl * (d.rng - 1), y: ty0 + (u.y - ty0) / dl * (d.rng - 1) };
      }
    }
    if (tw && beginWarp(g, u, tw.x, tw.y)) return;
  }

  // A Tesla Trooper sent onto one of our own Tesla Coils stands beside it
  // and hand-feeds it: RA2's charged coil fires with the grid down.
  if (u.order && u.order.t === 'coil') {
    var cb0 = entById(g, u.order.id);
    if (!cb0 || cb0.dead || cb0.p !== u.p || cb0.type !== 'tesla') { u.order = null; return; }
    if (dist(u, cb0) <= Math.max(cb0.gw, cb0.gh) / 2 + 1.3) {
      u.path = null; u.guardX = u.x; u.guardY = u.y;
      if (!coilCrew(g, cb0)) { u.order = null; return; }      // the coil already has its three
      u.coilAt = g.tick;
      // He still shoots what walks into his own three-cell reach.
      if (u.cool <= 0) { var ct0 = findTarget(g, u, reachOf(d, u)); if (ct0) fire(g, u, ct0); }   // [ElectricBoltE] is Range 5
      return;
    }
    advance(g, u, Math.round(cb0.cx), Math.round(cb0.cy), uspd(u), 60);
    return;
  }

  // A Spy walks in through the front door and is spent inside.
  if (u.order && u.order.t === 'infil') {
    var sb0 = entById(g, u.order.id);
    if (!sb0 || sb0.dead || sb0.p === u.p || neutral(sb0.p)) { u.order = null; return; }
    if (dist(u, sb0) <= Math.max(sb0.gw, sb0.gh) / 2 + 1.1) {
      spyInfiltrate(g, u, sb0);
      u.dead = true; u.order = null;
      if (u.sel) dropFromSel(u);
      return;
    }
    advance(g, u, Math.round(sb0.cx), Math.round(sb0.cy), uspd(u), 60);
    return;
  }

  // A MOVE order is an explicit instruction and outranks opportunistic
  // fire: the unit goes where it was sent. It shoots on the way — standing
  // still to do that is what made ordered troops refuse to disengage — and
  // resumes normal engagement once it arrives and the order clears.
  // GARRISON. RA2's Enter mission: walk to the block, then step inside and
  // stop being a unit. A block that filled up or changed hands on the way
  // just cancels the order rather than leaving the man standing in the road.
  if (u.order && u.order.t === 'garrison') {
    var gb = entById(g, u.order.id);
    if (!gb || gb.dead || !garrisonable(g, gb, u.p)) { u.order = null; return; }
    if (dist(u, gb) <= Math.max(gb.gw, gb.gh) / 2 + 1.1) { enterGarrison(g, gb, u); return; }
    if (!advance(g, u, Math.round(gb.cx), Math.round(gb.cy), uspd(u), 60) && !u.path && u.noProg > 90) giveUpEnter(g, u, 'that building');
    return;
  }
  // ENTER a transport. RA2's Enter mission again: walk to the hull, then
  // step inside and stop being a unit. A hull that filled up, died or is
  // still in the air on the way just cancels the order.
  if (u.order && u.order.t === 'enter') {
    var tr = entById(g, u.order.id);
    if (!tr || tr.dead || tr.kind !== 'u' || paxCount(tr) >= paxCapOf(tr) || tr.p !== u.p) { u.order = null; return; }
    if (dist(u, tr) <= 1.5) {                                  // any of the 8 neighbour cells (a diagonal is 1.41)
      if (tr.air && !tr.landed) { u.path = null; return; }     // wait for it to touch down
      if (boardTransport(g, tr, u)) return;
      u.order = null; return;
    }
    // Give up only when stuck FAR from the hull: a squad queueing round a
    // transport makes no progress for a while and that is not a lost route.
    // (The stuck-forever case the audit found was the 1.4 threshold above:
    // a man arriving on a DIAGONAL neighbour cell sits 1.41 away and never
    // boarded — "1 on the way" for the rest of the match.)
    if (!advance(g, u, Math.round(tr.x), Math.round(tr.y), uspd(u), 24) && !u.path && u.noProg > 90 && dist(u, tr) > 3) giveUpEnter(g, u, 'the transport');
    return;
  }
  if (u.order && u.order.t === 'capture') {
    // Engineer: walk into the enemy structure and take it over (RA2 rules:
    // the engineer is consumed, the building keeps its damage).
    var cb = entById(g, u.order.id);
    var ownFix = cb && !cb.dead && cb.p === u.p && !BLDS[cb.type].hut && cb.hp < cb.maxhp;
    if (!cb || cb.dead || (cb.p === u.p && !BLDS[cb.type].hut && !ownFix)) { u.order = null; return; }
    if (dist(u, cb) <= Math.max(cb.gw, cb.gh) / 2 + 1.1) {
      var cbd = BLDS[cb.type];
      // RA2's Engineer on YOUR OWN damaged building: it goes straight back
      // to full strength and he is spent doing it. Free, instant, and the
      // reason an Engineer is worth keeping behind the line.
      if (cb.p === u.p && !cbd.hut) {
        if (cb.hp >= cb.maxhp) { u.order = null; return; }
        cb.hp = cb.maxhp; cb.repair = false;
        u.dead = true; u.order = null;
        if (u.sel) dropFromSel(u);
        if (u.p === ME) { eva('Structure repaired', 3000); say(bspecOfB(g, cb).name + ' repaired'); }
        return;
      }
      // [CABHUT] BridgeRepairHut=yes — the engineer is spent rebuilding the
      // span, and the hut stays neutral.
      if (cbd.hut) {
        var nsp = repairBridgeFrom(g, cb);
        u.dead = true; u.order = null;
        if (nsp && u.p === ME) { eva('Bridge repaired', 4000); say('Bridge repaired'); }   // eva.ini #46
        else if (!nsp && u.p === ME) say('Nothing to repair — the span is already standing', true);
        return;
      }
      // A garrisoned civilian block is not captured, it is CLEARED: RA2's
      // engineer throws the occupants out and the block goes back to nobody.
      if (cbd.civ) {
        killOccupants(g, cb);
        cb.p = P_NEUT; cb.sel = false; cb.target = null;
        u.dead = true; u.order = null;
        if (u.p === ME) { eva('Structure abandoned', 3000); say('Building cleared'); }
        return;
      }
      var oldP = cb.p; cb.p = u.p; cb.sel = false; cb.rally = null;
      recalcPower(g, oldP); recalcPower(g, u.p);
      u.dead = true; u.order = null;
      // [CAOILD] ProduceCashStartup=1000 — the derrick pays out the moment
      // it changes hands from the Neutral house.
      if (cbd.cashStart && neutral(oldP)) {
        g.side[cb.p].credits += cbd.cashStart;
        if (cb.p === ME && !headless) { creditPop(cbd.cashStart); sfx('cash'); }
      }
      if (cbd.neut) {
        if (u.p === ME) eva('Tech building captured', 3000);          // eva.ini #105
        else if (oldP === ME) eva('Tech building lost', 3000);        // eva.ini #106
      } else if (u.p === ME) {
        eva('Structure captured', 3000);
        // A captured production building is the one capture that changes
        // what you can BUILD, and nothing else on screen says so.
        var cfk = bfacOf(g, cb);
        if (cbd.makes && cfk !== g.side[u.p].fac) {
          var what = { b: 'structures', i: 'infantry', v: 'vehicles', a: 'aircraft', n: 'ships' }[cbd.makes];
          say(FACTIONS[cfk].name + ' ' + bspecOfB(g, cb).name + ' captured — their ' + what +
              ' are on your sidebar now', false, 300);
        }
      }
      else if (oldP === ME) eva('Structure captured by the enemy', 3000);
      return;
    }
    if (!advance(g, u, Math.round(cb.cx), Math.round(cb.cy), uspd(u), 60) && !u.path && u.noProg > 90) giveUpEnter(g, u, 'that building');
    return;
  }
  // ATTACK-MOVE. RA2's AttackMove advances on a spot and stops to kill what
  // it meets, then carries on — the difference between a column that walks
  // past a Tesla Coil and one that levels it.
  if (u.order && u.order.t === 'amove') {
    var am = findTarget(g, u, reachOf(d, u));
    if (am) {
      var amd = dist(u, am), amw = weaponFor(d, am, u);
      var ame = edgeDist(u, am);
      if (ame <= rngVs(amw, am) && !tooClose(amw, ame)) {
        u.path = null;
        var aax = (am.kind === 'b' ? am.cx : am.x) - u.x, aay = (am.kind === 'b' ? am.cy : am.y) - u.y;
        var aaf = faceOf(aay, aax), amRot = rotOf(u.type);
        var amB = d.turret ? (u.aimAt = g.tick, aimTurret(u, aaf, amRot)) : aimHull(u, aaf, amRot);
        if (u.cool <= 0 && amB) fire(g, u, am);
        return;                                  // hold and fight
      }
      // Close the last few cells rather than walking past out of range.
      if (amd < reachOf(d, u) + 3) {
        advance(g, u, Math.round(am.kind === 'b' ? am.cx : am.x),
                      Math.round(am.kind === 'b' ? am.cy : am.y), uspd(u), 45);
        return;
      }
    }
    var amdx = u.order.x - u.x, amdy = u.order.y - u.y;
    if (amdx * amdx + amdy * amdy < (u.air ? 0.3 : 1.4)) {
      u.order = null; u.path = null; u.guard = true; u.guardX = u.x; u.guardY = u.y;
      nextWaypoint(g, u);
    } else if (!advance(g, u, u.order.x, u.order.y, uspd(u), 0) && !u.path && u.noProg > 90) {
      u.order = null; u.guardX = u.x; u.guardY = u.y;
    }
    return;
  }

  // FORCE-FIRE at a spot: close to range, then keep shelling it.
  if (u.order && u.order.t === 'ffire') {
    var fdx = u.order.x - u.x, fdy = u.order.y - u.y;
    var fd = Math.sqrt(fdx * fdx + fdy * fdy);
    var fspec = (u.deployed && d.dep) ? d.dep : d;
    if (fd <= fspec.rng && !tooClose(fspec, fd)) {
      u.path = null;
      var ff = faceOf(fdy, fdx), ffRot = rotOf(u.type);
      var ffB = d.turret ? (u.aimAt = g.tick, aimTurret(u, ff, ffRot)) : aimHull(u, ff, ffRot);
      if (u.cool <= 0 && ffB) fireGround(g, u, u.order.x, u.order.y);
      return;
    }
    if (!advance(g, u, u.order.x, u.order.y, uspd(u), 60) && u.noProg > 90) {
      u.order = null; u.noProg = 0;
    }
    return;
  }

  // FOLLOW (F): shadow a friendly unit, shooting anything that comes into
  // reach on the way. RA2's GuardModeStray is the leash length.
  if (u.order && u.order.t === 'follow') {
    var fo = entById(g, u.order.id);
    if (!fo || fo === u) { u.order = null; return; }
    if (d.dmg > 0 && u.cool <= 0) {
      var fpass = findTarget(g, u, reachOf(d, u));
      if (fpass) fire(g, u, fpass);
    }
    u.guardX = fo.kind === 'b' ? fo.cx : fo.x; u.guardY = fo.kind === 'b' ? fo.cy : fo.y;
    if (dist(u, fo) > GUARD_STRAY) advance(g, u, Math.round(u.guardX), Math.round(u.guardY), uspd(u), 30);
    else u.path = null;
    return;
  }

  if (u.order && u.order.t === 'move') {
    if (d.dmg > 0 && u.cool <= 0) {
      var passing = findTarget(g, u, reachOf(d, u));
      if (passing) fire(g, u, passing);
    }
    // fire() can end the order under us — a Terror Drone that burrows into
    // its victim, an Ivan that plants and dies, a Chrono Legionnaire that
    // erases the thing it was walking past. Reading u.order.x after it has
    // been nulled crashed the whole match (soak, 3 of 96 runs).
    if (!u.order || u.order.t !== 'move') return;
    var mdx = u.order.x - u.x, mdy = u.order.y - u.y;
    if (mdx * mdx + mdy * mdy < (u.air ? 0.3 : 1.4)) {  // arrived (a flyer lands its spot exactly)
      u.order = null; u.path = null; u.guardX = u.x; u.guardY = u.y;
      nextWaypoint(g, u);
    } else if (!advance(g, u, u.order.x, u.order.y, uspd(u), 0) && !u.path &&
               u.noProg > 90) {
      // Path ran out short and a fresh one changed nothing: unreachable.
      u.order = null; u.guardX = u.x; u.guardY = u.y;
    }
    return;
  }

  // An attack order says where to GO, not what to ignore on the way. The
  // ordered target is engaged when it is in range; anything else in range
  // is engaged too. Letting the order win outright marched whole waves
  // past live gun turrets without a shot fired.
  var tgt = null, ordered = null;
  if (u.order && u.order.t === 'attack') {
    ordered = entById(g, u.order.id);
    if (!ordered || !canHit(d, ordered, u)) { u.order = null; ordered = null; }
    else if (edgeDist(u, ordered) <= rngVs(weaponFor(d, ordered, u), ordered)
             && !tooClose(weaponFor(d, ordered, u), edgeDist(u, ordered))) tgt = ordered;
  }
  // A PLAYER's attack order is RA2's: the target it names is the only thing
  // this unit shoots at until it is dead. Nothing on the way is engaged and
  // nothing already in range holds it back — before this, a tank told to
  // hit a far building parked on the nearest conscript instead, and a new
  // order changed nothing while the old target stayed in range ("can't
  // fully control the attack target", 2026-09-11). The loose rule above
  // stays for the AI's own waves, which set their orders directly.
  var focus = !!(ordered && u.order.focus);
  // [RepairBullet]: an IFV with an Engineer aboard has no gun, it has a
  // welding arm, and it uses it on the vehicles around it.
  if (d.ifv && ifvSpec(u).repair) { stepRepairIFV(g, u); if (!u.order) return; }
  // ThreatPosed=0 / CanPassiveAquire=no on [SHAD]: a transport never picks
  // its own fight, it shoots only what it was told to.
  if (!tgt && !d.passive && !focus) tgt = findTarget(g, u, reachOf(d, u));
  // AI-driven GIs deploy when something is in sandbag range and pack up
  // after five quiet seconds; a human deploys with D, as in RA2.
  if (d.dep && isAiSide(g, u.p)) {
    if (tgt) u.tgtAt = g.tick;
    if (!u.deployed && !(u.order && u.order.t !== 'attack') && (tgt || findTarget(g, u, d.dep.rng))) u.deployed = true;
    else if (u.deployed && !tgt && g.tick - (u.tgtAt || 0) > 300) u.deployed = false;
  }
  // A DeployFire unit braces ITSELF, on both sides. rules.ini's [GGI] carries
  // a commented-out DeployTime whose note says the explicit state machine was
  // dropped "b/c of autodeploy" — so RA2 does this for the player too, and it
  // has to: a Guardian GI that only fires its missile after the player
  // notices a tank and presses D is a unit nobody would use.
  //
  // It CANNOT go through findTarget. That filters every candidate by the
  // weapon the unit has right now, which while packed is the 4-cell rifle —
  // so a tank at 6 cells is invisible, and a Guardian who cannot see it never
  // braces and therefore never sees it. `depFireTarget` scans on the MISSILE'S
  // range for the armour and aircraft the missile is for, and nothing else.
  if (d.depFire && d.w2) {
    var av = depFireTarget(g, u, d.w2.rng);
    if (av) u.tgtAt = g.tick;
    if (!u.deployed && av && !(u.order && u.order.t === 'move')) u.deployed = true;
    else if (u.deployed && !av && g.tick - (u.tgtAt || 0) > 180) u.deployed = false;
    if (u.deployed && !tgt && !focus) tgt = av;        // braced: the missile can reach it now
  }

  if (tgt) {
    var dd = dist(u, tgt);
    // The AI's tanks drive THROUGH infantry, as RA2's do: a prone Conscript
    // shrugs off shells (ProneDamage 50%) but not 30 tons of Grizzly. Human
    // tanks keep RA2's stop-and-shoot unless force-moved.
    if (isAiSide(g, u.p) && tgt.kind === 'u' && crusher(u) && crushable(tgt) && dd > 0.8) {
      if (edgeDist(u, tgt) <= rngVs(weaponFor(d, tgt, u), tgt) && u.cool <= 0) fire(g, u, tgt);
      advance(g, u, Math.round(tgt.x), Math.round(tgt.y), uspd(u), 30);
      return;
    }
    var dde = edgeDist(u, tgt);                       // to the wall, not the centre
    if (dde <= rngVs(weaponFor(d, tgt, u), tgt) && !tooClose(weaponFor(d, tgt, u), dde)) {
      u.path = null;
      var ax = (tgt.kind === 'b' ? tgt.cx : tgt.x) - u.x;
      var ay = (tgt.kind === 'b' ? tgt.cy : tgt.y) - u.y;
      var af = faceOf(ay, ax), afRot = rotOf(u.type), bears = true;
      // A Kirov does not pivot to face what is directly beneath it.
      if (d.turret) { u.aimAt = g.tick; bears = aimTurret(u, af, afRot); }
      else if (!(d.bomb && dd < 0.6)) bears = aimHull(u, af, afRot);
      if (u.cool <= 0 && bears) fire(g, u, tgt);
      return;
    }
    // Chase only what we were told to chase, or what is close to our post.
    // RA2 separates Stop from Guard (`[General] GuardModeStray=2.0`): a
    // STOPPED unit holds its ground and only fires at what walks into
    // range, while a GUARDING unit leaves its post by up to two cells to
    // engage and then walks back. Everything else keeps the old loose
    // leash so freshly built and idle troops still defend themselves.
    var postD = Math.sqrt((u.guardX - u.x) * (u.guardX - u.x) + (u.guardY - u.y) * (u.guardY - u.y));
    var chase = (ordered && tgt === ordered) ||
                (u.stopped ? false
                 : u.guard ? postD < reachOf(d, u) + GUARD_STRAY
                 : postD < 7);
    if (chase) {
      advance(g, u, Math.round(tgt.kind === 'b' ? tgt.cx : tgt.x),
                    Math.round(tgt.kind === 'b' ? tgt.cy : tgt.y), uspd(u), 45);
      return;
    }
  }

  if (u.order && u.order.t === 'attack' && ordered) {
    if (!advance(g, u, Math.round(ordered.kind === 'b' ? ordered.cx : ordered.x),
                       Math.round(ordered.kind === 'b' ? ordered.cy : ordered.y), uspd(u), 60) &&
        u.noProg > 90) {
      // No route to the thing we were told to kill. Holding the order here
      // is not patience, it is paralysis — the unit stands still for the
      // rest of the match while its side wonders why the attack never
      // landed. Measured: 33 of one side's infantry frozen inside its own
      // base behind its own buildings, and the match a 16-minute stalemate
      // because of it. Drop the order; findTarget() still lets it shoot
      // whatever it can reach, and the AI hands it a new one next pass.
      u.order = null; u.noProg = 0;
    }
    return;
  }

  // GUARD, the half Stop does not have: a guarding unit watches a whole
  // area, not just what its gun can already reach, and steps out to meet
  // anything inside `GuardModeStray` of its post. findTarget() only ever
  // returns what is ALREADY in weapon range, so the reaching-out pass has
  // to be its own.
  if (!tgt && u.guard && !u.order && !u.air && d.dmg > 0) {
    var away = nearestFoe(g, u, reachOf(d, u) + GUARD_STRAY);
    if (away) {
      advance(g, u, Math.round(away.kind === 'b' ? away.cx : away.x),
                    Math.round(away.kind === 'b' ? away.cy : away.y), uspd(u), 45);
      return;
    }
  }

  // A guard that chased something comes home; a stopped unit never left.
  if (!tgt && u.guard && !u.order && !u.air) {
    var gdx = u.guardX - u.x, gdy = u.guardY - u.y;
    if (gdx * gdx + gdy * gdy > 1.4) { advance(g, u, Math.round(u.guardX), Math.round(u.guardY), uspd(u), 90); return; }
    u.path = null;
  }

  if (u.air) hoverIdle(g, u);          // nothing to do up there: hold a circle
}

// The nearest thing this unit could shoot within `r`, whether or not its
// gun reaches that far yet — Guard's "something is coming" sense.
function nearestFoe(g, u, r) {
  var spec = UNITS[u.type], best = null, bd = 1e9;
  near(u.x, u.y, r + 1, function (o) {
    if (o.dead || o.p === u.p || !canHit(spec, o, u)) return;
    var dd = dist(u, o);
    if (dd > r || dd >= bd) return;
    bd = dd; best = o;
  });
  return best;
}

export function entById(g, id) {
  var e = g.byId[id];
  return e && !e.dead ? e : null;
}

// Pad-based aircraft (RA2 Harrier). It lives on one of the four pads of an
// Airforce Command, flies out with `ammo` missiles, fires them all at the
// ordered target, returns to the pad, reloads, and goes again while the
// target still stands. With no order it sits on the pad (or hovers where a
// move order left it); it never auto-acquires — RA2 aircraft do not either.
export function findPad(g, u) {
  var used = {};
  for (var i = 0; i < g.units.length; i++) {
    var o = g.units[i];
    if (!o.dead && o !== u && o.p === u.p && o.pad) used[o.pad + ':' + o.slot] = 1;
  }
  var best = null, bd = 1e9;
  for (var j = 0; j < g.blds.length; j++) {
    var b = g.blds[j];
    if (b.dead || b.p !== u.p || b.type !== 'airforce') continue;
    for (var k = 0; k < PAD_SLOTS.length; k++) {
      if (used[b.id + ':' + k]) continue;
      var dd = dist(u, b);
      if (dd < bd) { bd = dd; best = { b: b, slot: k }; }
      break;
    }
  }
  return best;
}

export function padCapacity(g, p) { return PAD_SLOTS.length * countBld(g, p, 'airforce'); }

// RA2 Harriers descend onto the pad and climb off it; ours snapped between
// cruise altitude and zero on the tick `landed` flipped. The transition is
// caught here and `altOf` ramps the height over LAND_T either way.
export var LAND_T = 34;

function stepAircraft(g, u) {
  var wasLanded = !!u.landed;
  stepAircraft0(g, u);
  if (wasLanded && !u.landed) u.flyAt = g.tick;
  else if (!wasLanded && u.landed) u.landAt = g.tick;
}

function stepAircraft0(g, u) {
  var d = UNITS[u.type];
  var pad = u.pad ? entById(g, u.pad) : null;
  if (pad && pad.p !== u.p) pad = null;
  if (!pad) {
    u.pad = 0; u.landed = false;
    var fp = findPad(g, u);
    if (fp) { u.pad = fp.b.id; u.slot = fp.slot; pad = fp.b; }
  }

  if (u.order && u.order.t === 'move') {
    u.landed = false; u.rtb = false;
    var mdx = u.order.x - u.x, mdy = u.order.y - u.y;
    if (mdx * mdx + mdy * mdy < 0.3) { u.order = null; u.guardX = u.x; u.guardY = u.y; nextWaypoint(g, u); }
    else flyToward(g, u, u.order.x, u.order.y, uspd(u));
    return;
  }
  if (u.order && u.order.t === 'attack') {
    var t = entById(g, u.order.id);
    if (!t || !canHit(d, t, u)) { u.order = null; if (!u.landed) u.rtb = true; }
    else if (!u.landed && !u.rtb && u.ammo > 0) {
      var dd = dist(u, t);
      if (dd <= d.rng) {
        var ax = (t.kind === 'b' ? t.cx : t.x) - u.x, ay = (t.kind === 'b' ? t.cy : t.y) - u.y;
        slew(u, 'face', 'fsub', faceOf(ay, ax), rotOf(u.type));
        if (u.cool <= 0) fire(g, u, t);
      } else flyToward(g, u, t.kind === 'b' ? t.cx : t.x, t.kind === 'b' ? t.cy : t.y, uspd(u));
      return;
    } else if (!u.landed) u.rtb = true;            // out of missiles: home to reload, order kept
  }

  if (u.rtb) {
    if (!pad) { u.rtb = false; return; }           // nowhere to land: hover here
    var sl = padSlot(pad, u.slot);
    u.landed = false;
    if (!flyToward(g, u, sl.x, sl.y, uspd(u))) {
      u.x = sl.x; u.y = sl.y; u.landed = true; u.rtb = false; u.face = 0; u.fsub = 0;
      u.guardX = u.x; u.guardY = u.y;
    }
    return;
  }
  if (u.landed) {
    // On the pad: rearm one missile per `reload` ticks, patch the airframe.
    if (u.ammo < d.ammo && (g.tick % d.reload) === 0) u.ammo++;
    if (u.hp < u.maxhp && (g.tick % 30) === 0) u.hp = Math.min(u.maxhp, u.hp + u.maxhp * 0.02);
    if (u.ammo >= d.ammo && u.order && u.order.t === 'attack') u.landed = false;   // sortie again
    return;
  }
  // Hovering with nothing to do and no ammo: go home. With missiles left it
  // circles on station.
  if (u.ammo <= 0 && pad) u.rtb = true;
  else hoverIdle(g, u);
}

// art.ini `IsAnimDelayedFire=yes` / `DelayedFireDelay=28` on [NATSLA] and
// [GAPRIS]: both towers visibly wind up for 28 FRAMES before the shot, which
// at RA2's 15 fps (rules.ini:693) is 1.9 seconds — 112 ticks here. Held at
// the raw 28 the wind-up was under half a second and the Tesla Coil's bolt
// effectively arrived with no warning at all, which is the whole point of
// DelayedFireDelay.
export var CHARGE_T = 112;

// rules.ini [General] PrismSupportModifier=150%, PrismSupportMax=8, and TWO
// separate keys that were being conflated:
//   PrismSupportDelay=60      how long supporting takes a tower OFFLINE
//   PrismSupportDuration=15   how long the support BEAM is visible
// The offline period was being computed from the beam's visibility (15 * 2 =
// 30 ticks), so a supporter recovered and supported again 29 ticks later and
// a cluster of towers never actually paid for the bonus. 60 frames at 15 fps
// is four seconds — 240 ticks.
export var PRISM_SUP_MAX = 8, PRISM_SUP_MOD = 1.5, PRISM_SUP_DUR = 15, PRISM_SUP_DELAY = 240;

export function prismSupport(g, b) {
  var n = 0;
  for (var i = 0; i < g.blds.length && n < PRISM_SUP_MAX; i++) {
    var o = g.blds[i];
    if (o === b || o.dead || o.p !== b.p || o.type !== 'prism') continue;
    if (o.charging > 0 || o.cool > 0 || o.make > 0) continue;
    var dx = o.cx - b.cx, dy = o.cy - b.cy, rr = BLDS.prism.rng;
    if (dx * dx + dy * dy > rr * rr) continue;
    n++;
    o.cool = Math.max(o.cool, PRISM_SUP_DELAY);        // [General] PrismSupportDelay=60 frames
    o.supAt = g.tick;
    // The BEAM's own life is PrismSupportDuration=15 frames = 60 ticks.
    if (!headless) g.shots.push({ x: o.cx, y: o.cy, tx: b.cx, ty: b.cy, t: 0, life: PRISM_SUP_DUR * 4, link: true, id: g.nextId++ });
  }
  b.sup = n;
}

// [GAGATE_A] DeployTime=.044 (~2.6s of leaf travel) and GateCloseDelay=.2.
// Both are scaled to something a player can walk a column through: 18 ticks
// of swing, three quarters of a second of hold once the last friendly is
// clear.
export var GATE_T = 18, GATE_HOLD = 45;

export function stepGate(g, b) {
  var want = false;
  for (var i = 0; i < g.units.length; i++) {
    var u = g.units[i];
    if (u.dead || u.p !== b.p || u.air) continue;
    if (Math.abs(u.x - b.cx) <= 1.9 && Math.abs(u.y - b.cy) <= 1.9) { want = true; break; }
  }
  if (want) b.gateT = g.tick;
  var hold = want || (g.tick - (b.gateT || -1e9) < GATE_HOLD);
  // Never shut on top of somebody: RA2's leaves stop rather than crush.
  if (!hold && b.gate >= GATE_T) {
    for (i = 0; i < g.units.length; i++) {
      var v = g.units[i];
      if (!v.dead && !v.air && Math.round(v.x) === Math.round(b.cx) && Math.round(v.y) === Math.round(b.cy)) { hold = true; break; }
    }
  }
  b.gate = Math.max(0, Math.min(GATE_T, (b.gate || 0) + (hold ? 1 : -1)));
}
