// Iron Frontier — net.js
// GENERATED by apps/games/rts/tools/modularize from rts.src.html + art/units/**.

import { stepAI } from './ai.js';
import { BLDS } from './blds.js';
import { bspecOf, bspecOfB, isHarv } from './combat-tables.js';
import { HASH_UNSET, entX, entY, hash, hashAt, near, rebuildHash, setHash, setHashAt, stateHash, stepSuper, stepWrecks, swFire } from './combat.js';
import { deployMcv, killBld, placeBld, recalcPower, spawnUnit, stepRubble } from './entities.js';
import { isAir, moverOf } from './geom.js';
import { LAND_T, stepUnit, tilePassable } from './move.js';
import { ORE_GROW_T, ORE_SPREAD_T, canOccupy, ejectGarrison, hash3, stepBld, stepCrates, stepDrops, stepOreSpread } from './neutral.js';
import { sendHome } from './ore.js';
import { blocked, pathQ, requestPath, runPathQueue, setPathQ } from './path.js';
import { QUEUE_MAX, canBuild, canPlace, cancelLast, countUnit, enqueue, freeTileNear, isBldLane, laneOfBld, stepQueues } from './production.js';
import { _seed, set_seed } from './rng.js';
import { UNITS } from './roster.js';
import { applyGaps, revealFor } from './shroud.js';
import { describeShort, stepBombs, stepErase, stepInfest, stepRad } from './special.js';
import { headless, setG, setState } from './state.js';
import { SW } from './supers.js';
import { canBoard, paxCapOf, paxCount, unloadTransport } from './transport.js';
import { eva, sfx, unitAck } from './ui/audio.js';
import { refreshSW, say } from './ui/hud.js';
import { attackMission, clearSel, describe, makeRally, orderAmove, orderAttack, orderFFire, orderFollow, orderUnitsTo, refreshCmdbar, sellBld } from './ui/input.js';
import { sel, setSel } from './ui/screen.js';
import { economyDead, stepEvaWatch } from './watch.js';
import { GUARD_STRAY, MAP, ME, P_AI, P_HUMAN, neutral, oreT, setSeat } from './world.js';

// --------------------------------------------------------------------- //
//  Lockstep command layer
//
//  RA2's netcode is LOCKSTEP: every client runs the same deterministic
//  simulation from the same seed and the wire carries only COMMANDS —
//  "these unit ids move to that cell" — applied on an agreed FUTURE tick,
//  so every machine mutates its world at the identical moment. Nothing but
//  the command stream ever crosses the network; state never does.
//
//  The rules this layer enforces, and why each one matters:
//    1. `applyCmd` is the ONLY thing that mutates the sim on a player's
//       behalf. An input handler resolves what the click MEANT (which is
//       full of local-only knowledge: the selection, the cursor, the
//       camera) and then emits a serialisable command. It never touches
//       `G` itself. A single mutator is what makes two clients agree.
//    2. A command issued on tick T runs on tick T + LOCKSTEP_DELAY on
//       EVERY client, local one included. Uniform delay is the point: a
//       local shortcut would make the issuing client run one tick ahead of
//       its peers for that order and desync immediately.
//    3. The due queue is applied in a canonical order — by player id, then
//       by that player's issue sequence — because JS object key order and
//       packet arrival order are not the same everywhere.
//    4. The AI is NOT a network player. It is part of the simulation: it
//       runs inside `simStep` on every client from the same seed and
//       therefore reaches the same decisions without sending anything.
//
//  A REAL SERVER plugs in at the `Transport` seam below. It has to do
//  exactly three things and nothing else:
//     (a) agree the match seed, map, options, faction and player ids
//         BEFORE tick 0, and hand every client the identical record;
//     (b) relay command bundles — it may reorder them in flight, since
//         each bundle is stamped with its due tick and its issuer, but it
//         must never drop one;
//     (c) hold the tick barrier: a client may not step tick T until it
//         holds a bundle (empty counts) from every player for T. That is
//         `Transport.ready(tick)`, and it is the whole of flow control —
//         the slowest player sets the pace, exactly as RA2 does.
//  It does no simulation and stores no game state, so it cannot be the
//  thing that gets the answer wrong.
// --------------------------------------------------------------------- //
// Ticks between issuing an order and running it. Single player keeps the
// two it has always had. A two-player match raises it, because the delay is
// also the PIPELINE: with delay D a client may run D-1 ticks past the last
// bundle it holds, so D=2 forces a full round trip every single tick and any
// jitter on the wire shows up as a stutter. RA2 grows the delay for the same
// reason (and shrinks it again on a fast link, which is still a ☐ here).
export var SP_DELAY = 2, MP_DELAY = 4;

export var LOCKSTEP_DELAY = SP_DELAY;   // ticks between issuing an order and running it

var DESYNC_EVERY = 60;           // ticks between state-hash comparisons

export var NET = { active: null };

// The module-level derived caches (`_seed`, the spatial hash, the path
// queue) belong to whichever game is stepping. One page running two
// clients has to SWAP them, or client B reads client A's neighbour buckets
// and the two worlds drift apart in the first minute — the same failure the
// per-match `resetHash()` fixed for back-to-back matches.
export function netStash() {
  var c = NET.active;
  if (c) c.ctx = { seed: _seed, hash: hash, hashAt: hashAt, pathQ: pathQ };
}

export function netLoad(c) {
  set_seed(c.ctx.seed); setHash(c.ctx.hash); setHashAt(c.ctx.hashAt); setPathQ(c.ctx.pathQ);
  setG(c.g); NET.active = c; setSeat(c.p);
}

export function netUse(c) {
  if (NET.active === c) { setG(c.g); setSeat(c.p); return; }
  netStash(); netLoad(c);
}

function NetClient(g, pid, tr, nplayers) {
  this.g = g; this.p = pid | 0; this.tr = tr;
  this.n = nplayers || 1;
  this.q = {};                   // due tick -> [cmd]
  this.pend = [];                // emitted this tick, not yet sent
  this.seq = 0;
  this.sent = -1;                // highest tick a bundle has been sent for
  this.hashes = {};              // tick -> our own state hash
  this.check = this.n > 1;       // only a networked match needs desync checks
  this.desync = null;
  // Fresh derived caches: two clients must never share a spatial hash.
  this.ctx = { seed: _seed, hash: {}, hashAt: HASH_UNSET, pathQ: [] };
}

// A bundle is one player's commands for one tick — empty bundles are sent
// too, because "nothing happened on tick T" is exactly the information the
// barrier needs.
// The tick the NEXT bundle covers: LOCKSTEP_DELAY ticks after the one the
// client is sitting on. One number, used both to stamp commands and to
// address bundles, so the barrier's ledger and the schedule can never
// disagree about which tick an order belongs to.
NetClient.prototype.due = function () { return this.g.tick + LOCKSTEP_DELAY; };

NetClient.prototype.flush = function () {
  var at = this.due(), i;
  for (i = 0; i < this.pend.length; i++) if (this.pend[i].at < at) this.pend[i].at = at;
  var b = { p: this.p, at: at, cmds: this.pend };
  this.pend = [];
  this.sent = at;
  this.tr.send(b);
};

NetClient.prototype.recv = function (b) {
  if (b.hash !== undefined) { this.onPeerHash(b); return; }
  for (var i = 0; i < b.cmds.length; i++) {
    var t = b.cmds[i].at;
    (this.q[t] || (this.q[t] = [])).push(b.cmds[i]);
  }
};

NetClient.prototype.onPeerHash = function (b) {
  if (this.desync) return;
  var mine = this.hashes[b.at];
  if (mine === undefined) { (this.peerHash || (this.peerHash = {}))[b.at] = b; return; }
  if (mine !== b.hash) this.fail(b.at, mine, b.hash, b.p);
};

NetClient.prototype.fail = function (t, mine, theirs, who) {
  this.desync = { tick: t, mine: mine, theirs: theirs, peer: who };
  netOnDesync(this, this.desync);
};

// Ordered application: player id first, then that player's own sequence.
// Two clients that receive the same commands in different orders still run
// them in the same order.
function cmdOrder(a, b) { return a.p !== b.p ? a.p - b.p : a.seq - b.seq; }

function netApplyDue(g) {
  var c = NET.active;
  if (!c || c.g !== g) return;
  var list = c.q[g.tick];
  if (!list) return;
  delete c.q[g.tick];
  list.sort(cmdOrder);
  for (var i = 0; i < list.length; i++) applyCmd(g, list[i].p, list[i]);
}

// End-of-tick checkpoint. Single player has no peer to disagree with, so
// the hash is not even computed.
function netTick(g) {
  var c = NET.active;
  if (!c || c.g !== g || !c.check || c.desync) return;
  if (g.tick % DESYNC_EVERY) return;
  var h = stateHash(g);
  c.hashes[g.tick] = h;
  // Broadcast BEFORE comparing. A client that finds the mismatch first stops
  // stepping, so if it compared first and returned it would carry the only
  // copy of its own fingerprint out of the match with it — the peer would
  // never learn, and would sit at a barrier that never opens, with no
  // explanation. Measured in two real tabs: only the tab that noticed
  // stopped, the other played on into a stall.
  c.tr.send({ p: c.p, at: g.tick, hash: h });
  var pend = c.peerHash && c.peerHash[g.tick];
  if (pend) { delete c.peerHash[g.tick]; if (pend.hash !== h) c.fail(g.tick, h, pend.hash, pend.p); }
}

// A desync is not a defeat and must not run the score screen: the match
// simply stops where it is (netMayStep refuses to step a desynced client)
// and says which tick the two worlds stopped agreeing on, with both
// fingerprints, because that pair is the whole of the bug report.
var netOnDesync = function (c, d) {
  if (headless || !c.g) return;
  setState('paused');
  say('Desynchronised at tick ' + d.tick + ' — this client ' + d.mine +
      ', player ' + d.peer + ' ' + d.theirs + '. The match has stopped.', true, 900);
};

// The one place a player action turns into a mutation.
function netEmit(c) {
  var n = NET.active;
  if (!n || !n.g || n.desync) return false;
  c.p = n.p; c.seq = n.seq++; c.at = n.due();
  n.pend.push(c);
  // A LocalNet has no barrier and no wire, so the bundle can go straight
  // out; a networked client batches until its tick boundary.
  if (n.tr.immediate) n.flush();
  return true;
}

export function cmd(type, payload) {
  var c = payload || {};
  c.t = type;
  return netEmit(c);
}

function cmdLocal(c) { return !headless && NET.active && c.p === NET.active.p; }

// ---- transports --------------------------------------------------------
// LocalNet: single player. The "network" is a function call, the barrier is
// always open, and a command is in the schedule the moment it is issued.
function LocalNet() { this.immediate = true; this.peers = []; }

LocalNet.prototype.join = function (c) { this.peers.push(c); };

LocalNet.prototype.send = function (b) { for (var i = 0; i < this.peers.length; i++) this.peers[i].recv(b); };

LocalNet.prototype.ready = function () { return true; };

LocalNet.prototype.onCmd = function (fn) { this.sink = fn; };

// LoopbackNet: two (or more) clients in ONE page, each with its own `G`,
// trading bundles across a bus with a settable per-client latency. No
// sockets, no server — but every rule a real transport has to obey is
// exercised: bundles arrive late, out of order relative to the other
// player's, and the barrier is what keeps the two worlds on the same tick.
export function LoopBus() { this.links = []; this.wire = []; this.clock = 0; }

LoopBus.prototype.link = function (lat) {
  var L = new LoopbackNet(this, lat | 0);
  this.links.push(L);
  return L;
};

LoopBus.prototype.post = function (from, b) {
  var at = this.clock + (from.lat || 0);
  for (var i = 0; i < this.links.length; i++) {
    var to = this.links[i];
    if (to === from) { to.deliver(b); continue; }   // your own orders never travel
    // A real wire SERIALISES. Copying here is not politeness: it keeps the
    // two clients from sharing command objects (a mutation on one would
    // otherwise silently appear on the other, which is exactly the bug a
    // desync test must be able to stage) and it asserts, every single
    // bundle, that a command is plain JSON with no live references in it.
    this.wire.push({ at: at, to: to, b: JSON.parse(JSON.stringify(b)) });
  }
};

// One bus beat: everything whose latency has expired lands.
LoopBus.prototype.pump = function () {
  this.clock++;
  var keep = [], i;
  for (i = 0; i < this.wire.length; i++) {
    if (this.wire[i].at <= this.clock) this.wire[i].to.deliver(this.wire[i].b);
    else keep.push(this.wire[i]);
  }
  this.wire = keep;
};

LoopBus.prototype.drain = function () { while (this.wire.length) this.pump(); };

// Everything an ASYNCHRONOUS transport has in common, whatever the wire
// underneath is: a ledger of which player's bundle for which tick has
// landed, and the barrier that reads it. Only `send` differs between the
// in-page bus and a BroadcastChannel between two tabs.
function barrierNet(P) {
  P.join = function (c) {
    this.client = c;
    var q = this.pre; this.pre = null;
    if (q) for (var i = 0; i < q.length; i++) c.recv(q[i]);
  };
  P.onCmd = function (fn) { this.sink = fn; };
  P.deliver = function (b) {
    // A hash beacon is a checkpoint, not a bundle: it must never satisfy
    // the barrier, or a client could step a tick nobody has spoken for.
    if (b.hash === undefined) this.have[b.p + '@' + b.at] = 1;
    // Rule (b) is "never drop one", and a bundle can outrun the client that
    // is still being built. Counting it into the ledger and then discarding
    // its commands would be the worst of both: the barrier opens and the
    // orders are gone.
    if (this.client) this.client.recv(b);
    else (this.pre || (this.pre = [])).push(b);
  };
  // The barrier: tick T may not run until every player's bundle for T is in.
  // Ticks before the first scheduled one are free — nobody could have sent a
  // bundle for them.
  P.ready = function (t) {
    if (t < LOCKSTEP_DELAY) return true;     // nobody could have addressed these
    var n = this.client ? this.client.n : 1, p;
    for (p = 0; p < n; p++) if (!this.have[p + '@' + t]) return false;
    // A ledger that only grows is a leak in a long match; a tick already
    // behind the barrier can never be asked about again.
    for (p = 0; p < n; p++) delete this.have[p + '@' + (t - 8)];
    return true;
  };
}

function LoopbackNet(bus, lat) {
  this.immediate = false; this.bus = bus; this.lat = lat | 0;
  this.client = null; this.have = {};   // "p@tick" -> true, the barrier's ledger
}

barrierNet(LoopbackNet.prototype);

LoopbackNet.prototype.send = function (b) { this.bus.post(this, b); };

// ---- BcNet: a real wire between two TABS -------------------------------
// The first transport in this file that is not a function call. A
// `BroadcastChannel` carries bundles between two browsing contexts on one
// machine: delivery is a separate task, so a bundle posted during frame N
// is not readable until frame N+1, exactly like a socket and unlike
// LoopbackNet. That is the whole point — the barrier, the due-tick stamp
// and the canonical apply order all have to be right or the two tabs drift
// apart within seconds, and here they are proved against a wire that
// genuinely delays.
//
// It obeys the three rules the seam names and does nothing else: the LOBBY
// (below) agrees the match record before tick 0, `send`/`onWire` relay
// bundles without dropping any, and `ready` holds the tick barrier. It
// simulates nothing and holds no game state — `have` is a set of tick
// numbers.
//
// `port` is anything with `post(msg)`; the page hands it a BroadcastChannel
// and the tests hand it a scriptable pair, which is what lets an
// arrival-order hazard be staged deterministically.
export function BcNet(port, n) {
  this.immediate = false;
  this.port = port; this.n = n | 0;
  this.client = null; this.have = {};
}

barrierNet(BcNet.prototype);

BcNet.prototype.send = function (b) {
  // A BroadcastChannel never echoes to its own sender, and a client must
  // still satisfy its own half of the barrier: post to the wire AND to
  // ourselves, exactly as LoopBus does for the link that sent.
  this.deliver(b);
  this.port.post({ k: 'b', b: b });
};

// Anything that is not a bundle belongs to the lobby, which shares the
// channel; the transport ignores it rather than guessing.
BcNet.prototype.onWire = function (m) {
  if (!m || m.k !== 'b' || !m.b) return false;
  this.deliver(m.b);
  return true;
};

// A scriptable stand-in for a BroadcastChannel GROUP: `post` queues, `pump`
// delivers whatever has come due. The page hands `BcNet` a real channel; a
// test hands it one of these, so an arrival-order or latency hazard can be
// staged deterministically against the very same transport code the two
// tabs run.
export function BcBus(lats) { this.nets = []; this.wire = []; this.clock = 0; this.lats = lats || []; }

BcBus.prototype.link = function (n) {
  var bus = this, i = this.nets.length;
  this.nets.push(null);
  var net = new BcNet({ post: function (m) { bus.post(i, m); } }, n);
  this.nets[i] = net;
  return net;
};

BcBus.prototype.post = function (from, m) {
  var at = this.clock + (this.lats[from] || 0);
  for (var i = 0; i < this.nets.length; i++) {
    if (i === from) continue;                  // a BroadcastChannel never echoes to its sender
    // Serialising here is the same assertion LoopBus makes: a lobby message
    // or a bundle must be plain JSON with no live references in it.
    this.wire.push({ at: at, to: i, m: JSON.parse(JSON.stringify(m)) });
  }
};

BcBus.prototype.pump = function () {
  this.clock++;
  var keep = [], i;
  for (i = 0; i < this.wire.length; i++) {
    if (this.wire[i].at <= this.clock) this.nets[this.wire[i].to].onWire(this.wire[i].m);
    else keep.push(this.wire[i]);
  }
  this.wire = keep;
};

BcBus.prototype.drain = function () { while (this.wire.length) this.pump(); };

// Attach a fresh single-player client to a new game. Called at the end of
// `newState`, so every entry point — the menu, the test hooks, the balance
// harness — starts with an empty schedule and its own derived caches.
export function netAttach(g, tr, pid, nplayers) {
  var t = tr || new LocalNet();
  var c = new NetClient(g, pid || 0, t, nplayers);
  if (t.join) t.join(c);
  c.ctx = { seed: _seed, hash: {}, hashAt: HASH_UNSET, pathQ: [] };
  setHash(c.ctx.hash); setPathQ(c.ctx.pathQ); setHashAt(HASH_UNSET);
  NET.active = c; c.g = g; setSeat(c.p);
  return c;
}

// Re-point the game's client at a real transport once the opening force is
// down. `netAttach` resets the derived caches, so it cannot be used here.
export function netBind(tr, pid, nplayers) {
  var c = NET.active;
  c.tr = tr; c.p = pid | 0; c.n = nplayers || 1; c.check = c.n > 1;
  setSeat(c.p);
  if (tr.join) tr.join(c);
  return c;
}

// The frame loop's gate. Single player never waits.
export function netMayStep(g) {
  var c = NET.active;
  if (!c || c.g !== g) return true;          // no client owns this game: nothing to wait for
  if (c.desync) return false;                // the worlds disagree; stepping on makes it worse
  if (c.tr.immediate) return true;
  if (c.sent < c.due()) c.flush();
  return c.tr.ready(g.tick + 1);
}

// One networked client's tick: post this tick's bundle, wait for the
// barrier, step. Returns whether it actually stepped.
export function netStep(c) {
  netUse(c);
  if (c.desync || c.g.over) return false;
  if (!c.tr.immediate && c.sent < c.due()) c.flush();
  if (!c.tr.ready(c.g.tick + 1)) return false;
  simStep(c.g);
  return true;
}

// ---- the single mutator ------------------------------------------------
function entsOf(g, ids) {
  var a = [], i, e;
  if (!ids) return a;
  for (i = 0; i < ids.length; i++) { e = g.byId[ids[i]]; if (e && !e.dead) a.push(e); }
  return a;
}

export function idsOf(list) {
  var a = [];
  for (var i = 0; i < list.length; i++) a.push(list[i].id);
  return a;
}

function entOf(g, id) { var e = g.byId[id]; return e && !e.dead ? e : null; }

// Every player-initiated change to the world passes through here, on both
// clients, on the same tick. The `local` guard is only ever about FEEDBACK —
// the mutation above it is unconditional, so a spectator's world and the
// issuing player's world take the identical change.
export function applyCmd(g, p, c) {
  var local = cmdLocal(c), us, i, n, tgt;
  switch (c.t) {

    case 'move':
      us = entsOf(g, c.u);
      n = orderUnitsTo(g, us, c.x, c.y, { queue: !!c.queue, voice: local });
      if (local && n) {
        say(c.queue ? 'Waypoint added' : (c.ore ? 'Harvesting' : 'Moving')); sfx('click');
        g.fx.push({ x: c.x, y: c.y, t: 0, life: 18, size: 0, ping: true });
      }
      return;

    case 'attack':
      us = entsOf(g, c.u); tgt = entOf(g, c.id);
      if (!tgt) return;
      n = orderAttack(g, us, tgt, !!c.force, true, !!c.queue);   // a player's order: exclusive focus
      if (!local) return;
      if (!n) { say(c.force ? 'Nothing selected can shoot that' : (isAir(tgt) ? 'Nothing selected can shoot aircraft' : 'Nothing selected can attack that'), true); sfx('no'); return; }
      var verb = c.queue ? 'Queued: ' : '';
      verb += c.force ? 'Force-firing on ' : attackMission === 'capture' ? 'Capturing ' : attackMission === 'garrison' ? 'Entering '
            : attackMission === 'infil' ? 'Infiltrating ' : 'Attacking ';
      say(verb + describe(tgt).replace(/ —.*$/, ''));
      sfx('click'); unitAck(us, attackMission === 'attack' ? 'attack' : 'move');
      return;

    case 'ffire':
      us = entsOf(g, c.u);
      n = orderFFire(g, us, c.x, c.y);
      if (!local) return;
      if (!n) { say('Nothing selected has a gun that can shell a spot', true); sfx('no'); return; }
      say('Force-firing on the ground'); sfx('click'); unitAck(us, 'attack');
      g.fx.push({ x: c.x, y: c.y, t: 0, life: 22, size: 0, ping: true });
      return;

    case 'amove':
      us = entsOf(g, c.u);
      n = orderAmove(g, us, c.x, c.y);
      if (local && n) {
        say('Attack-move — ' + n + ' unit' + (n === 1 ? '' : 's') + ' will engage what they meet');
        sfx('click'); unitAck(us, 'attack');
        g.fx.push({ x: c.x, y: c.y, t: 0, life: 22, size: 0, ping: true });
      }
      return;

    case 'follow':
      us = entsOf(g, c.u); tgt = entOf(g, c.id);
      if (!tgt) return;
      n = orderFollow(g, us, tgt);
      if (!local) return;
      if (n) { say(n + ' unit' + (n === 1 ? '' : 's') + ' following the ' + UNITS[tgt.type].name); sfx('click'); unitAck(us, 'move'); }
      else say('Nothing left to follow with', true);
      return;

    case 'enter':                                  // board one of our transports
      us = entsOf(g, c.u); tgt = entOf(g, c.id);
      if (!tgt) return;
      var room = paxCapOf(tgt) - paxCount(tgt), nin = 0;
      us.forEach(function (u) {
        if (nin >= room || !canBoard(g, tgt, u) || u === tgt) return;
        u.guard = false; u.stopped = false; u.wp = null;
        u.order = { t: 'enter', x: 0, y: 0, id: tgt.id }; u.repathAt = -999; u.path = null;
        requestPath(g, u, Math.round(tgt.x), Math.round(tgt.y)); nin++;
      });
      if (nin && UNITS[tgt.type].air) { tgt.landReq = 1; tgt.order = null; tgt.path = null; }
      if (!local) return;
      if (nin) {
        say('Boarding the ' + UNITS[tgt.type].name + ' — ' + nin + ' on the way (' +
            paxCount(tgt) + '/' + paxCapOf(tgt) + ' aboard)');
        sfx('click'); unitAck(us, 'move');
      } else if (room <= 0) { say(UNITS[tgt.type].name + ' is full — ' + paxCount(tgt) + '/' + paxCapOf(tgt), true); sfx('no'); }
      return;

    case 'own':                                    // coil / engineer patch / Ivan on our own
      us = entsOf(g, c.u); tgt = entOf(g, c.id);
      if (!tgt) return;
      var nown = 0, what = '';
      us.forEach(function (u) {
        var ud = UNITS[u.type];
        if (ud.coiler && tgt.kind === 'b' && tgt.type === 'tesla') {
          u.guard = false; u.stopped = false; u.wp = null;
          u.order = { t: 'coil', x: 0, y: 0, id: tgt.id }; u.repathAt = -999; u.path = null;
          requestPath(g, u, Math.round(tgt.cx), Math.round(tgt.cy));
          nown++; what = 'Charging the Tesla Coil';
        } else if (ud.capture && tgt.kind === 'b' && tgt.hp < tgt.maxhp && !BLDS[tgt.type].hut) {
          u.guard = false; u.stopped = false; u.wp = null;
          u.order = { t: 'capture', x: 0, y: 0, id: tgt.id }; u.repathAt = -999; u.path = null;
          requestPath(g, u, Math.round(tgt.cx), Math.round(tgt.cy));
          nown++; what = 'Engineer will repair ' + bspecOfB(g, tgt).name;
        } else if (isHarv(u) && tgt.kind === 'b' && tgt.type === 'refinery') {
          // RA2's ENTER mission on a refinery. It is a first-class order in
          // the real game, not an inference: [HARV]/[CMIN] both carry
          // `Dock=NAREFN,GAREFN` and a `VoiceEnter=` bark of their own
          // (the Chrono Miner's is a dedicated ChronoMinerReturn clip),
          // and [GAREFN]/[NAREFN] answer with `DockUnload=yes`.
          //
          // It overrides the mining cycle at ANY load — that is the whole
          // point of it. Seke's XWIS miner guide: "start sending miners
          // back manually despite not being full, 2/5 or 3/5 is fine".
          // What an EMPTY miner does is unsourced; we obey the order, which
          // is the rule everywhere else in this file (an order refused in
          // silence is indistinguishable from a bug).
          //
          // `null`ing the order is what makes it mine the NEAREST seam
          // after unloading rather than driving back to a hand-assigned
          // one — see the unload branch in stepHarvester.
          u.guard = false; u.stopped = false; u.wp = null; u.order = null;
          sendHome(g, u, tgt, true);
          nown++; what = u.cargo ? 'Returning to the refinery' : 'Heading for the refinery';
        } else if (UNITS[u.type].cls === 'v' && !u.air && tgt.kind === 'b' && tgt.type === 'depot') {
          // AIM AT A CELL THE UNIT CAN ACTUALLY REACH.
          //
          // This used to aim at round(cx),round(cy) — the pad centre, which is
          // a cell INSIDE the footprint that the pathfinder cannot enter. The
          // move's arrival test is dist < 1.183, and from outside a 3x3 the
          // nearest reachable cell centre is 2.0 away, so the order could
          // never COMPLETE: it was abandoned by the noProg branch and the
          // vehicle stopped wherever it happened to stall. MEASURED over 8
          // depots x 12 angles on a live page, that landed between 1.912 and
          // 2.145 cells out against a repair reach of gw/2 + 0.6 = 2.1 — so
          // it worked 89.9% of the time BY COINCIDENCE, on a 0.02-cell
          // margin, and the headless sweep here fails 6 of 8 approaches.
          //
          // So: pick the nearest PASSABLE cell on the ring just outside the
          // footprint and drive to that. The order can complete, and where it
          // completes is known rather than accidental.
          var dgw = tgt.gw, dgh = tgt.gh, bestC = null, bestD = 1e9;
          var rx0 = Math.round(tgt.cx), ry0 = Math.round(tgt.cy);
          var hx = Math.floor(dgw / 2) + 1, hy = Math.floor(dgh / 2) + 1;
          for (var ry = -hy; ry <= hy; ry++) for (var rx = -hx; rx <= hx; rx++) {
            if (Math.abs(rx) !== hx && Math.abs(ry) !== hy) continue;   // the ring only
            var cxx = rx0 + rx, cyy = ry0 + ry;
            if (blocked(g, cxx, cyy, u.p, UNITS[u.type].mv)) continue;
            var dd = (cxx - u.x) * (cxx - u.x) + (cyy - u.y) * (cyy - u.y);
            if (dd < bestD) { bestD = dd; bestC = { x: cxx, y: cyy }; }
          }
          if (!bestC) { what = what || 'No way in to the Service Depot'; }
          else {
            u.guard = false; u.stopped = false; u.wp = null;
            u.order = { t: 'move', x: bestC.x, y: bestC.y };
            u.repathAt = -999; u.path = null;
            u.dockB = tgt.id;                       // "I was sent here" — see stepBld
            requestPath(g, u, bestC.x, bestC.y);
            nown++; what = 'Going in for repairs';
          }
        } else if (ud.ammo && u.pad && tgt.kind === 'b' && tgt.type === 'airforce') {
          // `rtb` is the same flag the auto-return and a Stop order both set;
          // the pad cycle does the rest (fly home, land on its own slot,
          // rearm one missile per `reload` ticks).
          u.guard = false; u.stopped = false; u.wp = null; u.order = null;
          u.rtb = true; u.path = null; u.repathAt = -999;
          nown++; what = u.ammo ? 'Returning to rearm' : 'Out of missiles — heading home';
        } else if (ud.ivan && !tgt.bomb) {
          u.guard = false; u.stopped = false; u.wp = null;
          u.order = { t: 'attack', x: 0, y: 0, id: tgt.id, force: 1 }; u.repathAt = -999; u.path = null;
          u.guardX = entX(tgt); u.guardY = entY(tgt);
          requestPath(g, u, Math.round(u.guardX), Math.round(u.guardY));
          nown++; what = 'Bombing our own ' + describeShort(tgt);
        }
      });
      if (local && nown) { say(what); sfx('click'); unitAck(us, 'move'); }
      return;

    case 'garrison':
      us = entsOf(g, c.u); tgt = entOf(g, c.id);
      if (!tgt) return;
      var ng = 0;
      us.forEach(function (u) {
        if (!canOccupy(u.type)) return;
        u.guard = false; u.stopped = false;
        u.order = { t: 'garrison', x: 0, y: 0, id: tgt.id }; u.repathAt = -999;
        requestPath(g, u, Math.round(tgt.cx), Math.round(tgt.cy)); ng++;
      });
      if (local && ng) { say('Entering ' + bspecOfB(g, tgt).name); sfx('click'); unitAck(us, 'move'); }
      return;

    case 'rally':
      var prod = entsOf(g, c.b);
      prod.forEach(function (b) { b.rally = makeRally(g, b, c.x, c.y); });
      if (local && prod.length) {
        eva('New rally point established', 4000);                 // eva.ini #100
        say(prod.length > 1 ? 'Rally point set for ' + prod.length + ' buildings'
                            : 'Rally point set — new units will head there');
        sfx('click');
        g.fx.push({ x: c.x, y: c.y, t: 0, life: 22, size: 0, ping: true });
      }
      return;

    case 'evac':                                   // D on a held building
      var held = entsOf(g, c.b), out = 0;
      held.forEach(function (b) { out += ejectGarrison(g, b); });
      if (!local) return;
      setSel(sel.filter(function (e) { return !e.dead; }));
      say(out ? 'Evacuated — ' + out + (out === 1 ? ' infantryman' : ' infantrymen') + ' back on the street'
              : 'Nowhere to put them — the street is blocked', !out);
      sfx(out ? 'click' : 'no'); refreshCmdbar();
      return;

    case 'unload':
      us = entsOf(g, c.u);
      var outN = 0, waiting = 0;
      us.forEach(function (u) {
        if (paxCount(u) <= 0) return;
        if (UNITS[u.type].air) {
          u.landReq = 1; u.unloadReq = 1; u.order = null; u.path = null;
          if (u.landed && g.tick - (u.landAt == null ? -9999 : u.landAt) >= LAND_T) { outN += unloadTransport(g, u).length; u.unloadReq = 0; }
          else waiting++;
        } else outN += unloadTransport(g, u).length;
      });
      if (!local) return;
      if (outN) say('Unloaded — ' + outN + ' out');
      else if (waiting) say('Landing to unload');
      else say('Nowhere to put them — the ground around it is blocked', true);
      sfx(outN || waiting ? 'click' : 'no'); refreshCmdbar();
      return;

    case 'mcv':
      us = entsOf(g, c.u);
      var made = 0;
      us.forEach(function (u) { if (UNITS[u.type].deploysInto && deployMcv(g, u)) made++; });
      if (!local) return;
      setSel(sel.filter(function (e) { return !e.dead; }));
      if (made) { say('Construction Yard deployed'); sfx('place'); eva('Construction complete', 3000); unitAck(us, 'deploy'); }
      else { eva('Cannot deploy here', 4000); say('Cannot deploy here — the MCV needs a clear 3x3 of open ground', true); sfx('no'); }
      refreshCmdbar();
      return;

    case 'dig':                                    // GI / Desolator deploy toggle
      us = entsOf(g, c.u).filter(function (u) { return UNITS[u.type].dep || UNITS[u.type].deployRad; });
      if (!us.length) return;
      var on = !!c.on;
      us.forEach(function (u) { u.deployed = on; u.order = null; u.path = null; u.wp = null; u.guardX = u.x; u.guardY = u.y; });
      if (!local) return;
      var dn = UNITS[us[0].type].deployRad ? 'Desolator' : 'GI';
      say((on ? 'Deployed' : 'Undeployed') + ' — ' + us.length + ' ' + dn + (us.length === 1 ? '' : 's'));
      sfx('click');
      if (on) unitAck(us, 'deploy');
      return;

    case 'scatter':
      us = entsOf(g, c.u);
      if (!us.length) return;
      var mx = 0, my = 0;
      us.forEach(function (u) { mx += u.x; my += u.y; });
      mx /= us.length; my /= us.length;
      us.forEach(function (u, i) {
        var a = Math.atan2(u.y - my, u.x - mx);
        if (!isFinite(a) || (u.x === mx && u.y === my)) a = i * 2.4;
        orderUnitsTo(g, [u], Math.max(0, Math.min(MAP - 1, Math.round(u.x + Math.cos(a) * 2))),
                              Math.max(0, Math.min(MAP - 1, Math.round(u.y + Math.sin(a) * 2))));
      });
      if (local) { say('Scatter'); sfx('click'); }
      return;

    case 'hold':                                   // guard / stop
      us = entsOf(g, c.u);
      if (!us.length) return;
      var isG = c.kind === 'guard';
      us.forEach(function (u) {
        u.order = null; u.path = null; u.wp = null; u.guardX = u.x; u.guardY = u.y;
        if (isHarv(u)) { u.state = 'idle'; u.mineAt = null; u.holdUntil = g.tick + 60 * 20; }
        if (UNITS[u.type].ammo) u.rtb = true;      // RA2: a stopped aircraft returns to its pad
        u.guard = isG; u.stopped = !isG;
      });
      if (local) {
        say((isG ? 'Guarding this ground — they will engage within ' + GUARD_STRAY + ' cells and return'
                 : 'Stopped — holding position') + ' (' + us.length + ' unit' + (us.length === 1 ? '' : 's') + ')');
        if (c.sfx) sfx('click');
      }
      return;

    case 'queue':
      if (!canBuild(g, p, c.k, isBldLane(c.lane))) return;
      if (enqueue(g, p, c.k, c.lane)) { if (local) sfx('click'); }
      else if (local) { say('Queue is full — ' + QUEUE_MAX + ' items', true); sfx('no'); }
      return;

    case 'pause':                                    // RA2: right-click holds, click resumes
      var pq = g.side[p].queues[c.lane];
      if (!pq || pq.list[0] !== c.k || (isBldLane(c.lane) && pq.ready)) return;
      pq.pause = !pq.pause;
      if (local) {
        sfx('click');
        var pn = (isBldLane(c.lane) ? bspecOf(g, c.k, p) : UNITS[c.k]).name;
        say(pq.pause ? 'On hold — ' + pn + ' (click to resume, right-click again to cancel)' : 'Resumed — ' + pn);
      }
      return;

    case 'cancel':
      var refunded = cancelLast(g, p, c.lane, c.k);
      if (refunded !== false && local) {
        sfx('click');
        say('Cancelled ' + (isBldLane(c.lane) ? bspecOf(g, c.k, p) : UNITS[c.k]).name +
            (refunded > 0 ? ' — refunded $' + Math.round(refunded) : ''));
      }
      return;

    case 'place':
      if (!canPlace(g, p, c.k, c.x, c.y)) {
        if (local) { say('Can’t build there — needs clear ground inside the green area', true); sfx('no'); }
        return;
      }
      var nb = placeBld(g, c.k, p, c.x, c.y);
      g.side[p].queues[laneOfBld(c.k)].ready = null;
      if (c.k === 'refinery') {
        var sp = freeTileNear(g, c.x, c.y + bspecOf(g, c.k, p).gh + 1);
        if (sp) spawnUnit(g, 'harvester', p, sp.x, sp.y);
      }
      if (local && nb) { sfx('place'); say(bspecOf(g, c.k, p).name + ' online'); }
      return;

    case 'wall':
      if (!canPlace(g, p, c.k, c.x, c.y)) return;
      if (!c.free) {
        if (g.side[p].credits < bspecOf(g, c.k, p).cost) return;
        g.side[p].credits -= bspecOf(g, c.k, p).cost;
      } else g.side[p].queues[laneOfBld(c.k)].ready = null;
      placeBld(g, c.k, p, c.x, c.y);
      if (local) sfx('place');
      return;

    case 'sell':
      tgt = entOf(g, c.id);
      if (!tgt || tgt.kind !== 'b' || tgt.p !== p || tgt.sell) return;
      sellBld(g, tgt, local);
      return;

    case 'power':
      tgt = entOf(g, c.id);
      if (!tgt || tgt.kind !== 'b' || tgt.p !== p) return;
      tgt.offline = !tgt.offline;
      recalcPower(g, tgt.p);
      if (!local) return;
      eva(tgt.offline ? 'Building offline' : 'Building online', 3000);   // eva.ini #60 / #61
      say((tgt.offline ? 'Powered down ' : 'Powered up ') + bspecOfB(g, tgt).name);
      sfx(tgt.offline ? 'powoff' : 'powon', tgt.cx, tgt.cy);
      return;

    case 'repair':
      tgt = entOf(g, c.id);
      if (!tgt || tgt.kind !== 'b' || tgt.p !== p) return;
      tgt.repair = !tgt.repair;
      if (!local) return;
      if (tgt.repair) eva('Repairing', 4000);                            // eva.ini #57
      say(tgt.repair ? 'Repairing ' + BLDS[tgt.type].name : 'Repair stopped');
      sfx(tgt.repair ? 'wrench' : 'click', tgt.cx, tgt.cy);
      return;

    case 'sw':
      var okSw = SW[c.k].two ? swFire(g, p, c.k, c.x, c.y, c.x2, c.y2)
                             : swFire(g, p, c.k, c.x, c.y);
      if (local && !okSw) say(SW[c.k].name + ' is not charged', true);
      if (local) refreshSW();
      return;

    case 'destroy':                                // keyboard.ini Delete
      var dl = entsOf(g, c.u).filter(function (o) { return o.p === p; });
      dl.forEach(function (o) {
        if (o.kind === 'b') killBld(g, o);
        else { o.dead = true; if (!headless) g.fx.push({ x: o.x, y: o.y, t: 0, life: 22, size: 10 }); }
      });
      if (local && dl.length) {
        clearSel(); sfx('boom');
        say('Self-destructed ' + dl.length + ' ' + (dl.length === 1 ? 'object' : 'objects'), true);
      }
      return;
  }
}

// RA2 ground units do not share a cell. The separation push lives inside
// moveAlong, which only runs while a unit is FOLLOWING A PATH, so a unit
// that has STOPPED — order complete, order dropped, or never given one —
// settles wherever it happens to stand and stays there, on top of whatever
// else stopped on the same tile. The soak measured 66 settled stacks (five
// bodies, or three vehicles, parked on one cell) across 24 hard-vs-easy
// matches, 57 of them units carrying no order at all: an AI staging area,
// a rally point, or a wave that arrived and had nothing left to kill.
//
// This is the same push, at a shuffle's pace, for a unit that did not move
// on its own this tick. It deliberately does NOT touch `movedAt` or
// `noProg`: a shuffle is not progress, and the stuck detectors have to keep
// reading a jammed unit as jammed.
var SETTLE_R = 0.85, SETTLE_SPD = 0.02;

function stepSettle(g) {
  for (var i = 0; i < g.units.length; i++) {
    var u = g.units[i];
    if (u.dead || u.air || u.limbo || u.warp || u.erase > 0) continue;
    // A unit that is walking, or has walked in the last second and a half,
    // is already sorting itself out through moveAlong's own separation.
    if (g.tick - (u.movedAt == null ? -1e9 : u.movedAt) < 90) continue;
    // ...and a unit in a firefight holds the ground it is shooting from.
    // Without this the shuffle spread every firing line in the game, which
    // is worth more to the side standing in its own base than to the side
    // walking into it: measured on two disjoint 12-seed sets, hard vs
    // normal fell 22/24 -> 19/24 on both.
    if (g.tick - (u.fireAt == null ? -1e9 : u.fireAt) < 180) continue;
    if (u.deployed || u.landed) continue;            // deployed men and parked hulls hold their ground
    if (u.state === 'mining') continue;              // a miner on its seam stays on it
    if (u.order && u.order.t === 'coil') continue;   // hand-feeding a Tesla Coil is a position
    var d = UNITS[u.type];
    if (d.nav) continue;                             // hulls keep station by their own rules
    var sx = 0, sy = 0, n = 0;
    near(u.x, u.y, SETTLE_R, function (o) {
      if (o === u || o.dead || o.kind !== 'u' || o.air || o.limbo) return;
      var ox = u.x - o.x, oy = u.y - o.y, od = Math.sqrt(ox * ox + oy * oy);
      if (od >= SETTLE_R) return;
      n++;
      // Exactly co-located: the vector is zero and no push exists. Break the
      // tie off the ids so the shove is the same on every client.
      if (od < 1e-4) { ox = (u.id > o.id) ? 1 : -1; oy = ((u.id + o.id) & 1) ? 1 : -1; od = Math.SQRT2; }
      sx += ox / od * (SETTLE_R - od); sy += oy / od * (SETTLE_R - od);
    });
    if (!n) continue;
    var len = Math.sqrt(sx * sx + sy * sy);
    if (len < 1e-6) continue;
    var st = Math.min(SETTLE_SPD, len), mv = moverOf(u);
    var nx = u.x + sx / len * st, ny = u.y + sy / len * st;
    if (tilePassable(g, nx, u.y, u.p, mv)) u.x = Math.max(0, Math.min(MAP - 1, nx));
    if (tilePassable(g, u.x, ny, u.p, mv)) u.y = Math.max(0, Math.min(MAP - 1, ny));
  }
}

export function simStep(g) {
  g.tick++;
  netApplyDue(g);
  if (g.tick - hashAt >= 3 || hashAt > g.tick) { rebuildHash(g); setHashAt(g.tick); }
  runPathQueue(g, Math.min(40, 8 + (pathQ.length >> 2)));

  var i;
  for (i = 0; i < g.units.length; i++) if (!g.units[i].dead) stepUnit(g, g.units[i]);
  stepSettle(g);
  for (i = 0; i < g.blds.length; i++) if (!g.blds[i].dead) stepBld(g, g.blds[i]);
  if (g.debug) {                                   // debug mode: bottomless bank, no shroud
    g.side[P_HUMAN].credits = 999999;
    if (!g.debugSeen) { for (i = 0; i < g.seen.length; i++) g.seen[i] = 1; g.debugSeen = true; }
  }
  stepQueues(g, P_HUMAN);
  stepQueues(g, P_AI);
  stepSuper(g);
  if (g.ai) stepAI(g, g.ai, P_AI, P_HUMAN);
  if (g.ai2) stepAI(g, g.ai2, P_HUMAN, P_AI);
  if ((g.tick % 6) === 1 || g.tick <= 2) { applyGaps(g); revealFor(g, ME); }
  // Ore regrows on existing seams. [General] GrowthRate=5 is FIVE MINUTES
  // between growth passes, and [Riparius] GrowthPercentage=.06 is the chance
  // a given cell thickens on each pass. This ran every SECOND at +2, which
  // refilled a mined-out seam from 120 to full in about six minutes and made
  // ore effectively infinite — the spread code beside it already had the
  // period right, which is what made the growth rate stand out.
  if ((g.tick % ORE_GROW_T) === (ORE_GROW_T - 1)) {
    var ore = g.ore, ter = g.terrain, gpass = ++g.grow;
    for (var oi = 0; oi < ore.length; oi++) {
      if (!oreT(ter[oi]) || ore[oi] >= 900) continue;
      if (hash3(g.seed, oi, gpass + 4177) >= 0.06) continue;    // GrowthPercentage=.06
      ore[oi] = Math.min(900, ore[oi] + 75);                    // one of RA2's twelve density stages
    }
  }
  // ...and, far more slowly, throws a seam into the ground next to it.
  if ((g.tick % ORE_SPREAD_T) === (ORE_SPREAD_T - 1)) stepOreSpread(g);
  stepCrates(g);
  stepEvaWatch(g);
  stepDrops(g);
  stepInfest(g);
  stepBombs(g);
  stepErase(g);
  stepRad(g);

  // effects
  stepWrecks(g);
  stepRubble(g);
  for (i = g.shots.length - 1; i >= 0; i--) if (++g.shots[i].t > g.shots[i].life) g.shots.splice(i, 1);
  for (i = g.fx.length - 1; i >= 0; i--) if (++g.fx[i].t > g.fx[i].life) g.fx.splice(i, 1);

  // reap
  if ((g.tick & 31) === 0) {
    for (i = g.units.length - 1; i >= 0; i--) {
      if (g.units[i].dead) { delete g.byId[g.units[i].id]; g.units.splice(i, 1); }
    }
    for (i = g.blds.length - 1; i >= 0; i--) {
      if (g.blds[i].dead) { delete g.byId[g.blds[i].id]; g.blds.splice(i, 1); }
    }
  }

  // A side with no harvester, no way to buy one, and no way to rebuild the
  // factory that makes one has already lost — it just cannot be finished
  // off quickly through a wall of turrets. Without this a decided match can
  // run forever, which is worse for everyone than calling it.
  for (i = 0; i < 2; i++) {
    if (economyDead(g, i)) g.side[i].deadFor++; else g.side[i].deadFor = 0;
  }
  if (!g.over) {
    if (g.side[P_AI].deadFor > 60 * 75) g.over = 1;
    else if (g.side[P_HUMAN].deadFor > 60 * 75) g.over = -1;
  }

  // win / lose — losing every structure ends it
  if (!g.over) {
    var mine = 0, theirs = 0;
    for (i = 0; i < g.blds.length; i++) {
      if (g.blds[i].dead) continue;
      // Insignificant=yes / BaseNormal=no: a ring of walls is not a base,
      // so a side down to its perimeter has already lost.
      if (BLDS[g.blds[i].type].wall || BLDS[g.blds[i].type].gate) continue;
      // A city block or an oil derrick belongs to nobody, and a captured one
      // is Unsellable=yes/Insignificant=yes in rules.ini: neither side wins
      // or loses a match on it.
      if (neutral(g.blds[i].p) || BLDS[g.blds[i].type].neut) continue;
      if (g.blds[i].p === P_HUMAN) mine++; else theirs++;
    }
    // RA2: you are not beaten while an MCV is still rolling, and neither is
    // anyone who can still buy one. Selling your last yard with an MCV in
    // hand is a base MOVE, not a surrender.
    mine += countUnit(g, P_HUMAN, 'mcv') + (canBuild(g, P_HUMAN, 'mcv', false) ? 1 : 0);
    theirs += countUnit(g, P_AI, 'mcv') + (canBuild(g, P_AI, 'mcv', false) ? 1 : 0);
    // "Short Game" off is RA2's LONG game: levelling the base is not
    // enough, the last vehicle and the last rifleman have to go too.
    if (!g.opt.short) {
      mine += countUnit(g, P_HUMAN, null);
      theirs += countUnit(g, P_AI, null);
    }
    if (theirs === 0) g.over = 1;
    else if (mine === 0) g.over = -1;
  }
  if (g.over && g.overAt == null) g.overAt = g.tick;   // the infantry Cheer starts here
  netTick(g);                                          // lockstep desync checkpoint
}

// --- generated ---
// ESM import bindings are read-only, so a write from another module goes
// through the owner. Reads stay verbatim everywhere: the binding is live.
export function setLOCKSTEP_DELAY(v) { LOCKSTEP_DELAY = v; }
