// Iron Frontier — neutral.js
// GENERATED by apps/games/rts/tools/modularize from rts.src.html + art/units/**.

import { BLDS } from './blds.js';
import { bspecFor, eliteOf, harvKey, isHarv, isWall, versesVs, vetFire, vetRofU } from './combat-tables.js';
import { boom, damage, dist, entX, entY, findTarget, fire, infCorpse, isInf, near } from './combat.js';
import { DOOR_OPEN, DOOR_T, powered, spawnUnit } from './entities.js';
import { FACTIONS, facOf } from './factions.js';
import { altOf, canHit, labelWater } from './geom.js';
import { CHARGE_T, prismSupport, stepGate } from './move.js';
import { emitUnit, freeTileNear } from './production.js';
import { UNITS } from './roster.js';
import { coilCharged, killDrone } from './special.js';
import { headless, idx, inMap } from './state.js';
import { eva, sfx } from './ui/audio.js';
import { creditPop, say } from './ui/hud.js';
import { finishSell } from './ui/input.js';
import { MAP, ME, P_NEUT, T_BRIDGE, T_GROUND, T_ORE, T_WATER, buildableT, neutral } from './world.js';

// ===================================================================== //
//  The neutral house: garrisoning, tech buildings, bridges, crates
//
//  RA2's civilian layer is not scenery. A city block with `CanBeOccupied=yes`
//  is a fortress waiting for infantry; an Oil Derrick is an income stream
//  waiting for an Engineer; a bridge is a road that can be cut. All of it
//  hangs off ONE idea — structures owned by house -1 (`P_NEUT`) that sit in
//  `g.blds` like any other, so occupancy, pathing, targeting, damage and
//  rendering need no special case beyond "there is no g.side[-1]".
// ===================================================================== //

// rules.ini `Occupier=yes` appears on exactly TWO infantry sections in
// v1.006: [E1] (GI) and [E2] (Conscript). A Flak Trooper, a Tesla Trooper
// or Tanya cannot garrison, however much you would like them to.
var OCCUPIER = { rifle: 1, conscript: 1 };

// [General] ThreatPerOccupant=10 — what a garrison adds to the building's
// pull on enemy target selection, per man inside.
export var THREAT_PER_OCCUPANT = 10;

export function occCapOf(b) { return (BLDS[b.type] && BLDS[b.type].occCap) || 0; }

export function occCount(b) { return b.occ ? b.occ.length : 0; }

export function canOccupy(type) { return !!OCCUPIER[type]; }

// Can THIS man walk into THAT building? Only an Occupier, only a civilian
// block, only one that is empty or already ours, and only if there is room.
export function garrisonable(g, b, p) {
  if (!b || b.dead || !occCapOf(b) || b.make > 0) return false;
  if (!neutral(b.p) && b.p !== p) return false;
  return occCount(b) < occCapOf(b);
}

export function enterGarrison(g, b, u) {
  if (!garrisonable(g, b, u.p) || !canOccupy(u.type)) return false;
  if (!b.occ) b.occ = [];
  var first = !b.occ.length;
  b.occ.push({ type: u.type, hp: u.hp, rank: u.rank || 0, cool: 0, port: b.occ.length });
  // RA2 hands the building to the occupying house the moment the first man
  // is inside — it flies your colour, it shoots for you, and the enemy can
  // now target it. The last man out hands it back.
  b.p = u.p;
  u.dead = true; u.sel = false; u.order = null;
  if (u.p === ME) eva('Structure garrisoned', 4000);       // eva.ini #107
  if (first && !headless) sfx('garrin', b.cx, b.cy);
  return true;
}

// Everybody out. RA2 puts the men back on the ground around the building at
// the health they went in with; the block reverts to the neutral house.
export function ejectGarrison(g, b) {
  if (!b.occ || !b.occ.length) return 0;
  var n = 0, p = b.p;
  for (var i = 0; i < b.occ.length; i++) {
    var o = b.occ[i], sp = freeTileNear(g, Math.round(b.cx), Math.round(b.cy));
    if (!sp) break;
    var u = spawnUnit(g, o.type, p, sp.x, sp.y);
    u.hp = Math.max(1, o.hp); u.rank = o.rank; n++;
  }
  b.occ.length = 0;
  b.p = P_NEUT; b.sel = false; b.target = null;
  if (!headless) sfx('garrout', b.cx, b.cy);
  if (p === ME) eva('Structure abandoned', 4000);          // eva.ini #108
  return n;
}

// The building came down with men inside. RA2 kills every occupant.
export function killOccupants(g, b) {
  if (!b.occ || !b.occ.length) return;
  for (var i = 0; i < b.occ.length; i++) {
    if (!headless) infCorpse(g, { kind: 'u', type: b.occ[i].type, p: b.p, x: b.cx, y: b.cy }, 'HE');
    if (!neutral(b.p)) g.side[b.p].lost++;
  }
  b.occ.length = 0;
}

// Occupants fire their OWN weapons out of the windows. A garrison of GIs is
// a ring of M60s behind cover, which is exactly why RA2 players fight over
// the crossroads block.
function garrisonTarget(g, b, spec) {
  var best = null, bs = -Infinity;
  near(b.cx, b.cy, spec.rng + 1.5, function (o) {
    if (o.dead || o.p === b.p || neutral(o.p)) return;
    if (!canHit(spec, o) || isWall(o)) return;
    var dd = dist(b, o);
    if (dd > spec.rng + 0.5) return;
    var mult = spec.wh ? versesVs(spec.wh, o) : 1;
    if (mult <= 0) return;
    var sc = mult * 100 - dd * 6 - (o.hp / o.maxhp) * 40;
    if (sc > bs) { bs = sc; best = o; }
  });
  return best;
}

// Where a man's muzzle sits on the block's face. Four ports round the
// sprite, so a full garrison flashes from several windows at once rather
// than stacking every shot on the roof ridge.
var GARRISON_PORTS = [[-13, 30], [13, 30], [-9, 16], [9, 16]];

function stepGarrison(g, b) {
  var fired = null;
  for (var i = 0; i < b.occ.length; i++) {
    // Occupants keep their rank through the garrison (stashed and restored
    // with them), so they keep their `ElitePrimary=` and their Burst too.
    var o = b.occ[i], d = eliteOf(UNITS[o.type], o);
    if (o.cool > 0) { o.cool--; continue; }
    var t = garrisonTarget(g, b, d);
    if (!t) continue;
    o.cool = d.rate * vetRofU(o);              // [General] VeteranROF=0.6, at this unit's own rank
    fired = t;
    if (!headless) {
      var pt = GARRISON_PORTS[o.port % GARRISON_PORTS.length];
      g.shots.push({ x: b.cx, y: b.cy, tx: entX(t), ty: entY(t), t: 0, life: 7, id: g.nextId++,
                     ox: pt[0], alt: pt[1], talt: t.kind === 'u' ? altOf(t) : 0 });
    }
    damage(g, b, t, d.dmg * (d.burst || 1) * vetFire(o.rank), d.wh);
  }
  b.target = fired;
  if (fired && !headless && (g.tick % 12) === 0) sfx('shot');
}

// Everything the neutral house does on its own tick: garrison fire, the
// derrick's cash trickle ([CAOILD] ProduceCashAmount/Delay) and the
// hospital's field healing ([CATHOSP] Hospital=yes).
function stepNeutral(g, b) {
  var d = BLDS[b.type];
  if (b.occ && b.occ.length) stepGarrison(g, b);
  if (neutral(b.p)) return;                       // the rest needs an owner
  if (d.cash && (g.tick % d.cashDelay) === 0) {
    g.side[b.p].credits += d.cash;
    if (b.p === ME && !headless && (g.tick % (d.cashDelay * 10)) === 0) creditPop(d.cash * 10);
  }
  if (d.heal && (g.tick % 30) === 0) {
    for (var i = 0; i < g.units.length; i++) {
      var u = g.units[i];
      if (u.dead || u.p !== b.p || !isInf(u) || u.hp >= u.maxhp) continue;
      if (dist(u, b) > d.heal) continue;
      u.hp = Math.min(u.maxhp, u.hp + u.maxhp * 0.04);
    }
  }
}

// ---- Bridges ([General] DestroyableBridges=yes, BridgeStrength=1500) --- //
// A span is a column of deck cells (indexBridges). Force-fire, a nuke or a
// storm bolt on the deck takes it down; the cells revert to open water, the
// traffic on them goes into the river, and `g.bwrk` remembers the torn ends.
export function damageBridge(g, x, y, amount) {
  x = Math.round(x); y = Math.round(y);
  if (!inMap(x, y)) return false;
  var si = g.bspan[idx(x, y)];
  if (!si) return false;
  var sp = g.bridges[si - 1];
  if (sp.down) return false;
  sp.hp -= amount;
  if (sp.hp <= 0) collapseSpan(g, sp);
  return true;
}

export function collapseSpan(g, sp) {
  sp.down = true; sp.hp = 0;
  var i, c;
  for (i = 0; i < sp.cells.length; i++) {
    c = sp.cells[i];
    g.terrain[c] = T_WATER;
    g.bwrk[c] = 1;                                 // this water used to be a deck
  }
  labelWater(g);                                   // a dropped span can JOIN two bodies of water
  for (i = 0; i < g.units.length; i++) {
    var u = g.units[i];
    if (u.dead || u.air) continue;
    var ci = idx(Math.max(0, Math.min(MAP - 1, Math.round(u.x))), Math.max(0, Math.min(MAP - 1, Math.round(u.y))));
    if (g.bspan[ci] !== sp.cells.length && sp.cells.indexOf(ci) < 0) continue;
    u.dead = true; u.path = null;
    if (!headless) boom(g, u.x, u.y, 14);
  }
  if (headless) return;
  for (i = 0; i < sp.cells.length; i++) {
    var cx = sp.cells[i] % MAP, cy = (sp.cells[i] / MAP) | 0;
    g.fx.push({ x: cx, y: cy, t: -i * 3, life: 30, size: 18 });
  }
  sfx('bridge', sp.x, sp.y);
  say('A bridge span has collapsed', true);
}

// [CABHUT] BridgeRepairHut=yes: an engineer walks in and the span comes
// back. The hut serves whatever spans lie within a few cells of it, which
// is how RA2's huts sit at both ends of one crossing.
export function repairBridgeFrom(g, b) {
  var n = 0;
  for (var i = 0; i < g.bridges.length; i++) {
    var sp = g.bridges[i];
    if (!sp.down) continue;
    var best = 1e9;
    for (var c = 0; c < sp.cells.length; c++) {
      var cx = sp.cells[c] % MAP, cy = (sp.cells[c] / MAP) | 0;
      var dd = Math.abs(cx - b.cx) + Math.abs(cy - b.cy);
      if (dd < best) best = dd;
    }
    if (best > 9) continue;
    sp.down = false; sp.hp = sp.maxhp;
    for (c = 0; c < sp.cells.length; c++) { g.terrain[sp.cells[c]] = T_BRIDGE; g.bwrk[sp.cells[c]] = 0; }
    labelWater(g);                                 // and a repaired one can split them again
    n++;
  }
  return n;
}

// ---- Crates ([CrateRules] / [Powerups]) ------------------------------- //
// CrateMinimum=1 (one per player), CrateRegen=3 (minutes), CrateRadius=3.0
// for the area bonuses. The weights are the first field of each [Powerups]
// row; the ones RA2 leaves at weight 0 (IonStorm, Pod, Napalm...) are not
// in the pool, and neither is Cloak, which we have nothing to cloak with.
var CRATE_MIN = 2, CRATE_REGEN = 3 * 60 * 60, CRATE_RADIUS = 3.0;

var CRATE_POOL = [
  { k: 'money',   w: 20 }, { k: 'veteran', w: 20 }, { k: 'unit',    w: 20 },
  { k: 'armor',   w: 10 }, { k: 'firepower', w: 10 }, { k: 'healbase', w: 10 },
  { k: 'reveal',  w: 10 }, { k: 'speed',   w: 10 }
];

// A hash, not a stateful RNG: crate placement and contents have to be
// reproducible from (seed, tick) alone so a replay lands the same crate in
// the same field with the same prize.
export function hash3(a, b, c) {
  var h = ((a | 0) * 374761393 + (b | 0) * 668265263 + (c | 0) * 2246822519) >>> 0;
  h = (h ^ (h >>> 13)) >>> 0; h = (h * 1274126177) >>> 0;
  return ((h ^ (h >>> 16)) >>> 0) / 4294967296;
}

function crateSpot(g, salt) {
  for (var tries = 0; tries < 200; tries++) {
    var x = (hash3(g.seed, salt, tries * 2 + 1) * MAP) | 0;
    var y = (hash3(g.seed, salt, tries * 2 + 2) * MAP) | 0;
    if (!inMap(x, y)) continue;
    var i = idx(x, y);
    if (!buildableT(g.terrain[i]) || g.occ[i]) continue;
    var near0 = false;
    for (var p = 0; p < 2; p++) {
      var st = g.start[p];
      if (st && Math.abs(x - st.x) < 12 && Math.abs(y - st.y) < 12) near0 = true;
    }
    if (near0) continue;
    var taken = false;
    for (var c = 0; c < g.crates.length; c++) if (g.crates[c].x === x && g.crates[c].y === y) taken = true;
    if (taken) continue;
    return { x: x, y: y };
  }
  return null;
}

function crateKind(g, salt) {
  var total = 0, i;
  for (i = 0; i < CRATE_POOL.length; i++) total += CRATE_POOL[i].w;
  var r = hash3(g.seed, salt, 7777) * total;
  for (i = 0; i < CRATE_POOL.length; i++) { r -= CRATE_POOL[i].w; if (r <= 0) return CRATE_POOL[i].k; }
  return 'money';
}

function spawnCrate(g, salt) {
  var sp = crateSpot(g, salt);
  if (!sp) return null;
  var cr = { x: sp.x, y: sp.y, kind: crateKind(g, salt), born: g.tick, id: g.nextId++ };
  g.crates.push(cr);
  return cr;
}

export function stepCrates(g) {
  if (g.noCrates) return;
  // CrateMinimum=1 per player: the board starts at its floor, then one more
  // arrives every CrateRegen=3 minutes for as long as it is below it.
  if (!g.opt.crates) return;                     // skirmish "Crates" off: none ever spawn
  if (g.tick <= 2) { while (g.crates.length < CRATE_MIN) if (!spawnCrate(g, g.crates.length + 1)) break; }
  else if (g.tick >= g.crateAt && g.crates.length < CRATE_MIN) {
    spawnCrate(g, g.tick);
    g.crateAt = g.tick + CRATE_REGEN;
  }
  if ((g.tick & 3) !== 0) return;
  for (var i = g.crates.length - 1; i >= 0; i--) {
    var cr = g.crates[i], got = null;
    for (var j = 0; j < g.units.length; j++) {
      var u = g.units[j];
      if (u.dead || u.air || isHarv(u)) continue;
      if (Math.abs(u.x - cr.x) > 0.75 || Math.abs(u.y - cr.y) > 0.75) continue;
      got = u; break;
    }
    if (!got) continue;
    g.crates.splice(i, 1);
    if (got.p === ME) sfx('crate');
    openCrate(g, cr, got);
    g.crateAt = Math.min(g.crateAt, g.tick + CRATE_REGEN);
  }
}

// FreeMCV=yes: a player with money but no buildings gets an MCV out of the
// next crate he touches, whatever was in it.
export function openCrate(g, cr, u) {
  var p = u.p, s = g.side[p], k = cr.kind, i, msg = '', glyph = '?';
  var noBase = true;
  for (i = 0; i < g.blds.length; i++) if (!g.blds[i].dead && g.blds[i].p === p) { noBase = false; break; }
  if (noBase) k = 'unit';
  function around(fn) {
    for (var q = 0; q < g.units.length; q++) {
      var o = g.units[q];
      if (o.dead || o.p !== p) continue;
      if (Math.abs(o.x - cr.x) > CRATE_RADIUS || Math.abs(o.y - cr.y) > CRATE_RADIUS) continue;
      fn(o);
    }
  }
  if (k === 'money') {
    s.credits += 2000; msg = '$2000'; glyph = '$';
    if (p === ME) { creditPop(2000); sfx('cash'); }
  } else if (k === 'veteran') {
    u.rank = Math.min(2, (u.rank || 0) + 1); msg = 'Veteran'; glyph = '★';
    if (p === ME) eva('Unit promoted', 3000);
  } else if (k === 'firepower') {
    around(function (o) { o.fpMul = Math.max(o.fpMul || 1, 2.0); });      // [Powerups] Firepower ...,2.0
    msg = 'Firepower'; glyph = '⚔';
    if (p === ME) eva('Unit firepower upgraded', 3000);             // eva.ini #76
  } else if (k === 'armor') {
    around(function (o) { o.arMul = Math.max(o.arMul || 1, 1.5); });      // [Powerups] Armor ...,1.5
    msg = 'Armour'; glyph = '🛡';
    if (p === ME) eva('Unit armor upgraded', 3000);                 // eva.ini #77
  } else if (k === 'speed') {
    around(function (o) { o.spMul = Math.max(o.spMul || 1, 1.2); });      // [Powerups] Speed ...,1.2
    msg = 'Speed'; glyph = '»';
    if (p === ME) eva('Unit speed upgraded', 3000);                 // eva.ini #78
  } else if (k === 'healbase') {
    for (i = 0; i < g.blds.length; i++) if (!g.blds[i].dead && g.blds[i].p === p) g.blds[i].hp = g.blds[i].maxhp;
    msg = 'Base repaired'; glyph = '✚';
  } else if (k === 'reveal') {
    if (p === ME) for (i = 0; i < g.seen.length; i++) g.seen[i] = 1;
    msg = 'Map revealed'; glyph = '👁';
    if (p === ME) eva('New terrain discovered', 3000);              // eva.ini #39
  } else {
    // [Powerups] Unit / [CrateRules] UnitCrateType=none — a random vehicle,
    // or the free MCV when the owner has nothing left to build from.
    // 'harvester' is a ROLE, not a key: UNITS has chronominer/warminer, so
    // the literal crashed openCrate (and spawned nothing) whenever the die
    // came up 2 for the Directorate.
    var pick = noBase ? 'mcv' : (facOf(g, p) === 'col' ? ['rhino', 'flaktrack', 'v3'] : ['lancer', 'ifv', harvKey(facOf(g, p))])[(hash3(g.seed, cr.id, 5) * 3) | 0];
    var sp2 = freeTileNear(g, cr.x, cr.y);
    if (sp2) spawnUnit(g, pick, p, sp2.x, sp2.y);
    msg = bspecFor ? UNITS[pick].name : 'Unit'; glyph = '🚚';
    if (p === ME) eva('Reinforcements have arrived', 3000);         // eva.ini #38
  }
  if (headless) return;
  g.fx.push({ x: cr.x, y: cr.y, t: 0, life: 60, crateFx: 1, glyph: glyph });
  if (p === ME) say('Crate: ' + msg);
}

// ---- Ore spreading ([Riparius] Spread=2200 SpreadPercentage=.06) ------ //
// RA2 counts Spread in its own logic frames; 2200 of them is about two and
// a half minutes. Every pass, six per cent of the ore cells throw a seam
// into one empty neighbour. Gems do not spread at all — [Cruentus] has
// SpreadPercentage=0 — so a gem field is finite, and that is the point of it.
export var ORE_SPREAD_T = 2200 * 4;                    // 2200 RA2 frames at our 60Hz tick

// [Riparius] Growth=2200 — ore's OWN growth period, the sibling of the
// Spread=2200 the line above already uses, at the same 15 fps. [General]
// GrowthRate=5 is the global logic timer; pairing it with a per-overlay
// GrowthPercentage mixed two scales, and the overlay's own key is the more
// specific reading. Measured over 24 matches: the 5-minute reading left 3
// undecided and the map dry from 18:00; this is the same mechanism at ore's
// documented period.
export var ORE_GROW_T = ORE_SPREAD_T;                  // [Riparius] Growth=2200 frames

export function stepOreSpread(g) {
  var pass = ++g.spread, ter = g.terrain, ore = g.ore, i, n;
  var DIRS = [-1, 1, -MAP, MAP];
  for (i = 0; i < ter.length; i++) {
    if (ter[i] !== T_ORE || ore[i] < 200) continue;                 // a thin seam has nothing to give
    if (hash3(g.seed, i, pass) >= 0.06) continue;                   // SpreadPercentage=.06
    var d = DIRS[(hash3(g.seed, i, pass + 991) * 4) | 0];
    n = i + d;
    if (n < 0 || n >= ter.length) continue;
    if (Math.abs((n % MAP) - (i % MAP)) > 1) continue;              // never wrap a row
    if (ter[n] !== T_GROUND || g.occ[n]) continue;
    ter[n] = T_ORE; ore[n] = 120;
  }
}

// ---- Paradrop ([CAAIRP] SuperWeapon=ParaDropSpecial) ------------------ //
// [General] AllyParaDropInf=E1 AllyParaDropNum=6 / SovParaDropInf=E2
// SovParaDropNum=9. The plane crosses the map, the sticks come down on
// chutes, and they are yours where they land.
export function paraDrop(g, p, gx, gy) {
  var fk = facOf(g, p);
  var n = fk === 'col' ? 9 : 6, type = FACTIONS[fk].inf;
  g.drops.push({ p: p, x: gx, y: gy, type: type, left: n, t: 0, next: 0, men: [] });
  if (p === ME) eva('Reinforcements have arrived', 4000);
  return true;
}

// How long a stick hangs under the canopy, in ticks. The men used to be
// spawned on the ground the instant the run-in finished and a `chute` fx
// pushed on top of them — and nothing ever DREW that flag, so a drop was
// six soldiers appearing out of nothing. They now fall: `dr.men` holds the
// sticks still in the air, each one counted down in the SIM (so a headless
// replay lands them on the same tick a rendered one does) and spawned only
// when its canopy touches the ground.
export var PARA_FALL = 96, PARA_H = 132;        // ticks under canopy, and its height in px

export function stepDrops(g) {
  for (var i = g.drops.length - 1; i >= 0; i--) {
    var dr = g.drops[i];
    dr.t++;
    // Men already under canopy come down whether or not any are left to jump.
    for (var m = dr.men.length - 1; m >= 0; m--) {
      var man = dr.men[m];
      if (--man.fall > 0) continue;
      dr.men.splice(m, 1);
      // The tile it was aimed at may have filled while it was in the air.
      var land = freeTileNear(g, man.x, man.y) || { x: man.x, y: man.y };
      spawnUnit(g, dr.type, dr.p, land.x, land.y);
      if (!headless) g.fx.push({ x: land.x, y: land.y, t: 0, life: 16, size: 7 });
    }
    if (dr.left > 0 && dr.t >= 40 && dr.t >= dr.next) {   // the run-in, then one man every 7 ticks
      dr.next = dr.t + 7;
      var ang = dr.left * 1.9, rr = 0.6 + (dr.left % 3) * 0.7;
      var tx = Math.round(dr.x + Math.cos(ang) * rr), ty = Math.round(dr.y + Math.sin(ang) * rr);
      var sp = freeTileNear(g, Math.max(1, Math.min(MAP - 2, tx)), Math.max(1, Math.min(MAP - 2, ty)));
      if (sp) dr.men.push({ x: sp.x, y: sp.y, fall: PARA_FALL, sway: (dr.left * 2.3) % 6.283 });
      dr.left--;
    }
    if (dr.left <= 0 && !dr.men.length) g.drops.splice(i, 1);
  }
}

export function stepBld(g, b) {
  var d = BLDS[b.type];
  // The neutral house runs its own short tick: no repair bay, no power, no
  // production, but garrison fire, oil money and hospital healing.
  if (d.neut) { if (b.make > 0) b.make = 0; stepNeutral(g, b); return; }
  // Production door: it opens, the finished unit comes out of the mouth
  // partway through, then it shuts again. Never set headless.
  if (b.door > 0) {
    b.door--;
    if (b.hold && DOOR_T - b.door >= DOOR_OPEN) {
      var hd = b.hold; b.hold = null;
      var hsp = freeTileNear(g, hd.x, hd.y);
      if (hsp) emitUnit(g, hd.key, hd.p, hd.lane, b, hsp);
      else b.hold = hd;                       // apron blocked: it waits in the bay
    }
    if (b.hold && b.door <= 0) b.door = 1;    // hold the door open until it can leave
  }
  // Under construction (or being sold, which is the same anim backwards):
  // RA2's MAKE runs before the structure does anything.
  // The build-up: RA2 runs a MAKE anim with a hammering loop under it.
  if (b.make > 0) {
    b.make--;
    if (b.unpack > 0) b.unpack--;
    if (!headless && (b.make % 44) === 0) sfx(b.sell ? 'sell' : 'make', b.cx, b.cy);
    if (b.make <= 0 && b.sell) finishSell(g, b);
    return;
  }
  if (b.cool > 0) b.cool--;
  if (b.repair) {
    if (b.hp >= b.maxhp) b.repair = false;
    else if ((g.tick % 6) === 0) {
      var step = b.maxhp * 0.005, price = d.cost * 0.15 * (step / b.maxhp);   // [General] RepairPercent=15%
      if (g.side[b.p].credits >= price) { g.side[b.p].credits -= price; b.hp = Math.min(b.maxhp, b.hp + step); }
    }
  }
  if (d.gate) { stepGate(g, b); return; }
  if (b.type === 'depot' && (g.tick % 30) === 0 && powered(g, b.p)) {
    // Service Depot: vehicles parked on the pad (or touching it) are repaired.
    for (var di = 0; di < g.units.length; di++) {
      var v = g.units[di];
      if (v.dead || v.p !== b.p || UNITS[v.type].cls !== 'v' || v.air) continue;
      if (v.hp >= v.maxhp && !v.drone) continue;
      // TWO reaches, deliberately, because they answer different questions.
      //
      // "Touching the pad" (gw/2 + 0.6) is the ambient rule and stays exactly
      // as it was: a vehicle that happens to be parked against the depot gets
      // patched, and nothing further out does. Widening THAT would quietly
      // turn the depot into a field hospital for anything fighting nearby.
      //
      // "I was SENT here" (`v.dockB`) is the ordered rule, and it has to
      // reach further for a mechanical reason: the order can only aim at a
      // cell OUTSIDE the footprint (the pathfinder cannot enter a building),
      // that ring sits gw/2 + 0.5 out, and a move COMPLETES within 1.183 of
      // its target — so an obedient vehicle legitimately comes to rest up to
      // gw/2 + 1.7 from the centre. MEASURED: aiming at the pad centre
      // instead made the order impossible to complete, so it was abandoned by
      // the noProg branch and the vehicle stalled at 1.912-2.145 against a
      // 2.1 reach. It worked 89.9% of the time by coincidence on a live page,
      // and 2 of 8 approaches in this suite.
      var sent = v.dockB === b.id;
      var reach = sent ? 1.8 : 0.6;
      if (Math.abs(v.x - b.cx) > b.gw / 2 + reach || Math.abs(v.y - b.cy) > b.gh / 2 + reach) continue;
      // RA2's only cure for a Terror Drone: the bay shakes it out and
      // crushes it before it touches the repair itself.
      if (v.drone) { killDrone(g, v); if (v.p === ME) { eva('Terror Drone destroyed', 4000); say('Service Depot killed the Terror Drone'); } }
      var _was = v.hp;
      v.hp = Math.min(v.maxhp, v.hp + v.maxhp * 0.02);
      if (v.hp >= v.maxhp) v.dockB = 0;                 // the errand is done
      if (v.p === ME && _was < v.maxhp && v.hp >= v.maxhp) eva('Unit repaired', 4000);   // eva.ini #70
    }
  }
  if (!d.dmg) return;
  // Unpowered defences go dark — except the Pillbox, which has no Powered=
  // key in rules.ini ([NALASR] Sentry Gun does, though it draws nothing).
  if (!powered(g, b.p) && (d.power < 0 || b.type === 'sentrygun') && !coilCharged(g, b)) return;
  var t = findTarget(g, b, d.rng);
  b.target = t;                                 // what the turret frames point at
  // Tesla Coil / Prism Tower: 28 ticks of charge before the bolt, and the
  // Prism pulls support beams out of every idle tower in range first.
  if (b.type === 'tesla' || b.type === 'prism') {
    if (b.charging > 0) {
      b.charging--;
      var ct = (b.chgT && !b.chgT.dead) ? b.chgT : t;
      if (!ct) { b.charging = 0; b.chgT = null; b.sup = 0; return; }
      if (b.charging <= 0) { b.chgT = null; fire(g, b, ct); }
      return;
    }
    if (t && b.cool <= 0) {
      b.charging = CHARGE_T; b.chgT = t; b.sup = 0;
      if (b.type === 'prism') prismSupport(g, b);
      if (!headless) sfx(b.type === 'tesla' ? 'charge' : 'prismup', b.cx, b.cy);
    }
    return;
  }
  if (t && b.cool <= 0) fire(g, b, t);
}
