// Iron Frontier — opts.js
// GENERATED by apps/games/rts/tools/modularize from rts.src.html + art/units/**.

'use strict';

// ===================================================================== //
//  Iron Frontier — an isometric skirmish RTS.
//
//  Everything below runs on a FIXED 60Hz step with a seeded PRNG and no
//  Math.random anywhere, so a given seed replays identically. That is not
//  neatness for its own sake: the AI balance harness (__rtsSim) runs whole
//  matches headless and asserts on the outcome, which is only meaningful
//  if the same seed produces the same match every time.
// ===================================================================== //

export var STEP = 1000 / 60;          // ms per simulation tick

// --------------------------------------------------------------------- //
//  Skirmish options — RA2's setup screen, in one object.
//
//  Every default here reproduces the match the game played before the
//  options existed (10 000 credits, three opening infantry, short game,
//  crates on, superweapons on, a Construction Yard), so an untouched strip
//  replays a seed exactly as it did before — rts.test.js asserts that
//  against a recorded three-minute sim.
//
//  `speed` is RA2's 1-6 slider. The simulation is a FIXED 60Hz tick and
//  nothing in it may depend on wall clock, so the slider cannot change the
//  tick — it changes how many ticks a second of wall clock buys: 15 x
//  speed, i.e. 15/30/45/60/75/90 per second, which on a 60Hz display is
//  0.25 .. 1.5 sim ticks per rendered frame with no interpolation at all.
//  Speed 4 is exactly the old 60/s, RA2's "Fast" and our default.
// --------------------------------------------------------------------- //
export var OPT_DEF = { credits: 10000, units: 3, short: true, crates: true,
                supers: true, speed: 4, bases: true, colour: 2, aiColour: 1 };

var OPT_CREDITS = [5000, 10000, 20000];

// RA2's eight multiplayer house colours. Index 2 (blue) and 1 (red) are the
// pair the game shipped with, so the default COL below is byte-identical.
export var HOUSE = [
  { k: 'gold',   name: 'Gold',   c: '#e0bf49' },
  { k: 'red',    name: 'Red',    c: '#e5646c' },
  { k: 'blue',   name: 'Blue',   c: '#4aa3db' },
  { k: 'green',  name: 'Green',  c: '#5ec468' },
  { k: 'orange', name: 'Orange', c: '#e0873a' },
  { k: 'teal',   name: 'Teal',   c: '#3ec3bf' },
  { k: 'purple', name: 'Purple', c: '#a56ada' },
  { k: 'pink',   name: 'Pink',   c: '#e879b5' }
];

// The AI never wears the player's colour. Blue and red stay each other's
// opposite so the classic pairing survives; any other pick puts the AI in
// red, or blue if the player took red.
export function aiHouse(h) { return h === 1 ? 2 : 1; }

export function normOpts(o) {
  var r = {}, k;
  for (k in OPT_DEF) r[k] = OPT_DEF[k];
  if (o) for (k in OPT_DEF) if (o[k] !== undefined && o[k] !== null) r[k] = o[k];
  r.credits = OPT_CREDITS.indexOf(r.credits) < 0 ? OPT_DEF.credits : r.credits;
  r.units = Math.max(0, Math.min(10, r.units | 0));
  r.speed = Math.max(1, Math.min(6, r.speed | 0));
  r.short = !!r.short; r.crates = !!r.crates; r.supers = !!r.supers; r.bases = !!r.bases;
  r.colour = HOUSE[r.colour] ? (r.colour | 0) : OPT_DEF.colour;
  r.aiColour = HOUSE[r.aiColour] ? (r.aiColour | 0) : aiHouse(r.colour);
  if (r.aiColour === r.colour) r.aiColour = aiHouse(r.colour);
  return r;
}
