// Iron Frontier — ore.js
// GENERATED by apps/games/rts/tools/modularize from rts.src.html + art/units/**.

import { aiVirtualPurifiers } from './ai.js';
import { aimTurret, faceOf, rotOf } from './bake/kit.js';
import { isHarv, isInfArmour, reachOf, ucap, uspd } from './combat-tables.js';
import { armourOf, dist, entX, entY, findTarget, fire } from './combat.js';
import { advance } from './move.js';
import { blocked, requestPath } from './path.js';
import { freeTileNear, hasBld } from './production.js';
import { UNITS } from './roster.js';
import { headless, idx, inMap } from './state.js';
import { sfx } from './ui/audio.js';
import { creditPop } from './ui/hud.js';
import { nextWaypoint } from './ui/input.js';
import { GEM_MULT, MAP, ME, T_GEM, T_GROUND, isAiSide, oreT } from './world.js';

// --------------------------------------------------------------------- //
//  Ore + harvesting
// --------------------------------------------------------------------- //
// `skip` maps "x,y" to the tick it was skipped at, so an entry expires
// instead of being a life sentence. A harvester that permanently blacklists
// its own map ends up idle with ore all around it.
var NOGO_TTL = 60 * 25;

export function findOre(g, fromX, fromY, maxR, skip, now) {
  var best = null, bd = 1e9;
  var r = maxR || 30;
  for (var y = Math.max(0, (fromY - r) | 0); y < Math.min(MAP, fromY + r); y++) {
    for (var x = Math.max(0, (fromX - r) | 0); x < Math.min(MAP, fromX + r); x++) {
      var i = idx(x, y);
      if (!oreT(g.terrain[i]) || g.ore[i] <= 1) continue;      // gems are ore, only richer
      if (skip) {
        var sk = skip[x + ',' + y];
        if (sk != null && (now == null || now - sk < NOGO_TTL)) continue;
      }
      var d = (x - fromX) * (x - fromX) + (y - fromY) * (y - fromY);
      if (d < bd) { bd = d; best = { x: x, y: y }; }
    }
  }
  return best;
}

export function findRefinery(g, p, fromX, fromY) {
  var best = null, bd = 1e9;
  for (var i = 0; i < g.blds.length; i++) {
    var b = g.blds[i];
    if (b.dead || b.p !== p || b.type !== 'refinery') continue;
    var d = (b.cx - fromX) * (b.cx - fromX) + (b.cy - fromY) * (b.cy - fromY);
    if (d < bd) { bd = d; best = b; }
  }
  return best;
}

// A refinery's centre tile is INSIDE the building, so it is impassable and
// a path aimed there comes back empty. The mining->toref hand-off already
// aimed at a tile below the footprint, but advance()'s 240-tick refresh
// re-aimed at the centre — so the first delivery or two worked off the good
// path and then the harvester wedged against the wall, full, for the rest of
// the match. That is the "mines for a few rounds then just stops" bug.
//
// THE FOOTPRINT, IN CELL INDICES. Everything below is measured off these
// bounds rather than off `round(cx) +- gw/2 + 1`, because b.cx and b.cy sit
// on a HALF cell whenever the span is even and that sum then rounds a whole
// tile the wrong way. For the 4x3 refinery at cy 6: the footprint is rows
// 5..7, the sprite draws its dock ramp on row 8, and `Math.round(cy + gh/2
// + 1)` is round(8.5) = 9 — a clear tile of grass BEYOND the ramp. The
// miner's destination was a field. MEASURED: refDock (7,9), footprint ends
// y=7, art's own comment says the dock tile is (cx, cy+2) = row 8.
function footBounds(b) {
  return { x0: Math.round(b.cx - b.gw / 2 + 0.5), x1: Math.round(b.cx + b.gw / 2 - 0.5),
           y0: Math.round(b.cy - b.gh / 2 + 0.5), y1: Math.round(b.cy + b.gh / 2 - 0.5) };
}

// THE DOCK APRON: the row of cells immediately outside the +gy face. Both
// refinery sprites draw their dock there and nowhere else — the Soviet pale
// ramp slab off the dished pit, the Allied hoist mouth under the drum — and
// the art file has always said so in its own words ("the dock tile centre is
// (cx - 64, baseY + 32)", i.e. two cells down the +gy face). It is where the
// miner is sent AND, since a player aims at the dock, what a click on the
// dock has to mean.
var DOCK_OUT = 1;                  // the door stands ONE clear cell off the footprint

function dockApron(b) {
  var f = footBounds(b), cells = [];
  for (var x = f.x0; x <= f.x1; x++) cells.push({ x: x, y: f.y1 + DOCK_OUT });
  return cells;
}

export function refDock(g, b) {
  var f = footBounds(b);
  var mx = Math.round((f.x0 + f.x1) / 2), my = Math.round((f.y0 + f.y1) / 2);
  // The drawn dock first (its centre, then either side of it), and only then
  // the other three faces — a blocked ramp is still better answered by the
  // back door than by standing in the road.
  var ring = [
    [mx, f.y1 + DOCK_OUT], [mx - 1, f.y1 + DOCK_OUT], [mx + 1, f.y1 + DOCK_OUT],
    [mx, f.y0 - DOCK_OUT], [f.x1 + DOCK_OUT, my], [f.x0 - DOCK_OUT, my]
  ];
  for (var i = 0; i < ring.length; i++) {
    var x = ring[i][0], y = ring[i][1];
    if (inMap(x, y) && !blocked(g, x, y)) return { x: x, y: y };
  }
  return { x: mx, y: f.y1 + DOCK_OUT };
}

// ARRIVAL IS DEFINED BY THE DOCK, NOT BESIDE IT.
//
// These were two independent constants and they were free to disagree: the
// dock sat 3.04 cells off a 4x3 refinery's centre against an arrival radius
// of max(gw,gh)/2 + 1.9 = 3.90, and nothing tied them together. MEASURED
// over sixteen approach bearings on a clear arena, every single delivery
// banked on a margin of 0.00 to 0.04 of a cell — the miner never reached its
// dock at all, it crossed the radius somewhere on the way and unloaded
// there. One extra cell of stand-off (a blocked approach, a second miner
// already on the ramp, a hull that noses in from the far side) and "docks"
// becomes "parks against the wall forever", which is the shape of every
// report this code has had.
//
// And the shape was wrong as well as the number: a footprint is a RECTANGLE
// and its ring of doors is a rectangular band, so testing a CIRCLE about the
// centre is both too tight at the corners and far too loose along the faces.
// On a 4x3 that circle reached 3.90 out along +x where the door is 2.5 —
// MEASURED, the War Miner banked its ore from (22.3,18.7), a cell and a half
// clear of the building, standing in the road. The player watches the hold
// empty into thin air.
//
// So arrival is the SAME BAND refDock draws its cells from, one cell clear of
// the footprint, plus the half cell a hull's centre sits off a cell centre.
// Every dock cell satisfies it by construction — |dx| there is gw/2 + 0.5
// against a bound of gw/2 + 1.5 — so "reached my dock" implies "docked" and
// the two can no longer drift. It is a band and not a point on purpose: a
// second miner nudged off the ramp by separation, or one pressed against the
// far wall, still docks instead of stalling forever with a full hold.
var DOCK_SLOP = 0.5;               // ...and a hull's centre sits up to half a cell off it

function atRefinery(u, b) {
  var f = footBounds(b);
  return u.x >= f.x0 - DOCK_OUT - DOCK_SLOP && u.x <= f.x1 + DOCK_OUT + DOCK_SLOP &&
         u.y >= f.y0 - DOCK_OUT - DOCK_SLOP && u.y <= f.y1 + DOCK_OUT + DOCK_SLOP;
}

// WHICH REFINERY A CLICK ON BARE GROUND MEANS.
//
// `pickAt` resolves a building from its FOUNDATION, which is right for
// selecting one and wrong for docking at one: the dock is drawn on the apron
// OUTSIDE the foundation, so the most obvious thing on the building to aim
// at — the ramp, the pit, the sign — picked nothing. The click fell through
// to a plain move, the miner drove to the kerb and parked there full, and
// the cursor said MOVE the entire time. Reported three times, the last of
// them naming the aim point: "clicking the docking sign has no effect ... the
// cursor is a moving cursor not a docking cursor".
//
// RA2 drives the harvester ONTO the refinery, which makes a dock affordance
// that is not part of the building doubly wrong. This is the input side of
// the same `dockApron` the sim aims at, so the art, the order and the cursor
// all read one definition. Deliberately NOT folded into pickAt: the apron is
// walkable ground that every other unit must still be able to be sent to,
// and force-fire must not treat it as a structure.
export function dockAt(g, p, gx, gy) {
  for (var i = 0; i < g.blds.length; i++) {
    var b = g.blds[i];
    if (b.dead || b.p !== p || b.type !== 'refinery') continue;
    var a = dockApron(b);
    for (var j = 0; j < a.length; j++) if (a[j].x === gx && a[j].y === gy) return b;
  }
  return null;
}

// [General] ChronoDelay=60 frames after a teleport, and
// ChronoHarvTooFarDistance=50 — a Chrono Miner that would have to warp
// further than that across the map drives home instead, so it stays on its
// own side rather than blinking across two bases and walking all the way back.
export var CHRONO_DELAY = 60 * 2, CHRONO_HARV_TOOFAR = 50;

// THE ONE WAY A HARVESTER IS SENT HOME. The automatic full-load return and
// the player's forced dock order both come through here, so a forced return
// is the same journey as an automatic one rather than a second, shabbier
// imitation of it.
//
// That mattered most for [CMIN] Teleporter=yes. The C&C wiki is explicit
// that a Chrono Miner warps home when it is full "or when explicitly
// ordered to dock", and rolls "back on their wheels" otherwise — so the
// warp belongs to BOTH callers. Before this, the forced path set 'toref'
// by hand and the Chrono Miner trundled all the way home on its wheels
// while the identical automatic return teleported. Same order, two
// completely different journeys, and the slow one reads as "my click did
// nothing" — which is exactly how this was reported, twice.
//
// `forced` marks the refinery as the PLAYER's choice, which the 'toref'
// escape below must not quietly overrule.
export function sendHome(g, u, ref, forced) {
  if (!ref || ref.dead) { u.state = 'idle'; u.forcedDock = false; return false; }
  var hd = UNITS[u.type];
  u.homeRef = ref; u.forcedDock = !!forced;
  // stallAt is the "has not got anywhere for fifteen seconds" clock. It is
  // last set when the harvester STARTS a trip, and 'mining' never touches
  // it, so a miner that has been chewing a seam for fifteen seconds arrives
  // in 'toref' already over the limit: the escape fired on the very first
  // tick and swapped the player's refinery for the nearest one. MEASURED —
  // a forced return with a stallAt age of 954 ticks retargeted after 1 tick
  // and unloaded at a refinery 24 cells from the one that was clicked.
  u.noProg = 0; u.stallAt = g.tick; u.bestD = 1e9;
  if (hd.chronoHome && dist(u, ref) <= CHRONO_HARV_TOOFAR) {
    // It does not drive home. It stands still for ChronoDelay and
    // then it is simply THERE — and drives back out normally.
    u.state = 'warp'; u.warpAt = g.tick + CHRONO_DELAY; u.path = null;
    if (!headless) sfx('charge');
  } else {
    var dk = refDock(g, ref);
    u.state = 'toref'; u.path = null; u.repathAt = -999;
    requestPath(g, u, dk.x, dk.y);
  }
  return true;
}

export function stepHarvester(g, u) {
  var d = UNITS[u.type];
  // [HARV] OpportunityFire=yes + Turret=yes: the War Miner keeps its 20mm
  // pointed at whatever wanders past, mining or not. The Chrono Miner has
  // Primary=none and simply never enters this branch.
  if (d.dmg > 0 && u.cool <= 0 && u.state !== 'warp') {
    var wt = findTarget(g, u, reachOf(d, u));      // [20mmRapidE] is Range 5.75, not 5.5
    // [HARVWH] is 100/80/70 against the three infantry armours and 50/20/20
    // against the three vehicle ones: a 20mm autocannon is for men and thin
    // skins, not for tanks. Restricting ACQUISITION to what the gun is for
    // is not a nerf, it is the difference between a miner that defends
    // itself and one that picks a fight with a Rhino, gets shot, and runs
    // for the refinery with a half-full hold — measured as the Collective
    // losing 6 of 6 soak matches to its own miners' opportunism.
    if (wt && !(isInfArmour(armourOf(wt)) || armourOf(wt) === 'light')) wt = null;
    if (wt) {
      var wax = entX(wt) - u.x, way = entY(wt) - u.y;
      u.aimAt = g.tick;
      if (aimTurret(u, faceOf(way, wax), rotOf(u.type))) fire(g, u, wt);
    }
  }
  // ---- the Chrono Miner's trip home ([CMIN] Teleporter=yes) ------------
  if (u.state === 'warp') {
    if (g.tick < u.warpAt) { u.path = null; return; }
    var wr = u.homeRef;
    if (!wr || wr.dead) { u.state = 'toref'; return; }
    var wd = refDock(g, wr), wsp = freeTileNear(g, wd.x, wd.y);
    if (!headless) g.fx.push({ x: u.x, y: u.y, t: 0, life: 24, chrono: true });
    if (wsp) { u.x = wsp.x; u.y = wsp.y; }
    u.path = null; u.pi = 0; u.repathAt = -999; u.noProg = 0; u.stallAt = g.tick;
    u.guardX = u.x; u.guardY = u.y; u.state = 'toref';
    if (!headless) { g.fx.push({ x: u.x, y: u.y, t: 0, life: 24, chrono: true }); sfx('click'); }
    return;
  }

  // A move order is the player talking; it beats auto-mining. The idle
  // branch below used to re-acquire a seam on the very next tick, so a
  // right-click on a mining harvester was silently ignored (it drove on to
  // the ore instead). On arrival it HOLDS for a while, like an RA2 miner
  // parked by hand, then goes back to work on its own.
  if (u.order && u.order.t === 'move') {
    if (u.deployed && isAiSide(g, u.p)) u.deployed = false; // AI packs up on a move; a human's deployed GI stays put until D
    var mdx = u.order.x - u.x, mdy = u.order.y - u.y;
    if (mdx * mdx + mdy * mdy < 1.4) {
      u.order = null; u.path = null; u.state = 'idle'; u.mineAt = null;
      u.guardX = u.x; u.guardY = u.y; u.holdUntil = g.tick + 60 * 20;
      nextWaypoint(g, u);
    } else if (!advance(g, u, u.order.x, u.order.y, uspd(u), 0) && !u.path &&
               u.noProg > 90) {                          // repathAt is refreshed every 8 ticks; noProg is the honest signal
      u.order = null; u.state = 'idle'; u.holdUntil = g.tick + 60 * 20;   // unreachable: stop here
    }
    return;
  }
  if (u.state === 'idle' && u.holdUntil > g.tick) return;

  if (u.state === 'idle' || (u.state === 'tomine' && !u.mineAt)) {
    var patch;
    if (u.order && u.order.t === 'harvest') patch = { x: u.order.x, y: u.order.y };
    else {
      // Every harvester used to take the NEAREST seam, so a whole fleet
      // converged on one tile. Separation then pushed them apart faster
      // than they could close the last tile: all of them sat beside the ore
      // in 'tomine' forever, never arriving, and never giving up either —
      // moveAlong still reports progress while a path exists, so noProg
      // stays 0 and the unreachable-seam escape never fires. Income simply
      // stopped. Claiming a seam is what stops the pile-up.
      var taken = {};
      for (var ti = 0; ti < g.units.length; ti++) {
        var o = g.units[ti];
        if (o !== u && !o.dead && o.p === u.p && isHarv(o) && o.mineAt)
          taken[o.mineAt.x + ',' + o.mineAt.y] = g.tick;
      }
      if (u.noGo) for (var nk in u.noGo) if (taken[nk] == null) taken[nk] = u.noGo[nk];
      patch = findOre(g, u.x, u.y, 0, taken, g.tick)
           || findOre(g, u.x, u.y, 0, u.noGo, g.tick);
    }
    if (!patch) {
      // Nothing left even ignoring our own blacklist: forget it and retry
      // next tick rather than sitting idle beside a field of ore.
      u.noGo = null; u.state = 'idle'; return;
    }
    u.mineAt = patch; u.state = 'tomine';
    u.noProg = 0; u.bestD = 1e9; u.stallAt = g.tick;
    requestPath(g, u, patch.x, patch.y);
    return;
  }

  if (u.state === 'tomine') {
    var m = u.mineAt;
    if (!oreT(g.terrain[idx(m.x, m.y)]) || g.ore[idx(m.x, m.y)] <= 1) {
      u.mineAt = null; u.state = 'idle'; u.order = null; return;
    }
    var ddx = u.x - m.x, ddy = u.y - m.y, d2 = ddx * ddx + ddy * ddy;
    // Radial, not per-axis: separation can hold a harvester 0.85 off the
    // seam on one axis indefinitely, and a per-axis test never passes.
    if (d2 < 1.44) {
      u.state = 'mining'; u.path = null; u.noProg = 0;
      u.face = faceOf(m.y - u.y, m.x - u.x); u.fsub = 0;
    }
    else if (d2 < (u.bestD == null ? 1e9 : u.bestD) - 0.01) {
      u.bestD = d2; u.stallAt = g.tick;                // still closing
      advance(g, u, m.x, m.y, uspd(u), 240);
    } else if (g.tick - (u.stallAt == null ? g.tick : u.stallAt) > 420) {
      // Has a route and is walking it, but has not got any closer for seven
      // seconds — contested seam. Step off it for a while and take another.
      (u.noGo || (u.noGo = {}))[m.x + ',' + m.y] = g.tick;
      u.mineAt = null; u.state = 'idle'; u.order = null;
      u.noProg = 0; u.bestD = 1e9; u.stallAt = g.tick;
    } else if (!advance(g, u, m.x, m.y, uspd(u), 240) && u.noProg > 45) {
      // No route to this seam — ore is walkable but the ground around it
      // may not be, so a patch can be visible and still unreachable. Without
      // this the harvester locks onto it and freezes for the rest of the
      // match: it re-targeted correctly, then never arrived and never
      // reconsidered. Blacklist it for THIS harvester and look elsewhere.
      (u.noGo || (u.noGo = {}))[m.x + ',' + m.y] = g.tick;
      u.mineAt = null; u.state = 'idle'; u.order = null;
      u.noProg = 0; u.bestD = 1e9; u.stallAt = g.tick;
    }
    return;
  }

  // Under fire, a harvester runs for the refinery instead of standing in
  // the open being farmed. It banks whatever it is carrying on the way,
  // which is also what makes harassing one worth the attacker's time.
  if (g.tick - u.fleeAt < 240 && (u.state === 'mining' || u.state === 'tomine')) {
    var safe = findRefinery(g, u.p, u.x, u.y);
    if (safe) {
      // Not routed through sendHome on purpose: a Chrono Miner that
      // teleported out of every ambush would be unkillable, and running for
      // cover is the harvester's own decision, so it cannot inherit — or
      // keep — the player's claim on a particular refinery.
      u.homeRef = safe; u.state = 'toref'; u.path = null; u.repathAt = -999; u.noProg = 0;
      u.forcedDock = false; u.stallAt = g.tick;
      return;
    }
  }

  if (u.state === 'mining') {
    var mi = idx(u.mineAt.x, u.mineAt.y);
    var take = Math.min(d.mine, g.ore[mi], ucap(g, u) - u.cargo);
    g.ore[mi] -= take; u.cargo += take;
    // cargo is VOLUME (it fills the same bin either way); cargoV is what
    // that volume is worth. RA2 prices a gem bail at 50 against ore's 25,
    // so a hold of gems cashes out at double without holding half as much.
    u.cargoV += take * (g.terrain[mi] === T_GEM ? GEM_MULT : 1);
    // Visible work: a puff of ore dust off the seam every third of a
    // second (render-only; skipped headless so balance runs stay identical).
    // 12 ticks is every FIFTH of a second at 60 fps, not a third — and with
    // several harvesters mining at once that is a lot of small motion in the
    // corner of the eye for no information. 20 ticks is what the line above
    // always said it was.
    if (!headless && (g.tick % 20) === 0) {
      var jx = ((g.tick / 20) % 3) - 1;
      g.fx.push({ x: u.mineAt.x + jx * 0.22, y: u.mineAt.y - jx * 0.18, t: 0, life: 30, size: 0, dust: true });
    }
    if (g.ore[mi] <= 0.5) { g.terrain[mi] = T_GROUND; g.ore[mi] = 0; u.mineAt = null; }
    if (u.cargo >= ucap(g, u) - 0.01 || !u.mineAt) {
      // [General] HarvesterTooFarDistance=5, and Seke's XWIS miner guide:
      // a full RA2 miner heads for the NEAREST refinery. It is not bound to
      // a parent refinery at build time — the stickiness players notice is
      // last-visited memory plus proximity.
      if (u.cargo > 20) sendHome(g, u, findRefinery(g, u.p, u.x, u.y), false);
      else u.state = 'idle';
    }
    return;
  }

  if (u.state === 'toref') {
    var ref2 = u.homeRef;
    if (!ref2 || ref2.dead) {
      // The refinery was shot out from under it. Take the nearest survivor;
      // with none left, go idle rather than hold a pointer to a dead
      // building (RA2Web: "harvesters should permanently halt when no
      // refineries remain"). A forced order cannot survive its own target,
      // so the player's claim on it lapses here too.
      sendHome(g, u, findRefinery(g, u.p, u.x, u.y), false);
      return;
    }
    if (atRefinery(u, ref2)) {
      // Ore Purifier: +25%.  [General] AIVirtualPurifiers=4,2,0 (hard,
      // medium, easy) gives a skirmish AI that many IMAGINARY purifiers at
      // 25% each — RA2's own economy handicap curve, so hard mines at 2x and
      // medium at 1.5x with no building to shoot. See docs/design-decisions.md.
      var _pur = (hasBld(g, u.p, 'purifier') ? 1 : 0) + aiVirtualPurifiers(g, u.p);
      var _got = Math.round(u.cargoV * (1 + 0.25 * _pur));
      g.side[u.p].credits += _got; g.side[u.p].harv += _got;
      // An EMPTY miner can be sent home by hand, so this branch now runs
      // with nothing in the hold. A floating "+0" over the refinery and a
      // cash register for no money are both wrong; the dump still plays,
      // because it did dock.
      if (u.p === ME && !headless && _got > 0) creditPop(Math.round(u.cargoV));
      u.cargo = 0; u.cargoV = 0; u.state = 'idle'; u.path = null; u.noProg = 0; u.stallAt = g.tick;
      // The order is DISCHARGED here, not abandoned: 'idle' falls into the
      // seam search on the next tick with no order set, which takes the
      // nearest ore. That is what RA2 does after a hand-sent return —
      // Seke: "the miner automatically goes and mines the closest ore" —
      // as against the default trip, which heads back out to the patch it
      // was working. The forced dock cleared u.order for exactly this.
      u.forcedDock = false; u.mineAt = null;
      sfx('dump', u.x, u.y);
      if (_got > 0) sfx('cash');       // no cash register for an empty hold
      return;
    }
    var dk = refDock(g, ref2);
    advance(g, u, dk.x, dk.y, uspd(u), 240);
    // Nothing in this branch used to be able to give up, so a harvester
    // that could not reach its dock simply stopped being part of the game.
    // Re-choosing the refinery re-runs the dock search against current
    // ground, which is what clears a blocked approach.
    if (u.noProg > 180 || g.tick - (u.stallAt || 0) > 900) {
      // A HAND-PICKED REFINERY IS NOT NEGOTIABLE. RA2 has one dock per
      // refinery ([GAREFN]/[NAREFN] NumberOfDocks=1) and a miner whose
      // refinery is busy WAITS for it — HarvesterTooFarDistance=5 exists
      // precisely to stop it bouncing off to a further one, and RA2Web
      // fixed the same thing ("should no longer try to dump ore to a far
      // away refinery while the closest one is temporarily blocked"). So
      // only an UNFORCED trip may re-choose; a forced one keeps its target
      // and merely re-runs its own approach, which is the half of this
      // branch that actually clears a blocked dock.
      var re = u.forcedDock ? ref2 : (findRefinery(g, u.p, u.x, u.y) || ref2);
      u.homeRef = re; u.path = null; u.repathAt = -999;
      u.noProg = 0; u.stallAt = g.tick;
    }
    return;
  }
}
