// Iron Frontier — roster.js
// GENERATED by apps/games/rts/tools/modularize from rts.src.html + art/units/**.

// fac: null = both sides can build it. Otherwise the faction that owns it.
//
// The asymmetry is deliberate and one-dimensional per side, so it is legible
// in a fight rather than just a stat sheet: the Directorate outranges and
// outruns you, the Collective outlasts and out-masses you.
export var UNITS = {
  // RA2 has TWO miners, not one hull in two colours: [CMIN] Chrono Miner
  // (Storage=20, no weapon, teleport locomotor, ChronoInSound) and [HARV]
  // War Miner (Storage=40, Turret=yes, Primary=20mmRapid). Same $1400 /
  // Str 1000 / Speed 4 / Sight 4 chassis, two completely different jobs:
  // the Directorate's skips the drive home, the Collective's shoots back.
  // `harv: true` is what every call site tests (isHarv), and the legacy
  // key 'harvester' still resolves through harvKey() so nothing that says
  // "a harvester" — the AI, orderUnitsTo, the tests — had to be rewritten.
  chronominer: { harv: true, chronoHome: true,
    name: 'Chrono Miner', em: '🚛', cost: 1400, build: 59, cls: 'v', fac: 'dir',
    hp: 1000, spd: 0.052, sight: 4, armour: 'medium', psiImmune: true, radImmune: true,
    dmg: 0, rate: 0, rng: 0, splash: 0, wh: null,
    cap: 500, mine: 0.42, w: 15, h: 12, desc: 'Mines ore; warps home to the refinery when full'
  },
  warminer: { harv: true, turret: true,
    name: 'War Miner', em: '🚛', cost: 1400, build: 59, cls: 'v', fac: 'col',
    hp: 1000, spd: 0.052, sight: 4, armour: 'medium', psiImmune: true, radImmune: true,
    dmg: 30, rate: 80, rng: 5.5, splash: 0, wh: 'HARVWH',   // [20mmRapid] 30 / ROF 20 / Range 5.5, HARVWH
    // [HARV] ElitePrimary=[20mmRapidE] (rules.ini:18055): 50 / ROF 50 /
    // Range 5.75 / [HowitzerWH]. The ROF gets WORSE — this is the one unit
    // in the roster whose elite weapon is slower, and it only comes out
    // ahead because [HARV]'s `VeteranAbilities` has no ROF (rofAt 2), so
    // the x0.6 arrives with the new gun rather than before it.
    rofAt: 2,
    elite: { dmg: 50, rate: 200, rng: 5.75, wh: 'HowitzerWH' },
    cap: 1000, mine: 0.42, w: 15, h: 12, desc: 'Mines ore and shoots back with a 20mm gun'
  },
  rifle: {
    name: 'GI', em: '🔫', cost: 200, build: 8, cls: 'i', fac: 'dir',
    hp: 125, spd: 0.052, sight: 5, armour: 'none',
    dmg: 15, rate: 80, rng: 4, splash: 0,
    wh: 'SA', dep: { dmg: 15, rate: 60, rng: 5, wh: 'SSA', splash: 0 },   // deployed behind sandbags ([Para] 15 dmg, ROF 15, Range 5)
    elite: { dmg: 25 },   // [E1] ElitePrimary=[M60E] (rules.ini:18127): 15 -> 25, same ROF and range
    cap: 0, mine: 0, w: 9, h: 14, desc: 'Deploys behind sandbags for range and fire rate (D)'
  },
  conscript: {
    name: 'Conscript', em: '🎖️', cost: 100, build: 4, cls: 'i', fac: 'col',
    hp: 125, spd: 0.052, sight: 5, armour: 'flak',
    dmg: 15, rate: 100, rng: 4, splash: 0,
    wh: 'SA',
    elite: { dmg: 20, rng: 5 },   // [E2] ElitePrimary=[M1CarbineE] (rules.ini:17670): 15 -> 20, Range 4 -> 5
    cap: 0, mine: 0, w: 9, h: 14, desc: 'Cheapest body on the field'
  },
  rocket: {
    name: 'Guardian GI', em: '🚀', cost: 400, build: 17, cls: 'i', fac: 'dir',
    hp: 100, spd: 0.039, sight: 6, armour: 'none', aa: true, aaRng: 8,   // RA2 GGI: the missile is dual-purpose
    dmg: 15, rate: 80, rng: 4, splash: 0,
    // [GGI] Deployer=yes, DeployFire=yes — the missile only fires braced.
    depFire: true,
    wh: 'SA', w2: { dmg: 40, rate: 160, rng: 8, wh: 'GUARDWH', splash: 0, use: 'veh' },   // [MissileLauncher] ROF 40, Range 8
    cap: 0, mine: 0, w: 10, h: 14, desc: 'Rifle vs infantry, missile vs armour and aircraft'
  },
  flak: {
    // RA2 FLAKT. Flak bursts: strong on infantry and aircraft, weak on armour.
    name: 'Flak Trooper', em: '💥', cost: 300, build: 13, cls: 'i', fac: 'col', req: 'radar',
    hp: 100, spd: 0.052, sight: 5, armour: 'none', aa: true, aaRng: 8, flak: true,
    dmg: 20, rate: 80, rng: 5, splash: 1,
    aaW: { dmg: 20, rate: 100, rng: 8, aaRng: 8, splash: 0.6, wh: 'FlakGuyWH', aa: true, flak: true },   // [FlakGuyAAGun]
    wh: 'FlakTWH',
    // [FLAKT] ElitePrimary=[FlakGuyGunE] (rules.ini:17712): the only change
    // is Burst=2. (Its AA barrel doubles too, but through `EliteSecondary=
    // FlakGuyAAGunE`, which is deliberately out of scope here.)
    elite: { burst: 2 },
    cap: 0, mine: 0, w: 10, h: 14, desc: 'Flak gun, anti-infantry and anti-air'
  },
  rocketeer: {
    // RA2 JUMPJET. Flying infantry: air:true ignores terrain, only AA can hit it.
    name: 'Rocketeer', em: '🪂', cost: 600, build: 25, cls: 'i', fac: 'dir', req: 'airforce',
    hp: 125, spd: 0.117, sight: 8, armour: 'none', air: true, alt: 36, aa: true, aaRng: 5,
    shadow: [9, 4],
    dmg: 25, rate: 120, rng: 5, splash: 0,
    wh: 'SSA',
    elite: { rate: 20 },   // [JUMPJET] ElitePrimary=[20mmE] (rules.ini:17773): ROF 30 -> 5, nothing else
    cap: 0, mine: 0, w: 10, h: 16, desc: 'Jetpack trooper, machine gun; hovers, needs Airforce Command'
  },
  harrier: {
    // RA2 ORCA. Aircraft lane: lives on an Airforce Command pad (4 per HQ),
    // flies out with `ammo` missiles, fires them all, returns to reload.
    name: 'Harrier', em: '✈️', cost: 1200, build: 50, cls: 'a', fac: 'dir', req: 'airforce',
    // [General] ReloadRate=.3 — MINUTES to reload each ammo point, so 18 s
    // (1080 ticks), not the 150 that made a sortie cost 2.5 s on the pad.
    hp: 150, spd: 0.182, sight: 8, armour: 'light', air: true, alt: 46, ammo: 2, reload: 1080,
    shadow: [17, 7],
    dmg: 150, rate: 40, rng: 6, splash: 0.4,   // [Maverick] Range=6
    // [Maverick] is `Burst=2` and [ORCA] is `Ammo=1`: ONE trigger pull, two
    // missiles. Ours splits that into `ammo: 2` instead, because our fire
    // path draws one projectile per pull and two missiles per sortie is the
    // truer picture; the payload is the same 300. So the Burst here lives in
    // `ammo`, not in `dmg` — this is the roster's one weapon that expresses
    // Burst any other way, and it is recorded rather than silently folded.
    // [ORCA] ElitePrimary=[MaverickE] (rules.ini:17899) is 300 / Burst 4 /
    // Range 9, i.e. that same pair doubled again — which is what `burst: 2`
    // on top of our two shots buys: 2 x 2 x 300 = 1200, RA2's 1 x 4 x 300.
    rofAt: 2,          // [ORCA] VeteranAbilities has no ROF; EliteAbilities does
    elite: { dmg: 300, burst: 2, rng: 9 },
    wh: 'ORCAAP',
    cap: 0, mine: 0, w: 26, h: 16, desc: 'Jet, two Maverick missiles per sortie; ground only'
  },
  kirov: {
    // RA2 ZEP. Slow, enormous, drops bombs on whatever is under it. No AA.
    name: 'Kirov Airship', em: '🎈', cost: 2000, build: 84, cls: 'v', fac: 'col', req: 'lab',
    hp: 2000, spd: 0.065, sight: 8, armour: 'light', air: true, alt: 60, bomb: true,
    shadow: [30, 12],
    dmg: 250, rate: 200, rng: 1.0, splash: 2,
    // [ZEP] ElitePrimary=[BlimpBombE] (rules.ini:17875) changes exactly one
    // field: Warhead [BlimpHE] -> [KTSTLEXP]. Those two Verses rows are
    // byte-identical in rules.ini (:19315 vs the [BlimpHE] row), as are
    // CellSpread=2 and InfDeath=2 — the elite Kirov's bomb differs only in
    // which explosion art plays. Recorded as a SUBSTITUTION (KTSTLEXP ==
    // BlimpHE) rather than carried as a duplicate warhead nothing reads.
    rofAt: 2,          // [ZEP] VeteranAbilities has no ROF; EliteAbilities does
    wh: 'BlimpHE',
    cap: 0, mine: 0, w: 46, h: 22, desc: 'Bomber airship, huge and slow; needs a Battle Lab'
  },
  lancer: {
    name: 'Grizzly Tank', em: '🛡️', cost: 700, build: 29, cls: 'v', fac: 'dir', turret: true,
    hp: 300, spd: 0.091, sight: 8, armour: 'heavy',
    dmg: 65, rate: 240, rng: 5, splash: 0.3,
    wh: 'AP',
    // [MTNK] ElitePrimary=[105mmE] (rules.ini:17735): 55 / ROF 75 / Burst 2
    // / [GRIZAPE]. Damage DOWN and ROF SLOWER — the gain is the second
    // shell and a warhead that stops treating infantry as 25%.
    rofAt: 2,          // [MTNK] VeteranAbilities has no ROF; EliteAbilities does
    elite: { dmg: 55, burst: 2, rate: 300, wh: 'GRIZAPE' },
    cap: 0, mine: 0, w: 19, h: 15, desc: 'Fast, long reach, thin skin'
  },
  mammoth: {
    // 950/18 made the Collective's one factory a bottleneck a Lancer's
    // 650/12 never hit, and the extra factory the AI now builds multiplied
    // that gap instead of closing it (hard went 73% -> 90% Directorate).
    // 880/15 evens throughput per factory: measured 56% / 56% across
    // normal and hard, from 90% / 73%.
    name: 'Apocalypse', em: '⚙️', cost: 1750, build: 74, cls: 'v', fac: 'col', req: 'lab', turret: true,
    // 0.028 read fine on paper ("slow, heavy") and lost the faction the
    // game: below infantry speed (0.050) a Collective army arrives strung
    // out, fights piecemeal and can never disengage — measured 88% losses
    // for the side fielding it. 0.036 is still the slowest thing on the
    // field and still 0.73x a Lancer (about the RA2 Apocalypse/Grizzly
    // ratio); it just lets the army arrive together. Single biggest lever
    // in the whole table — see docs/design-decisions.md.
    hp: 800, spd: 0.052, sight: 6, armour: 'heavy', aa: true, aaRng: 8,
    // [120mmx] is Damage=100 with Burst=2. That was folded into `dmg: 200`;
    // it is now spelled the one way the roster spells Burst, because
    // [120mmxE] takes the Burst to FOUR and a pre-multiplied 200 has
    // nowhere to put that. dmg x burst is unchanged.
    dmg: 100, burst: 2, rate: 320, rng: 5.75, splash: 0.3,
    wh: 'ApocAP',
    // [APOC] ElitePrimary=[120mmxE] (rules.ini:17748): Burst 2 -> 4 and
    // [ApocAP] -> [ApocAPE], which opens the infantry rows from 25% to 100%.
    elite: { burst: 4, wh: 'ApocAPE' },
    // MammothTusk: the twin AA missile pack on the Apocalypse's hull, so it
    // is not helpless under a Harrier the way it was here.
    aaW: { dmg: 50, burst: 2, rate: 320, rng: 8, aaRng: 8, splash: 0.2, wh: 'HE', aa: true },   // [MammothTusk] 50 x Burst 2, ROF 80, Range 8
    cap: 0, mine: 0, w: 22, h: 17, desc: 'Slow, heavy, wide splash'
  },
  // ---- RA2 roster, phase B. Tier gating via `req` (any of), like structures.
  engineer: {
    name: 'Engineer', em: '🔧', cost: 500, build: 21, cls: 'i', fac: null, capture: true,
    hp: 75, spd: 0.052, sight: 4, armour: 'none',
    dmg: 0, rate: 0, rng: 0, splash: 0,
    wh: null,
    cap: 0, mine: 0, w: 9, h: 14, desc: 'Captures an enemy structure (consumed)'
  },
  // [ADOG]/[DOG]: the same animal on both sides ($200, Str 100, Speed 8,
  // Sight 9, Armor none, Prerequisite=Barracks, TechLevel 2). Its weapon is
  // [GoodTeeth]/[BadTeeth] — 30 damage, ROF 30, Range 1.5 — but the warhead
  // is [ParasiteDog], which is `Parasite=yes`: the leap does not wound a man,
  // it removes him. Against anything that is not a man the Verses row is all
  // zeroes, so a dog is literally incapable of scratching a tank.
  // `DetectDisguise=yes` makes it the only thing on the field that sees a
  // Mirage Tank for what it is.
  dog: {
    name: 'Attack Dog', em: '🐕', cost: 200, build: 8, cls: 'i', fac: null, req: 'barracks',
    hp: 100, spd: 0.104, sight: 9, armour: 'none', dog: true, detect: true,
    dmg: 30, rate: 120, rng: 1.5, splash: 0,
    wh: 'ParasiteDog',
    cap: 0, mine: 0, w: 13, h: 10, desc: 'Leaps on infantry and kills outright; sees through a Mirage'
  },
  ifv: {
    // [FV] Passengers=1, Gunner=yes, TurretCount=4, WeaponCount=13: the IFV
    // is a TRANSPORT whose weapon and turret are chosen by whoever is
    // riding in it (`IFVMode=` on the infantryman). Empty it is the rocket
    // pod — [HoverMissile] 25 x Burst 2 / ROF 50 / Range 6 / HE, MinimumRange=1.
    name: 'IFV', em: '🚙', cost: 600, build: 25, cls: 'v', fac: 'dir', turret: true,
    hp: 200, spd: 0.130, sight: 8, armour: 'light', aa: true, aaRng: 6,
    pax: 1, paxInf: true, ifv: true,
    // [HoverMissile] is Damage=25 with Burst=2, which used to be folded into
    // `dmg: 50`. Spelled out, because [HoverMissileE] is 80 x Burst 4 and a
    // pre-multiplied number cannot express either half. dmg x burst is
    // unchanged at 50.
    dmg: 25, burst: 2, rate: 200, rng: 6, minRng: 1, splash: 0.5,
    wh: 'HE',
    // [FV] ElitePrimary=[HoverMissileE] (rules.ini:17991). This is the
    // EMPTY IFV's rocket pod only: with a passenger aboard the weapon comes
    // from the man riding in it (`IFVMode=`), and his elite weapon is his
    // own — a separate table, not this one.
    rofAt: 2,          // [FV] VeteranAbilities has no ROF; EliteAbilities does
    elite: { dmg: 80, burst: 4 },
    cap: 0, mine: 0, w: 15, h: 12, desc: 'Fast rocket buggy; its gun changes with the infantryman riding in it'
  },
  mirage: {
    name: 'Mirage Tank', em: '🌳', cost: 1000, build: 42, cls: 'v', fac: 'dir', req: 'lab',
    hp: 200, spd: 0.091, sight: 9, armour: 'light',
    dmg: 100, rate: 280, rng: 7, splash: 0,
    wh: 'MirageWH',
    rofAt: 2,          // [MGTK] VeteranAbilities has no ROF; EliteAbilities does
    cap: 0, mine: 0, w: 18, h: 14, desc: 'Ambusher, shreds infantry; needs a Battle Lab'
  },
  tanya: {
    name: 'Tanya', em: '💃', cost: 1000, build: 42, cls: 'i', fac: 'dir', req: 'lab', max: 1,
    hp: 125, spd: 0.065, sight: 8, armour: 'flak',
    dmg: 125, rate: 40, rng: 6, splash: 0,
    wh: 'HollowPoint', w2: { dmg: 2500, rate: 400, rng: 1.2, wh: 'Super', splash: 0, use: 'bld' },   // [Sapper] ROF 100
    // [TANY] ElitePrimary=[DoublePistolsE] (rules.ini:18091): Range 6 -> 8
    // and nothing else. Elite Tanya does not hit harder, she opens first.
    elite: { rng: 8 },
    cap: 0, mine: 0, w: 9, h: 14, desc: 'Hero: kills infantry outright, C4s buildings; one only'
  },
  rhino: {
    name: 'Rhino Tank', em: '🦏', cost: 900, build: 38, cls: 'v', fac: 'col', turret: true,
    hp: 400, spd: 0.078, sight: 8, armour: 'heavy',
    dmg: 90, rate: 260, rng: 5.75, splash: 0.3,
    wh: 'AP',
    // [HTNK] ElitePrimary=[120mmE] (rules.ini:17761): 85 / ROF 80 / Burst 2
    // / [RHINAPE]. Read without Burst this is a NERF (90 -> 85, ROF 65 ->
    // 80); with it, two 85s in the time one 90 took.
    rofAt: 2,          // [HTNK] VeteranAbilities has no ROF; EliteAbilities does
    elite: { dmg: 85, burst: 2, rate: 320, wh: 'RHINAPE' },
    cap: 0, mine: 0, w: 20, h: 15, desc: 'Heavy main battle tank'
  },
  flaktrack: {
    name: 'Flak Track', em: '🛻', cost: 500, build: 21, cls: 'v', fac: 'col', turret: true,
    hp: 180, spd: 0.104, sight: 8, armour: 'heavy', aa: true, aaRng: 10, flak: true,
    dmg: 25, rate: 160, rng: 5, splash: 1,
    wh: 'FlakTWH',
    // FlakTWH (25) is the anti-ground burst; the AA barrel fires FlakWH (35).
    aaW: { dmg: 35, rate: 100, rng: 10, aaRng: 10, splash: 0.6, wh: 'FlakWH', aa: true, flak: true },   // [FlakTrackAAGun] Range=10
    rofAt: 2,          // [HTK] VeteranAbilities has no ROF; EliteAbilities does
    elite: { burst: 2 },   // [HTK] ElitePrimary=[FlakTrackGunE] (rules.ini:17701): Burst=2, nothing else
    pax: 5, paxInf: true,                                             // [HTK] Passengers=5
    cap: 0, mine: 0, w: 16, h: 12, desc: 'Fast flak halftrack, anti-infantry; carries five men'
  },
  v3: {
    name: 'V3 Launcher', em: '🚀', cost: 800, build: 34, cls: 'v', fac: 'col', req: 'radar',
    hp: 150, spd: 0.052, sight: 7, armour: 'light',
    dmg: 200, rate: 600, rng: 18, minRng: 5, splash: 1,   // [V3Launcher] MinimumRange=5
    wh: 'HE',
    cap: 0, mine: 0, w: 18, h: 14, desc: 'Long-range rocket artillery; needs Radar'
  },
  teslatrooper: {
    // [SHK] Shock Trooper. Beyond its own bolt it is the thing that keeps a
    // Tesla Coil alive: RA2 lets up to three of them charge one coil, which
    // fires without power and swaps [TeslaZap] for [OPCoilBolt] (300 dmg).
    coiler: true,
    name: 'Tesla Trooper', em: '⚡', cost: 500, build: 21, cls: 'i', fac: 'col',
    hp: 130, spd: 0.052, sight: 6, armour: 'plate',
    dmg: 50, rate: 240, rng: 3, splash: 0,
    wh: 'Shock',
    // [SHK] ElitePrimary=[ElectricBoltE] (rules.ini:17807): ROF 60 -> 40 and
    // Range 3 -> 5. Same damage; it reaches out and it fires oftener.
    elite: { rate: 160, rng: 5 },
    cap: 0, mine: 0, w: 10, h: 15, desc: 'Armoured, zaps tanks'
  },
  ivan: {
    // [IVAN] Primary=[IvanBomber] FireOnce / Range 1.5 / Warhead=[IvanBomb]
    // (IvanBomb=yes — it PLACES, it does not hurt); the blast is [IvanWH],
    // 400 damage, CellSpread 1.5. AttackCursorOnFriendlies=yes, so a bomb
    // can go on your own tank and walk it into their base.
    ivan: true,
    name: 'Crazy Ivan', em: '🧨', cost: 600, build: 25, cls: 'i', fac: 'col', req: 'radar',
    hp: 125, spd: 0.052, sight: 6, armour: 'none',
    dmg: 400, rate: 200, rng: 1.5, splash: 1,
    wh: 'IvanBomb',
    // [IVAN] ElitePrimary=[IvanBomberE] (rules.ini:17942): 400 -> 600. An
    // IvanBomb=yes warhead PLACES the charge instead of dealing damage, so
    // this number is carried on the bomb (plantBomb) and spent when the
    // fuse runs out, not at the moment of firing.
    elite: { dmg: 600 },
    cap: 0, mine: 0, w: 9, h: 14, desc: 'Plants bombs point-blank; needs Radar'
  },
  drone: {
    // [DRON] Primary=[DroneJump] 50 / ROF 60 / Range 1.83, Projectile=JUMP,
    // LimboLaunch=yes, Warhead=[Parasite] Parasite=yes: the drone does not
    // shoot a vehicle, it CLIMBS INSIDE and is removed from the map.
    parasite: true, psiImmune: true, radImmune: true,
    name: 'Terror Drone', em: '🕷️', cost: 500, build: 21, cls: 'v', fac: 'col',
    // [DRON] Armor=special_1 — rules.ini's own comment calls it "a unit with
    // infantry vulnerabilities". As `light` it took 50% from small arms and
    // 60% from the heavier infantry gun, i.e. riflemen could barely hurt the
    // one thing RA2 designed them to answer.
    hp: 100, spd: 0.130, sight: 4, armour: 'special_1',
    dmg: 50, rate: 240, rng: 1.83, splash: 0,
    wh: 'Parasite',
    cap: 0, mine: 0, w: 10, h: 9, desc: 'Fast, tears vehicles apart up close'
  },
  teslatank: {
    name: 'Tesla Tank', em: '🔋', cost: 1200, build: 50, cls: 'v', fac: 'col', req: 'radar',   // [TTNK] Prerequisite=NAWEAP,NARADR
    hp: 300, spd: 0.078, sight: 8, armour: 'heavy',
    dmg: 135, rate: 300, rng: 4, splash: 0,
    wh: 'Electric',
    // [TTNK] ElitePrimary=[TankBoltE] (rules.ini:17796): 150 / ROF 60 /
    // Range 6 — the only elite weapon that improves all three at once.
    rofAt: 2,          // [TTNK] VeteranAbilities has no ROF; EliteAbilities does
    elite: { dmg: 150, rate: 240, rng: 6 },
    cap: 0, mine: 0, w: 18, h: 14, desc: 'Tesla cannon on tracks; needs a Radar Tower'
  },
  prismtank: {
    // RA2 PTNK: Cost 1200, Strength 150, Armor light, Speed 6, Sight 8,
    // weapon Comet — 100 damage, ROF 60, Range 8, PrismWarhead, no splash,
    // prerequisite Battle Lab. It out-ranges every tank on the field and
    // pays for it in paper armour.
    name: 'Prism Tank', em: '🔆', cost: 1200, build: 50, cls: 'v', fac: 'dir', req: 'lab', turret: true,
    hp: 150, spd: 0.052, sight: 8, armour: 'light',
    dmg: 100, rate: 400, rng: 10, splash: 0,
    wh: 'CometWH',   // [Comet]: 100 dmg, ROF 100, Range 10, Speed 4 — RA2's siege tank, not an infantry gun
    rofAt: 2,          // [SREF] VeteranAbilities has no ROF; EliteAbilities does
    cap: 0, mine: 0, w: 15, h: 12, desc: 'Long-range prism beam, siege armour; needs a Battle Lab'
  },
  // ---- RA2 roster, phase C: the special infantry ----------------------
  // [DESO] Desolater: $600, Str 150, Armor plate, TechLevel 8, Sight 6,
  // Prerequisite=NAHAND,RADAR, SelfHealing=yes, ImmuneToRadiation=yes.
  // Primary [RadBeamWeapon] 125 / ROF 50 / Range 6 / RadBeamWarhead;
  // Secondary [RadEruptionWeapon] AreaFire, RadLevel=500 — the deploy.
  desolator: {
    name: 'Desolator', em: '☢️', cost: 600, build: 25, cls: 'i', fac: 'col',
    reqAll: ['barracks', 'radar'], selfHeal: true, radImmune: true, deployRad: true,
    hp: 150, spd: 0.052, sight: 6, armour: 'plate',
    dmg: 125, rate: 200, rng: 6, splash: 0,
    wh: 'RadBeamWH',
    // [DESO] ElitePrimary=[RadBeamWeaponE] (rules.ini:17953): 200 / Range 8.
    elite: { dmg: 200, rng: 8 },
    cap: 0, mine: 0, w: 10, h: 15, desc: 'Radiation beam; deploys (D) to flood the ground with radiation'
  },
  // [YURI] $1200, Str 100, Sight 12, Primary=[MindControl] 10 / ROF 200 /
  // Range 7 / Warhead=Controller (MindControl=yes), Prerequisite=NAHAND,
  // NATECH, TechLevel 10, ImmuneToPsionics=yes.
  yuri: {
    name: 'Yuri', em: '🧠', cost: 1200, build: 50, cls: 'i', fac: 'col',
    reqAll: ['barracks', 'lab'], psiImmune: true, mind: true,
    hp: 100, spd: 0.052, sight: 12, armour: 'none',
    dmg: 10, rate: 800, rng: 7, splash: 0,
    wh: 'Controller',
    cap: 0, mine: 0, w: 9, h: 14, desc: 'Takes permanent control of one enemy unit; needs a Battle Lab'
  },
  // [CLEG] Chrono Legionnaire: $1500, Str 125, Speed 5, Armor none,
  // TechLevel 10, Prerequisite=GAPILE,TECH, teleport locomotor.
  // [NeutronRifle] 8 / ROF 120 / Range 5 / Warhead=[ChronoBeam] Temporal=yes.
  cleg: {
    name: 'Chrono Legionnaire', em: '⏳', cost: 1500, build: 63, cls: 'i', fac: 'dir',
    reqAll: ['barracks', 'lab'], teleport: true, temporal: true,
    hp: 125, spd: 0.065, sight: 8, armour: 'none',
    dmg: 8, rate: 480, rng: 5, splash: 0,
    wh: 'ChronoBeam',
    // [CLEG] ElitePrimary=[NeutronRifleE] (rules.ini:17889): Damage 8 -> 16.
    // A Temporal=yes weapon never deals that damage — it sets how fast the
    // victim is erased, which is why stepEraseList divides by it.
    elite: { dmg: 16 },
    cap: 0, mine: 0, w: 10, h: 15, desc: 'Warps instead of walking; erases what it shoots instead of damaging it'
  },
  // [SPY] $1000, Str 100, Armor flak, Speed 4, Sight 9, Agent=yes,
  // Infiltrate=yes, CanDisguise + PermaDisguise, Primary=[MakeupKit]
  // (Warhead [Snapshot] MakesDisguise=yes), CanPassiveAquire=no.
  spy: {
    name: 'Spy', em: '🕵️', cost: 1000, build: 42, cls: 'i', fac: 'dir',
    reqAll: ['barracks', 'lab'], spy: true, infil: true,
    hp: 100, spd: 0.052, sight: 9, armour: 'flak',
    dmg: 0, rate: 0, rng: 0, splash: 0, wh: null,
    cap: 0, mine: 0, w: 9, h: 14, desc: 'Disguised; infiltrates an enemy structure (consumed). Dogs see through it'
  },
  // ---- RA2 roster, phase 8: the transports ----------------------------
  // [SHAD] BlackHawk Transport. Cost 1000, Strength 175, Armor light,
  // Speed 14, Sight 7, TechLevel 7, JumpJet locomotor, Landable=yes,
  // RadarInvisible=yes, Passengers=5, ThreatPosed=0, CanPassiveAquire=no,
  // Primary=[BlackHawkCannon] 35 / ROF 40 / Range 6 / Warhead SA.
  // Prerequisite=GAWEAP — the `;Prerequisite=GAHPAD` line above it is
  // commented out in rules.ini, so the War Factory is the whole gate.
  // It carries no `ammo`, so it never joins the Airforce Command's pad
  // cycle: it lands on any clear cell to load and unload, as RA2's does.
  nighthawk: {
    name: 'Nighthawk', em: '🚁', cost: 1000, build: 42, cls: 'v', fac: 'dir',
    hp: 175, spd: 0.182, sight: 7, armour: 'light', air: true, alt: 40,
    pax: 5, paxInf: true, passive: true, shadow: [16, 7],
    dmg: 35, rate: 160, rng: 6, splash: 0,
    wh: 'SA',
    // [SHAD] ElitePrimary=[BlackHawkCannonE] (rules.ini:17931): 40 and
    // [SA] -> [SSA], the harder small-arms row we already carry.
    rofAt: 2,          // [SHAD] VeteranAbilities has no ROF; EliteAbilities does
    elite: { dmg: 40, wh: 'SSA' },
    cap: 0, mine: 0, w: 20, h: 14, desc: 'Carries five infantry; lands on any clear ground to load and unload (D)'
  },
  // [SAPC] Armored Transport. Cost 900, Strength 300, Armor heavy, Speed 6,
  // Sight 6, TechLevel 2, Passengers=12, Crusher=yes, Turret=no, no weapon.
  // Prerequisite=NAYARD: there is no Shipyard yet, so for now it is built at
  // the War Factory and only drives — the hovercraft's water half lands with
  // the navy (roadmap Phase 8).
  apc: {
    // [SAPC] `Naval=yes`, `Prerequisite=NAYARD`. Until the navy landed this
    // was a land-only halftrack with nothing to point its prerequisite at;
    // it now floats (MovementZone=Amphibious) and is built at the Soviet
    // Shipyard, which is what rules.ini has always said it was.
    name: 'Amphibious Transport', em: '🚤', cost: 900, build: 38, cls: 'v', fac: 'col',
    nav: 1, amph: 1, req: 'shipyard',
    hp: 300, spd: 0.078, sight: 6, armour: 'heavy',
    pax: 12, paxInf: true, paxVeh: true, paxHarv: true, passive: true,
    dmg: 0, rate: 0, rng: 0, splash: 0, wh: null,
    cap: 0, mine: 0, w: 22, h: 15, desc: 'Carries twelve — infantry or light vehicles; unload with D'
  },
  // ===================================================================
  //  The navy. `nav: 1` is SpeedType=Float / MovementZone=Water (the hull
  //  lives on water and cannot leave it); `amph: 1` is the amphibious pair
  //  that crosses both. `sub: 1` is `Underwater=yes`, `sensors: 1` is
  //  `Sensors=yes` / SensorsSight=4 — the only thing that sees a submerged
  //  hull. `landTgt: false` is rules.ini `LandTargeting=1` (this weapon
  //  cannot be aimed at anything ashore); `navTgt: 'sub'` is the
  //  `NavalTargeting` family that ONLY reaches what is under the water.
  //  Every ROF below is rules.ini's x4, the conversion the whole roster
  //  uses (RA2 runs at 15 fps, we tick at 60).
  // ===================================================================
  destroyer: {
    // [DEST] $1000 / Str 600 / heavy / Speed 6 / Sight 7. Primary [155mm]
    // 60 / ROF 110 / Range 8 / ARTYHE. Secondary [ASWLauncher] launches an
    // Osprey ([ASW]) that drops [ASWBomb] 50 / APSplash on a submarine —
    // modelled here as an auto-launched short-range depth-charge attack
    // rather than a second airframe, because the helicopter never takes an
    // order of its own in RA2 either.
    name: 'Destroyer', em: '🚢', cost: 1000, build: 42, cls: 'n', fac: 'dir', nav: 1,
    hp: 600, spd: 0.078, sight: 7, armour: 'heavy',
    dmg: 60, rate: 440, rng: 8, splash: 0.5, wh: 'ARTYHE',
    elite: { burst: 2 },   // [DEST] ElitePrimary=[155mmE] (rules.ini:17783): Burst=2, nothing else
    asw: { dmg: 50, rate: 600, rng: 6, wh: 'APSplash', splash: 0.5 },
    cap: 0, mine: 0, w: 30, h: 16, desc: 'Naval gun; its Osprey hunts submarines by itself'
  },
  aegis: {
    // [AEGIS] $1200 / Str 800 / light / Speed 4 / Sight 8, Prerequisite
    // GAYARD,GARADR. [Medusa] 100 / ROF 15 / Range 12 / SAMWH, and
    // LandTargeting=1 with NavalTargeting=6: it is an anti-air battery and
    // nothing else — it cannot be aimed at a hull or at the shore.
    // GARADR is the AIRFORCE COMMAND: the Directorate has no `radar`
    // building at all (`radar` is `fac: 'col'`), so a bare `req: 'radar'`
    // here made the Aegis unbuildable for the only house that owns it —
    // and aiTeamPass refuses any task force with an unbuildable member, so
    // it took the WHOLE Allied offensive navy down with it. `lab` spells
    // the same "either house's radar" the same way.
    name: 'Aegis Cruiser', em: '🛰️', cost: 1200, build: 50, cls: 'n', fac: 'dir', nav: 1, req: ['airforce', 'radar'],
    hp: 800, spd: 0.052, sight: 8, armour: 'light', aa: true, aaRng: 12, ag: false,
    dmg: 100, rate: 60, rng: 12, splash: 0.3, wh: 'SAMWH',
    // [AEGIS] ElitePrimary=[MedusaE] (rules.ini:18079): ROF 15 -> 5, Range
    // 12 -> 14, Burst=2. The single largest elite jump in the roster — a
    // 12x rate of fire. `aaRng` moves with `rng` because the Aegis has no
    // separate AA weapon: its primary IS the missile, and rngVs reads
    // aaRng when the target flies.
    elite: { rate: 20, rng: 14, aaRng: 14, burst: 2 },
    cap: 0, mine: 0, w: 30, h: 16, desc: 'Anti-air only: a 12-cell missile umbrella over the fleet'
  },
  carrier: {
    // [CARRIER] $2000 / Str 800 / heavy / Speed 4, Prerequisite GAYARD+TECH.
    // Spawns=HORNET, SpawnsNumber=3, SpawnReloadRate=150; [HornetLauncher]
    // Range=25 is the standoff, and the damage is the Hornets' own
    // [HornetBomb] 40 / ORCAAP. CanPassiveAquire=no — it never picks its
    // own target, you give it one.
    name: 'Aircraft Carrier', em: '🛳️', cost: 2000, build: 84, cls: 'n', fac: 'dir', nav: 1, req: 'lab',
    hp: 800, spd: 0.052, sight: 7, armour: 'heavy', passive: true,
    spawns: 'hornet', spawnN: 3, spawnReload: 150,
    dmg: 1, rate: 600, rng: 25, splash: 0, wh: 'ORCAAP',
    cap: 0, mine: 0, w: 38, h: 18, desc: 'Launches three Hornets at a target up to 25 cells away'
  },
  hornet: {
    // [HORNET] Str 75 / light / Speed 12 / Ammo 1, Spawned=yes, TechLevel -1
    // — it is never on a build list, it comes off the deck.
    name: 'Hornet', em: '🛩️', cost: 50, build: 2, cls: 'a', fac: 'dir', spawned: true,
    hp: 75, spd: 0.156, sight: 2, armour: 'light', air: true, alt: 40, ammo: 1, reload: 1080,   // [General] ReloadRate=.3 minutes
    shadow: [13, 6],
    dmg: 40, rate: 12, rng: 5, splash: 0.3, wh: 'ORCAAP',
    // [HORNET] ElitePrimary=[HornetBombE] (rules.ini:17919): 80 and
    // [ORCAAP] -> [ARTYHE]. Its ability lists are the shortest in the file
    // — `STRONGER,FIREPOWER` at BOTH ranks — so it is the one unit that
    // never gets the ROF bonus at all.
    rofAt: 0,
    elite: { dmg: 80, wh: 'ARTYHE' },
    cap: 0, mine: 0, w: 20, h: 14, desc: 'Carrier-borne bomber'
  },
  dolphin: {
    // [DLPH] $500 / Str 200 / light / Speed 8 / Sight 4, Underwater=yes,
    // Sensors=yes, Cloakable=yes. [SonicZap] 4 + AmbientDamage 10 / ROF 120
    // / Range 6 / SonicWarhead; LandTargeting=1, NavalTargeting=5 — it is
    // an anti-submarine escort, it does not shell the shore.
    name: 'Dolphin', em: '🐬', cost: 500, build: 21, cls: 'n', fac: 'dir', nav: 1,
    sub: 1, sensors: 1, notHuman: true, psiImmune: true, req: 'lab',
    hp: 200, spd: 0.104, sight: 4, armour: 'light', landTgt: false,
    dmg: 42, rate: 480, rng: 6, splash: 0, wh: 'SonicWH',
    // [DLPH] ElitePrimary=[SonicZapE] (rules.ini:17976): Damage 4 -> 8,
    // Burst -> 2, AmbientDamage 10 -> 15, ROF 120 -> 80. Our 42 is the base
    // weapon's whole pulse folded at 3x ((4 x 1) + 10 = 14, x3): the sonic
    // wave passes through more than once and one `dmg` has to carry it. The
    // elite figure is the SAME fold on the elite numbers — ((8 x 2) + 15) =
    // 31, x3 = 93 — so the elite/base ratio is RA2's own 3.32x rather than
    // a number picked to look right.
    elite: { dmg: 93, rate: 320 },
    cap: 0, mine: 0, w: 16, h: 10, desc: 'Submerged sonic escort; sees and kills submarines'
  },
  lcraft: {
    // [LCRF] $900 / Str 300 / light / Speed 6 / Passengers 12. SpeedType
    // Hover in v1.006 — it crosses the beach, which is what makes it a
    // LANDING craft rather than a ferry.
    name: 'Landing Craft', em: '⛴️', cost: 900, build: 38, cls: 'n', fac: 'dir', nav: 1, amph: 1,
    hp: 300, spd: 0.078, sight: 6, armour: 'light',
    pax: 12, paxInf: true, paxVeh: true, paxHarv: true, passive: true,
    dmg: 0, rate: 0, rng: 0, splash: 0, wh: null,
    rofAt: 2,          // [LCRF] VeteranAbilities has no ROF; EliteAbilities does
    cap: 0, mine: 0, w: 26, h: 14, desc: 'Twelve seats, crosses water AND land; unload with D'
  },
  sub: {
    // [SUB] $1000 / Str 600 / heavy / Speed 4 / Sight 4, Underwater=yes,
    // Sensors=yes, Cloakable=yes, TechLevel 2. [SubTorpedo] 100 / ROF 120 /
    // Range 7 / APSplash; LandTargeting=1 — torpedoes are for hulls.
    name: 'Typhoon Attack Sub', em: '🌊', cost: 1000, build: 42, cls: 'n', fac: 'col', nav: 1,
    sub: 1, sensors: 1,
    hp: 600, spd: 0.052, sight: 4, armour: 'heavy', landTgt: false,
    dmg: 100, rate: 480, rng: 7, splash: 0.5, wh: 'APSplash',
    // [SUB] ElitePrimary=[SubTorpedoE] (rules.ini:17965): Burst=2. (Its
    // Speed 25 -> 18 is the torpedo's travel speed, which we do not model.)
    elite: { burst: 2 },
    cap: 0, mine: 0, w: 26, h: 12, desc: 'Runs submerged; torpedoes anything afloat'
  },
  seascorp: {
    // [HYD] $600 / Str 400 / heavy / Speed 8 / Sight 8, Prerequisite
    // NAYARD+NARADR. Primary [FlakTrackGun] 25 / ROF 40 / Range 5 / FlakTWH,
    // Secondary [FlakWeapon] 40 / ROF 20 / Range 12 / FlakWH — the fleet's
    // flak escort with a light gun for anything on the surface.
    name: 'Sea Scorpion', em: '🦂', cost: 600, build: 25, cls: 'n', fac: 'col', nav: 1, req: 'radar',
    hp: 400, spd: 0.104, sight: 8, armour: 'heavy', aa: true, aaRng: 12, flak: true,
    dmg: 25, rate: 160, rng: 5, splash: 0.4, wh: 'FlakTWH',
    elite: { burst: 2 },   // [HYD] ElitePrimary=[FlakTrackGunE] (rules.ini:17701): Burst=2
    aaW: { dmg: 40, rate: 80, rng: 12, aaRng: 12, splash: 0.6, wh: 'FlakWH', aa: true, flak: true },
    cap: 0, mine: 0, w: 22, h: 13, desc: 'Flak escort: anti-air umbrella and a light deck gun'
  },
  dread: {
    // [DRED] $2000 / Str 800 / heavy / Speed 4, Prerequisite NAYARD+NATECH.
    // Spawns=DMISL, SpawnsNumber=2 (`SpawnReloadRate=0` — the missiles do
    // not come back); [DredLauncher] ROF 50 / Range 25 / MinimumRange 8.
    // The V3's big brother: it bombards the shore from open water.
    name: 'Dreadnought', em: '🚀', cost: 2000, build: 84, cls: 'n', fac: 'col', nav: 1, req: 'lab',
    hp: 800, spd: 0.052, sight: 7, armour: 'heavy', passive: true,
    // [General] DMislDamage=300 — the DMisl detonates for 300, and
    // [DredLauncher] Burst=2 sends two. 100 was the launcher's own Damage=50
    // doubled, which is the projectile's launch value, not its warhead's.
    dmg: 300, burst: 2, rate: 200, rng: 25, minRng: 8, splash: 1.2, wh: 'DredWH',
    cap: 0, mine: 0, w: 34, h: 17, desc: 'Two long-range missiles per salvo; cannot fire inside 8 cells'
  },
  squid: {
    // [SQD] $1000 / Str 200 / light / Speed 8, Underwater=yes, Organic=yes,
    // SelfHealing=yes, Sensors=yes. [SquidGrab] Range 1.5 / ParasitePlus
    // (Parasite=yes — it does not wound the hull, it takes hold of it) and
    // [SquidPunch] 50 / ROF 32 / Range 1.83 / HE for everything else.
    name: 'Giant Squid', em: '🦑', cost: 1000, build: 42, cls: 'n', fac: 'col', nav: 1, req: 'lab',
    sub: 1, sensors: 1, notHuman: true, selfHeal: true, grab: true,
    hp: 200, spd: 0.104, sight: 5, armour: 'light', landTgt: false,
    dmg: 50, rate: 128, rng: 1.83, splash: 0, wh: 'HE',
    // [SQD] ElitePrimary=[SquidGrabE] (rules.ini:18102): Damage 15 -> 40.
    // RA2's Primary is the GRAB and its Secondary the punch; ours are the
    // other way round, so the elite swap lands on `w2` — which is why
    // weaponFor applies it to whichever weapon it resolved, not to the
    // spec it started from.
    w2: { dmg: 15, rate: 128, rng: 1.5, wh: 'Parasite', splash: 0, use: 'ship', elite: { dmg: 40 } },
    cap: 0, mine: 0, w: 18, h: 12, desc: 'Grabs a ship and drags it under; invisible until it strikes'
  },
  mcv: {
    // RA2 SMCV/AMCV: Cost 3000, Strength 1000, Armor heavy, Speed 4,
    // Sight 6, no weapon. `req: 'depot'` on top of the vehicle lane's
    // implicit War Factory is RA2's "Factory AND Service Depot" pair.
    // `deploysInto` is what makes D / the Deploy button turn it into a yard.
    name: 'MCV', em: '🏗️', cost: 3000, build: 126, cls: 'v', fac: null, req: 'depot', deploysInto: 'base',
    hp: 1000, spd: 0.052, sight: 6, armour: 'heavy',
    dmg: 0, rate: 0, rng: 0, splash: 0, wh: null,
    cap: 0, mine: 0, w: 22, h: 16, desc: 'Deploys in place into a Construction Yard (D)'
  }
};

// `elite:` above is written the way rules.ini writes an `ElitePrimary=` —
// ONLY the fields that differ (the median elite weapon changes two). Bake
// each one into a COMPLETE weapon here, once, at load: after this every
// `elite` is a whole spec that any consumer can read `.dmg`/`.rate`/`.rng`/
// `.wh`/`.burst`/`.splash` off without knowing it is the elite variant, and
// eliteOf() is a field lookup rather than a merge on the firing path. The
// baked copy deliberately carries no `elite` of its own, so a second swap
// is impossible.
(function bakeElite() {
  function bake(w) {
    if (!w || !w.elite) return;
    var o = {}, k;
    for (k in w) if (k !== 'elite') o[k] = w[k];
    for (k in w.elite) o[k] = w.elite[k];
    w.elite = o;
  }
  for (var t in UNITS) {
    var s = UNITS[t];
    // Sub-weapons first, so a top-level bake copies the already-baked ones.
    bake(s.w2); bake(s.aaW); bake(s.asw); bake(s.dep);
    bake(s);
  }
})();

// --------------------------------------------------------------------- //
//  The IFV's thirteen weapons ([FV] WeaponCount=13, TurretCount=4)
// --------------------------------------------------------------------- //
// rules.ini gives every infantryman an `IFVMode=`; [FV] then lists, in that
// exact order, a *TurretIndex / *TurretWeapon pair per mode. So the mode
// number IS the index into the table below, the turret index is which of the
// four turret models goes on the hull, and the weapon index picks one of the
// thirteen Weapon= lines. Read straight off rules.ini v1.006:
//
//   0 Normal   tur 0  HoverMissile      | 1 Repair  tur 2  RepairBullet
//   2 MachineGun tur 1 CRM60            | 3 Flak    tur 1  CRFlakGuyGun
//   4 Pistol   tur 1  CRMP5             | 5 Sniper  tur 1  AWPE
//   6 Shock    tur 3  CRElectricBolt    | 7 Explode tur 3  CRNuke
//   8 BrainBlast tur 3 CRMindControl    | 9 RadCannon tur 3 CRRadBeamWeapon
//  10 Chrono   tur 3  CRNeutronRifle    |11 Terrorist tur 3 CRTerrorBomb
//  12 Cow      tur 3  CowShot
//
// Turret models (the `;GEF` comment block in [FV]): 0 rocket, 1 gun,
// 2 repair arm, 3 high-tech.
export var IFV_TUR_ROCKET = 0, IFV_TUR_GUN = 1, IFV_TUR_ARM = 2, IFV_TUR_TECH = 3;

export var IFV_MODES = [
  // 0 — empty, a dog, or anything rules.ini leaves at the default.
  { n: 'Missile',      tur: IFV_TUR_ROCKET, rep: 'rocket',
    dmg: 50, rate: 200, rng: 6, minRng: 1, splash: 0.5, wh: 'HE', aa: true, aaRng: 6 },
  // 1 — [RepairBullet] Damage=-50, ROF=80, Range=1.8, Warhead=Mechanical.
  //     A negative-damage weapon: it welds friendly vehicles, it has no gun.
  { n: 'Repair arm',   tur: IFV_TUR_ARM, rep: 'repairifv', repair: 50,
    dmg: 0, rate: 320, rng: 1.8, splash: 0, wh: null },
  // 2 — [CRM60] 20 / ROF 15 / Range 6 / SSA. GI, Conscript, Spy.
  { n: 'Machine gun',  tur: IFV_TUR_GUN, rep: 'mg',
    dmg: 20, rate: 60, rng: 6, splash: 0, wh: 'SSA' },
  // 3 — [CRFlakGuyGun] 30 / ROF 15 / Range 7 / FlakTWH. Flak Trooper, Rocketeer.
  { n: 'Flak cannon',  tur: IFV_TUR_GUN, rep: 'flak',
    dmg: 30, rate: 60, rng: 7, splash: 1, wh: 'FlakTWH', aa: true, aaRng: 7,
    aaW: { dmg: 30, rate: 60, rng: 7, aaRng: 7, splash: 0.6, wh: 'FlakWH', aa: true, flak: true }, flak: true },
  // 4 — [CRMP5] 125 / ROF 20 / Range 6 / HollowPoint3. SEAL, Tanya.
  { n: 'Sub-machine gun', tur: IFV_TUR_GUN, rep: 'shot',
    dmg: 125, rate: 80, rng: 6, splash: 0, wh: 'HollowPoint' },
  // 5 — [AWPE] 125 / ROF 60 / Range 14 / HollowPoint. (No Sniper on the
  //     roster yet; the row is here because the mode index has to line up.)
  { n: 'Sniper rifle', tur: IFV_TUR_GUN, rep: 'shot',
    dmg: 125, rate: 240, rng: 14, splash: 0, wh: 'HollowPoint' },
  // 6 — [CRElectricBolt] 60 / ROF 45 / Range 6 / Shock. Tesla Trooper.
  { n: 'Tesla coil',   tur: IFV_TUR_TECH, rep: 'tesla',
    dmg: 60, rate: 180, rng: 6, splash: 0, wh: 'Shock' },
  // 7 — [CRNuke] 200 / ROF 80 / Range 1 / CRNUKEWH, Suicide=yes, and
  //     [FV] DeathWeapon=CRNuke: an Ivan aboard blows the hull up as well.
  { n: 'Demolition charge', tur: IFV_TUR_TECH, rep: 'ivantick', suicide: true,
    dmg: 200, rate: 320, rng: 1.5, splash: 1.5, wh: 'IvanWH' },
  // 8 — [CRMindControl] 200 / ROF 10 / Range 1 / PsiPulse, AreaFire. Yuri.
  { n: 'Psychic blast', tur: IFV_TUR_TECH, rep: 'psy',
    dmg: 200, rate: 40, rng: 1, splash: 3, wh: 'PsiPulse' },
  // 9 — [CRRadBeamWeapon] 175 / ROF 30 / Range 7 / RadBeamWarhead. Desolator.
  { n: 'Radiation beam', tur: IFV_TUR_TECH, rep: 'deso',
    dmg: 175, rate: 120, rng: 7, splash: 0, wh: 'RadBeamWH' },
  // 10 — [CRNeutronRifle] 10 / ROF 120 / Range 6 / ChronoBeam (Temporal=yes).
  { n: 'Neutron rifle', tur: IFV_TUR_TECH, rep: 'cleg', temporal: true,
    dmg: 10, rate: 480, rng: 6, splash: 0, wh: 'ChronoBeam' },
  // 11 — [CRTerrorBomb] 250 / ROF 10 / Range 1.5, Suicide=yes. (No Terrorist.)
  { n: 'Terror bomb',  tur: IFV_TUR_TECH, rep: 'ivantick', suicide: true,
    dmg: 250, rate: 40, rng: 1.5, splash: 1.5, wh: 'IvanWH' },
  // 12 — [CowShot]. Livestock. Kept so the index matches rules.ini.
  { n: 'Cow',          tur: IFV_TUR_TECH, rep: 'shot',
    dmg: 1, rate: 200, rng: 2, splash: 0, wh: 'SSA' }
];

// `IFVMode=` per infantry kind, straight off rules.ini: [E1] GI 2, [E2]
// Conscript 2, [SPY] 2, [ENGINEER]/[SENGINEER] 1, [FLAKT] 3, [TANY] 4,
// [SNIPE] 5, [SHK] Shock Trooper 6, [IVAN] 7, [YURI] 8, [DESO] 9, [CLEG] 10,
// [DOG]/[ADOG] 0. The Guardian GI is a Yuri's Revenge unit and has no row in
// this rules.ini; rulesmd gives [GGI] IFVMode=0, the rocket pod — which is
// also the one thing a missile trooper would obviously man.
export var IFV_MODE = {
  rifle: 2, conscript: 2, spy: 2,
  engineer: 1,
  flak: 3, rocketeer: 3,          // [FV] Weapon4 comment: "Flak Troop ;Rocketeer"
  tanya: 4,
  teslatrooper: 6,
  ivan: 7,
  yuri: 8,
  desolator: 9,
  cleg: 10,
  dog: 0, rocket: 0
};

export function ifvModeOf(u) {
  if (!u || !UNITS[u.type] || !UNITS[u.type].ifv) return 0;
  if (!u.pax || !u.pax.length) return 0;
  var m = IFV_MODE[u.pax[0].type];
  return m === undefined ? 0 : m;
}

export function ifvSpec(u) { return IFV_MODES[ifvModeOf(u)] || IFV_MODES[0]; }

// Which of the four turret models the hull is wearing right now.
export function ifvTurret(u) { return ifvSpec(u).tur; }
