// Iron Frontier — shroud.js
// GENERATED by apps/games/rts/tools/modularize from rts.src.html + art/units/**.

import { BLDS } from './blds.js';
import { powered } from './entities.js';
import { UNITS } from './roster.js';
import { inMap } from './state.js';
import { MAP, ME } from './world.js';

// --------------------------------------------------------------------- //
//  Simulation step
// --------------------------------------------------------------------- //
// Shroud (RA2 without fog of war): the map starts black and stays revealed
// once any of the player's units or structures has had it in sight. Enemy
// entities on unrevealed tiles are neither drawn nor hoverable. The AI is
// not shrouded — RA2's AI is not either.
export function revealFor(g, p) {
  var seen = g.seen, i, e, r, cx, cy, x, y, r2;
  // [GASPYSAT] SpySat=yes, Powered=true: no radius, no sweep — the map is
  // simply yours. Pull the power (or the building) and the shroud returns,
  // because the gap pass and this one run again from scratch every beat.
  if (spySatUp(g, p)) { for (i = 0; i < seen.length; i++) seen[i] = 1; return; }
  function disc(cx, cy, r) {
    var x0 = Math.max(0, Math.floor(cx - r)), x1 = Math.min(MAP - 1, Math.ceil(cx + r));
    var y0 = Math.max(0, Math.floor(cy - r)), y1 = Math.min(MAP - 1, Math.ceil(cy + r));
    r2 = (r + 0.5) * (r + 0.5);
    for (y = y0; y <= y1; y++) for (x = x0; x <= x1; x++)
      if ((x - cx) * (x - cx) + (y - cy) * (y - cy) <= r2) seen[y * MAP + x] = 1;
  }
  for (i = 0; i < g.units.length; i++) { e = g.units[i]; if (!e.dead && e.p === p) disc(e.x, e.y, UNITS[e.type].sight); }
  for (i = 0; i < g.blds.length; i++) { e = g.blds[i]; if (!e.dead && e.p === p) disc(e.cx, e.cy, BLDS[e.type].sight + Math.max(e.gw, e.gh) / 2); }
}

export function spySatUp(g, p) {
  for (var i = 0; i < g.blds.length; i++) {
    var b = g.blds[i];
    if (b.dead || b.p !== p || b.make > 0 || b.offline) continue;
    if (BLDS[b.type].spysat && powered(g, p)) return true;
  }
  return false;
}

// [NACLON] Cloning=yes: the Vats runs a second copy of every man the
// barracks turns out, free, and puts him at its own door.
export function cloneVatsOf(g, p) {
  for (var i = 0; i < g.blds.length; i++) {
    var b = g.blds[i];
    if (b.dead || b.p !== p || b.make > 0 || b.offline) continue;
    if (BLDS[b.type].clone && powered(g, p)) return b;
  }
  return null;
}

// --------------------------------------------------------------------- //
//  Gap Generator ([GAGAP] GapGenerator=yes, GapRadiusInCells=10)
//
//  RA2 does not tint the enemy's view of the disc — it takes the ground
//  BACK. The shroud closes over everything inside the radius on the OTHER
//  player's map, so units and structures under it stop existing as far as
//  he is concerned, and the only thing that reopens a cell is walking into
//  it again (his own sight discs are applied AFTER the gap each pass, which
//  is why a column inside the field still lights its own little pool).
//  `g.gapM[p]` is what is hidden FROM p: 2 = shrouded core, 1 = the outer
//  ring, which keeps its ground and only takes the dark wash so the edge
//  is soft instead of a cut circle.
// --------------------------------------------------------------------- //
export function applyGaps(g) {
  if (!g.gapM) g.gapM = [new Uint8Array(MAP * MAP), new Uint8Array(MAP * MAP)];
  var any = false, i, p;
  for (p = 0; p < 2; p++) g.gapM[p].fill(0);
  for (i = 0; i < g.blds.length; i++) {
    var b = g.blds[i], d = BLDS[b.type];
    if (b.dead || !d.gap || b.make > 0) continue;
    if (b.offline || !powered(g, b.p)) continue;         // Powered=true: no grid, no field
    var vic = 1 - b.p, m = g.gapM[vic], R = d.gap, R2 = R * R, IN = (R - 1.6) * (R - 1.6);
    var x0 = Math.max(0, Math.floor(b.cx - R)), x1 = Math.min(MAP - 1, Math.ceil(b.cx + R));
    var y0 = Math.max(0, Math.floor(b.cy - R)), y1 = Math.min(MAP - 1, Math.ceil(b.cy + R));
    for (var y = y0; y <= y1; y++) for (var x = x0; x <= x1; x++) {
      var dx = x - b.cx, dy = y - b.cy, dd = dx * dx + dy * dy;
      if (dd > R2) continue;
      var lv = dd <= IN ? 2 : 1;
      if (lv > m[y * MAP + x]) m[y * MAP + x] = lv;
      any = true;
    }
  }
  g.gapAny = any;
  // The human's memory of the ground is what actually gets erased.
  if (!any || g.debug) return;
  var hm = g.gapM[ME], seen = g.seen;
  for (i = 0; i < seen.length; i++) if (hm[i] === 2) seen[i] = 0;
}

export function gapped(g, p, x, y) {
  return !!(g.gapAny && g.gapM && g.gapM[p][((y | 0) * MAP + (x | 0))] === 2);
}

export function tileSeen(g, x, y) {
  x = Math.round(x); y = Math.round(y);
  return !inMap(x, y) || g.seen[y * MAP + x] === 1;
}

export function entSeen(g, e) {
  if (e.p === ME) return true;
  if (e.kind === 'u') return tileSeen(g, e.x, e.y);
  for (var yy = e.y; yy < e.y + e.gh; yy++) for (var xx = e.x; xx < e.x + e.gw; xx++) if (tileSeen(g, xx, yy)) return true;
  return false;
}
