// Iron Frontier — supers.js
// GENERATED by apps/games/rts/tools/modularize from rts.src.html + art/units/**.

import { BLDS } from './blds.js';
import { bspecFor } from './combat-tables.js';
import { hasFacBld, ownedBy } from './factions.js';

// --------------------------------------------------------------------- //
//  Superweapons (RA2). The structure is only the charger: the TIMER lives
//  on the side, so losing and rebuilding a silo restarts the countdown and
//  a second silo buys nothing — exactly RA2's rule. Charge times are the
//  rules.ini ones and only advance while the owner's grid is powered.
// --------------------------------------------------------------------- //
export var SW = {
  chrono:  { bld: 'chrono',  name: 'Chronosphere',           em: '\ud83c\udf00', charge: 60 * 60 * 7,  two: true,
             ready: 'Chronosphere ready',
             hint: 'Chronosphere \u2014 click the 3\u00d73 of vehicles to lift. Esc cancels.',
             hint2: 'Chronosphere \u2014 now click where to drop them. Esc cancels.' },
  storm:   { bld: 'weather', name: 'Weather Control Device', em: '\u26c8\ufe0f', charge: 60 * 60 * 10,
             ready: 'Weather Control Device ready',
             hint: 'Weather Control Device \u2014 click where the storm should form. Esc cancels.' },
  curtain: { bld: 'curtain', name: 'Iron Curtain',           em: '\ud83d\udee1\ufe0f', charge: 60 * 60 * 5,
             ready: 'Iron Curtain ready',
             hint: 'Iron Curtain \u2014 click the 3\u00d73 to make invulnerable. Esc cancels.' },
  nuke:    { bld: 'nuke',    name: 'Nuclear Missile',        em: '\u2622\ufe0f', charge: 60 * 60 * 10,
             ready: 'Nuclear missile ready',
             hint: 'Nuclear Missile \u2014 click the target. Esc cancels.' },
  // [ParaDropSpecial] RechargeTime=4, carried by a captured [CAAIRP]. It is
  // the only superweapon in the game that belongs to a building you cannot
  // build — you take it off the map with an Engineer.
  para:    { bld: 'airport', name: 'Paratrooper Drop',        em: '\ud83e\ude82', charge: 60 * 60 * 4,
             ready: 'Paratroopers ready',
             hint: 'Paratrooper Drop \u2014 click where the stick should land. Esc cancels.' }
};

export var SW_KEYS = ['chrono', 'storm', 'curtain', 'nuke', 'para'];

// [General] IronCurtainDuration=750 frames and LightningStormDuration=180.
// rules.ini:693 says in Westwood's own words "In frames 900 is a minute for
// 15fps", so 750 frames is FIFTY seconds, not twenty. STORM_T was already
// derived at 15 fps (180/15 = 12 s); IRON_T matched neither 15 nor 30 and
// was simply short, which made the Collective's answer to a defended base
// less than half the window RA2 gives it.
export var IRON_T = 50 * 60, STORM_T = 12 * 60, NUKE_FLIGHT = 10 * 60;

export function swInit() {
  var o = {};
  for (var i = 0; i < SW_KEYS.length; i++) o[SW_KEYS[i]] = { t: 0, ready: false, fired: 0, armed: false };
  return o;
}

// Is this structure a superweapon? (The captured Airport carries the
// Paratrooper special but is not buildable, so it never reaches canBuild.)
export function swBld(key) {
  for (var i = 0; i < SW_KEYS.length; i++) if (SW[SW_KEYS[i]].bld === key) return true;
  return false;
}

export function swKeysFor(fac) {
  var a = [];
  for (var i = 0; i < SW_KEYS.length; i++) if (BLDS[SW[SW_KEYS[i]].bld].fac === fac) a.push(SW_KEYS[i]);
  return a;
}

// Invulnerable under the Iron Curtain: checked by damage() before anything
// else, so a shot at a curtained Rhino is not merely survived, it is void.
export function ironed(g, e) { return !!e.ironUntil && g.tick < e.ironUntil; }

// Prerequisite check (RA2 tech tree): spec.req is one key or a list, any of.
// `req` = any one of these (the faction's radar-class building); `reqAll` =
// every one of these — rules.ini's Prerequisite= list is an AND.
//
// A faction-exclusive item's prerequisites are ITS faction's buildings:
// rules.ini writes [APOC] Prerequisite=NAWEAP,NATECH — the SOVIET Battle
// Lab, not the generic TECH alias — so an Engineer on their War Factory
// buys their Rhinos and not their Apocalypse. Keys only one faction has
// (`radar`, `airforce`) already say which; the shared ones (barracks, lab,
// depot, shipyard, power) are the ones that had to be asked. A both-sides
// item (fac null) keeps RA2's generic alias and takes either.
// In an ordinary match this is a no-op: every building a house owns carries
// that house's faction.
export function reqMet(g, p, spec) {
  var fac = spec.fac || null;
  if (spec.reqAll) for (var j = 0; j < spec.reqAll.length; j++) if (!hasFacBld(g, p, spec.reqAll[j], fac)) return false;
  if (!spec.req) return true;
  var rs = [].concat(spec.req);
  for (var i = 0; i < rs.length; i++) if (hasFacBld(g, p, rs[i], fac)) return true;
  return false;
}

export function reqName(spec, fac) {
  // Faction-aware: the Collective reads "Tesla Reactor", not "Power Plant",
  // and never sees the other side's radar-class building in an "or".
  var nm = function (k) { return bspecFor(k, fac || 'dir').name; };
  var own = function (k) { return !fac || ownedBy(BLDS[k], fac); };
  var a = (spec.reqAll || []).filter(own).map(nm).join(' + ');
  var o = spec.req ? [].concat(spec.req).filter(own).map(nm).join(' or ') : '';
  return a && o ? a + ' + ' + o : (a || o);
}
