'use strict';
// P2b: write the ES-module tree.
//
// `emit` runs the P1 unit conversion in memory first (it never reads a P1
// tree from disk), re-analyses the converted monolith, and writes
//   <out>/rts.html            the page, inline script replaced by one <script type="module">
//   <out>/rts/package.json    {"type":"module"}
//   <out>/rts/**.js           one module per section + 69 unit-art modules
// then proves the result: `node --check` on every file, and a real `import()`
// of main.js under the DOM stub rts.test.js uses.

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

const S = require('./source');
const SEC = require('./sections');
const M = require('./model');
const U = require('./units');
const R = require('./report');

const BANNER = (file, note) => [
  `// Iron Frontier — ${file}`,
  `// GENERATED by apps/games/rts/tools/modularize from rts.src.html + art/units/**.`,
  ...(note ? [`// ${note}`] : []),
];

function deindent(text, n, where) {
  const pad = ' '.repeat(n);
  return text.split('\n').map((l, i) => {
    if (!l.trim()) return '';
    if (!l.startsWith(pad)) {
      const e = new Error(`${where}: line ${i + 1} is not indented by ${n} spaces and cannot be de-indented: ${JSON.stringify(l.slice(0, 60))}`);
      e.loud = true;
      throw e;
    }
    return l.slice(n);
  }).join('\n');
}

// `X = e;` -> `setX(e);`, `X += e` -> `setX(X + (e))`, `X++` -> `setX(X + 1)`
function writeRewrite(rec, text, base) {
  const w = rec.w || rec;
  const setter = rec.setter;
  const node = w.node;
  if (w.kind === 'update') {
    return { start: node.start - base, end: node.end - base, text: `${setter}(${w.name} ${w.operator === '++' ? '+' : '-'} 1)` };
  }
  const rhs = text.slice(node.right.start - base, node.right.end - base);
  if (w.kind === 'simple') return { start: node.start - base, end: node.end - base, text: `${setter}(${rhs})` };
  const op = w.operator.slice(0, -1);
  return { start: node.start - base, end: node.end - base, text: `${setter}(${w.name} ${op} (${rhs}))` };
}

function applyEdits(text, edits) {
  const es = edits.slice().sort((a, b) => b.start - a.start);
  let out = text;
  for (const e of es) out = out.slice(0, e.start) + e.text + out.slice(e.end);
  return out;
}

function importHeader(from, byTarget) {
  const lines = [];
  const targets = [...byTarget.keys()].map((t) => [M.specifier(from, t), t]).sort((a, b) => (a[0] < b[0] ? -1 : 1));
  for (const [spec, t] of targets) {
    const names = [...byTarget.get(t)].sort();
    if (!names.length) lines.push(`import '${spec}';`);
    else lines.push(`import { ${names.join(', ')} } from '${spec}';`);
  }
  return lines;
}

function unitModulePath(u) { return `units/${u.cls}/${u.kind}.js`; }

function emit(outDir, api) {
  // ---- P1, in memory ----------------------------------------------------- //
  const ctx0 = api.fullAnalysis();
  const fails = R.checkReport(R.buildReport(ctx0));
  if (fails.length) {
    console.error('emit: refusing — `check` is not clean:');
    for (const f of fails) console.error('  ' + f);
    return 1;
  }
  console.error('emit: P1 in memory'); const p1Html = U.rewriteSource(ctx0.src, ctx0.ua); console.error('emit: rewrote monolith');

  // ---- re-analyse the converted monolith --------------------------------- //
  const src = S.loadSource(S.SRC, p1Html);
  const cfg = SEC.loadSections();
  const extraModules = ctx0.ua.units.map((u) => ({ file: unitModulePath(u), unit: u }));
  const model = M.buildModel(src, cfg, { extraModules }); console.error('emit: re-analysed');
  const unitByFile = new Map(extraModules.map((m) => [m.file, m.unit]));

  // ---- unit modules join the graph --------------------------------------- //
  const exportsOf = new Map();
  for (const [f, s] of model.perSection) exportsOf.set(f, new Set([...s.exported].filter((n) => s.declares.has(n))));
  for (const m of extraModules) exportsOf.set(m.file, new Set([m.unit.fnName]));

  const imports = model.imports;                   // file -> Map(target -> Set(names))
  const addImport = (from, to, name) => {
    if (from === to) return;
    if (!imports.has(from)) imports.set(from, new Map());
    const t = imports.get(from);
    if (!t.has(to)) t.set(to, new Set());
    if (name) t.get(to).add(name);
  };

  // (a) each unit module imports the closure names its body uses
  for (const m of extraModules) {
    const u = m.unit;
    for (const n of u.topNames) {
      const own = model.ownerOf.get(n);
      if (!own || !own.section) continue;
      addImport(m.file, own.section, n);
      exportsOf.get(own.section).add(n);
    }
    for (const n of u.topWrites) {
      const st = model.setters.get(n);
      if (!st) { console.error(`emit: no setter for closure var ${n} written by ${u.rel}`); return 1; }
      addImport(m.file, st.owner, st.setter);
      exportsOf.get(st.owner).add(st.setter);
    }
  }

  // (b) whoever calls the extracted function imports it
  const byName = new Map();
  for (const r of model.res.refs) {
    if (r.binding) continue;
    if (!byName.has(r.name)) byName.set(r.name, []);
    byName.get(r.name).push(r);
  }
  for (const m of extraModules) {
    const u = m.unit;
    const hits = byName.get(u.fnName) || [];
    if (!hits.length) { console.error(`emit: nothing references ${u.fnName} (${u.rel}) in the converted monolith`); return 1; }
    for (const r of hits) {
      const st = model.stmts[model.stmts.bodyOfGroup[r.top]];
      if (st) addImport(st.section, m.file, u.fnName);
    }
  }

  // ---- order + cycles on the augmented graph ------------------------------ //
  console.error('emit: graph done'); const ev = M.evalOrder(model); console.error('emit: order done');
  const violations = M.orderViolations(model, ev);
  if (violations.length) {
    console.error('emit: refusing — the module graph would evaluate a load-time read too early:');
    for (const v of violations) console.error(`  ${v.from} reads ${v.name} (owner ${v.owner}) at rts.src.html:${v.at}`);
    return 1;
  }

  // ---- write --------------------------------------------------------------//
  const files = new Map();
  const rtsDir = 'rts';

  for (const sec of model.sections) {
    const f = sec.file;
    const isMain = f === 'main.js';
    const byTarget = new Map();
    if (isMain) {
      for (const other of model.files) {
        if (other === f) continue;
        byTarget.set(other, (imports.get(f) || new Map()).get(other) || new Set());
      }
    } else {
      for (const [t, names] of imports.get(f) || new Map()) byTarget.set(t, names);
    }

    const out = BANNER(f, isMain ? 'the boot section; it imports every module so evaluation order is the section order' : null);
    const head = importHeader(f, byTarget);
    if (head.length) { out.push(''); out.push(...head); }
    out.push('');

    const exported = exportsOf.get(f);
    for (const st of sec.all) {
      const base = st.chunkStart;
      const edits = [];
      for (const rec of model.crossWrites) {
        if (rec.w.node.start < st.chunkStart || rec.w.node.end > st.chunkEnd) continue;
        const setter = model.setters.get(rec.name).setter;
        edits.push(writeRewrite({ ...rec, setter }, st.text, base));
      }
      let text = applyEdits(st.text, edits);
      text = deindent(text, 2, `${f} (rts.src.html:${st.fileLine})`);
      const wants = st.names.some((n) => exported.has(n));
      if (wants) {
        if (st.nodes.length > 1) { console.error(`emit: ${f}: two statements share a line and one must be exported (rts.src.html:${st.fileLine})`); return 1; }
        const lines = text.split('\n');
        lines[st.stmtLineInChunk] = 'export ' + lines[st.stmtLineInChunk];
        text = lines.join('\n');
      }
      out.push(text.replace(/\n+$/, ''));
      out.push('');
    }

    const setters = [...model.setters.values()].filter((s) => s.owner === f);
    if (setters.length) {
      out.push('// --- generated ---');
      out.push('// ESM import bindings are read-only, so a write from another module goes');
      out.push('// through the owner. Reads stay verbatim everywhere: the binding is live.');
      for (const s of setters.sort((a, b) => (a.name < b.name ? -1 : 1))) {
        out.push(`export function ${s.setter}(v) { ${s.name} = v; }`);
      }
      out.push('');
    }
    files.set(`${rtsDir}/${f}`, out.join('\n').replace(/\n{3,}/g, '\n\n'));
  }

  // unit modules
  for (const m of extraModules) {
    const u = m.unit;
    const byTarget = new Map();
    for (const [t, names] of imports.get(m.file) || new Map()) byTarget.set(t, names);
    const out = u.headerLines.slice();
    const head = importHeader(m.file, byTarget);
    if (head.length) { out.push(''); out.push(...head); }
    out.push('');

    // rewrite the body's writes to closure vars
    const edits = [];
    for (const w of u.wrapped.res.writes) {
      if (w.binding) continue;
      if (!u.topWrites.includes(w.name)) continue;
      const st = model.setters.get(w.name);
      const cls = M.classifyWrite(w);
      if (!cls.ok) { console.error(`emit: ${u.rel}: cannot rewrite the write to ${w.name}: ${cls.why}`); return 1; }
      // The write nodes were found in u.wrapped.text (the body wrapped in a
      // dummy function so it parses), so their offsets are WRAPPED offsets and
      // `delta` maps them back to body offsets. applyEdits() below runs against
      // u.bodyText, so the right-hand side must be sliced out of u.bodyText too
      // — slicing the wrapped text with body offsets produced `setVLIFT( )` in
      // ifv.js and `setVLIFT(s)` in mcv.js, i.e. a silent NaN in the IFV's paint.
      edits.push(writeRewrite({ w, setter: st.setter, kind: w.kind, name: w.name, operator: w.operator },
        u.bodyText, u.wrapped.delta));
    }
    const body = applyEdits(u.bodyText, edits);
    const { header, rest } = U.splitHeader(body);
    void header;
    const v = { ...u, restText: rest, headerLines: [] };
    const fnText = U.unitFileText(v).replace(/\n$/, '');
    out.push('export ' + fnText);
    files.set(`${rtsDir}/${m.file}`, out.join('\n').replace(/\n{3,}/g, '\n\n') + '\n');
  }

  files.set(`${rtsDir}/package.json`, JSON.stringify({ type: 'module' }, null, 2) + '\n');

  // the page
  const tag = '<script type="module" src="rts/main.js"></script>';
  const html = src.html.slice(0, src.html.lastIndexOf('<script>', src.scriptStart)) + tag +
    src.html.slice(src.scriptEnd + '</script>'.length);
  files.set('rts.html', html);

  for (const [rel, text] of files) {
    const p = path.join(outDir, rel);
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, text.endsWith('\n') ? text : text + '\n');
  }
  console.log(`emit: ${files.size} files -> ${outDir}`);
  console.log(`      ${model.sections.length} section modules + ${extraModules.length} unit modules`);
  console.log(`      evaluation order: ${ev.order.filter((f) => !f.startsWith('units/')).join(' ')}`);

  return verify(outDir, files) ? 0 : 1;
}

// ---- proof --------------------------------------------------------------- //
function verify(outDir, files) {
  let bad = 0;
  for (const rel of files.keys()) {
    if (!rel.endsWith('.js')) continue;
    const r = spawnSync(process.execPath, ['--check', path.join(outDir, rel)], { encoding: 'utf8' });
    if (r.status !== 0) { console.error(`verify: node --check FAILED on ${rel}\n${r.stderr}`); bad++; }
  }
  if (bad) return false;
  console.log(`verify: node --check clean on ${[...files.keys()].filter((f) => f.endsWith('.js')).length} files`);

  const harness = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'rts-verify-')), 'load.mjs');
  fs.writeFileSync(harness, HARNESS.replace('__MAIN__', JSON.stringify(path.join(outDir, 'rts', 'main.js'))));
  const r = spawnSync(process.execPath, [harness], { encoding: 'utf8' });
  process.stdout.write(r.stdout);
  if (r.status !== 0) { console.error('verify: importing rts/main.js FAILED\n' + r.stderr); return false; }
  return true;
}

// the DOM stub is rts.test.js's `load()`, lifted onto globalThis
const HARNESS = `
function stubCtx() {
  const noop = () => {};
  return {
    fillStyle: "", strokeStyle: "", lineWidth: 1, font: "", textAlign: "left",
    globalAlpha: 1, globalCompositeOperation: "source-over",
    fillRect: noop, strokeRect: noop, clearRect: noop, fillText: noop, strokeText: noop,
    lineJoin: "miter", miterLimit: 10, textBaseline: "alphabetic",
    beginPath: noop, closePath: noop, moveTo: noop, lineTo: noop,
    fill: noop, stroke: noop, arc: noop, ellipse: noop, roundRect: noop, clip: noop,
    quadraticCurveTo: noop, bezierCurveTo: noop, arcTo: noop, rect: noop,
    save: noop, restore: noop, scale: noop, translate: noop, rotate: noop, setTransform: noop,
    drawImage: noop, putImageData: noop,
    getImageData: () => ({ data: [] }),
    createRadialGradient: () => ({ addColorStop: noop }),
    createLinearGradient: () => ({ addColorStop: noop }),
    measureText: () => ({ width: 10 }),
  };
}
function stubEl() {
  const el = {
    style: { setProperty: () => {}, removeProperty: () => {}, getPropertyValue: () => "" },
    dataset: {}, textContent: "", innerHTML: "", className: "", hidden: false, value: "0",
    width: 800, height: 600, _terr: null,
    classList: { add: () => {}, remove: () => {}, toggle: () => {}, contains: () => false },
    addEventListener: () => {}, removeEventListener: () => {},
    appendChild: () => {}, removeChild: () => {}, setAttribute: () => {},
    getAttribute: () => "b", setPointerCapture: () => {},
    getContext: () => stubCtx(),
    getBoundingClientRect: () => ({ left: 0, top: 0, width: 800, height: 600 }),
  };
  el.querySelector = () => stubEl();
  el.querySelectorAll = () => [];
  return el;
}
const store = {};
const win = globalThis;
win.devicePixelRatio = 1;
win.addEventListener = () => {};
win.removeEventListener = () => {};
win.requestAnimationFrame = () => 0;
win.performance = { now: () => 0 };
win.localStorage = {
  getItem: (k) => (k in store ? store[k] : null),
  setItem: (k, v) => { store[k] = String(v); },
  removeItem: (k) => { delete store[k]; },
};
win.btoa = (b) => Buffer.from(b, "binary").toString("base64");
win.atob = (b) => Buffer.from(b, "base64").toString("binary");
win.setTimeout = () => 0;
win.document = {
  getElementById: () => stubEl(),
  createElement: () => stubEl(),
  querySelector: () => stubEl(),
  querySelectorAll: () => [],
  addEventListener: () => {},
  removeEventListener: () => {},
};
win.window = win;
await import('file://' + __MAIN__);
if (!globalThis.__rtsTest) { console.error('verify: __rtsTest was not defined'); process.exit(1); }
if (!globalThis.__rtsTables || !globalThis.__rtsSim) { console.error('verify: __rtsTables/__rtsSim missing'); process.exit(1); }
const g = globalThis.__rtsTest.api ? 'api present' : 'api MISSING';
console.log('verify: import("rts/main.js") ok — __rtsTest (' + g + '), __rtsTables, __rtsSim all defined');
`;

module.exports = { emit, deindent, writeRewrite, applyEdits, importHeader };
