#!/usr/bin/env python3
"""Build apps/games/rts/rts.html from rts.src.html + art/units/**.

The RTS page is the one file in this repo that is BUILT. Every unit's art is
its own file under `art/units/<class>/<kind>.js`, and `rts.src.html` marks
where each one lands with a single line —

        // @@include art/units/vehicles/rhino.js

— at the indentation the body should take. This script splices them in and
writes `rts.html`, which is what runs, deploys, and gets loaded by every test
and art tool. The output is gitignored and read-only, and the script refuses
to overwrite one that was edited by hand (see the guard below), so the unit
files and rts.src.html are the only copy of anything.

    python3 apps/games/rts/tools/rts-build.py            # build (no-op if current)
    python3 apps/games/rts/tools/rts-build.py --check    # exit 1 if rts.html is missing or stale
    python3 apps/games/rts/tools/rts-build.py --force    # discard a hand-edited rts.html

`run-tests.sh` and `shell/install.sh` both run it first, so a checkout that
tests or deploys is always built. Why the page is assembled textually rather
than loading the unit files as scripts: docs/design-decisions.md, "RTS unit
art split".
"""
import argparse
import hashlib
import os
import re
import sys
import tempfile

RTS = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(RTS, "rts.src.html")
OUT = os.path.join(RTS, "rts.html")
STAMP = os.path.join(RTS, ".rts-build.sha")
UNITS = os.path.join(RTS, "art", "units")
INCLUDE = re.compile(r"^( *)// @@include (\S+)\s*$")
HEADER = ("<!-- GENERATED by apps/games/rts/tools/rts-build.py from rts.src.html + art/units/. "
          "DO NOT EDIT rts.html: it is gitignored and overwritten by the next build. "
          "Edit rts.src.html or the unit file. -->")
REL = "apps/games/rts"


class BuildError(Exception):
    pass


def build(src_text, root=RTS):
    """The built page, plus the unit paths it included (in order)."""
    out, used = [], []
    lines = src_text.split("\n")
    if not lines or not lines[0].lower().startswith("<!doctype html>"):
        raise BuildError("rts.src.html does not start with <!doctype html>")
    out.append(lines[0])
    out.append(HEADER)
    for n, line in enumerate(lines[1:], start=2):
        m = INCLUDE.match(line)
        if not m:
            if "// @@ART" in line or "// @@END" in line:
                raise BuildError("rts.src.html:%d: stray @@ART/@@END marker (the split is @@include now)" % n)
            out.append(line)
            continue
        pad, rel = m.group(1), m.group(2)
        p = os.path.join(root, rel)
        if not rel.startswith("art/units/") or not rel.endswith(".js") or not os.path.isfile(p):
            raise BuildError("rts.src.html:%d: @@include %s: no such unit file" % (n, rel))
        if rel in used:
            raise BuildError("rts.src.html:%d: %s is included twice" % (n, rel))
        used.append(rel)
        with open(p, encoding="utf-8") as f:
            body = f.read()
        if body.endswith("\n"):
            body = body[:-1]
        for k, s in enumerate(body.split("\n"), start=1):
            if INCLUDE.match(s):
                raise BuildError("%s:%d: a unit file cannot @@include (no nesting)" % (rel, k))
            out.append(pad + s if s.strip() else "")
    # every unit file must be reachable, or an edit to it changes nothing and nobody notices
    on_disk = []
    for d, _, fs in os.walk(os.path.join(root, "art", "units")):
        for f in fs:
            if f.endswith(".js"):
                on_disk.append(os.path.relpath(os.path.join(d, f), root))
    orphans = sorted(set(on_disk) - set(used))
    if orphans:
        raise BuildError("unit file(s) not included by rts.src.html: " + ", ".join(orphans))
    return "\n".join(out), used


def sha(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def read(p):
    with open(p, encoding="utf-8") as f:
        return f.read()


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if rts.html is missing or not what a build would produce")
    ap.add_argument("--force", action="store_true", help="overwrite an rts.html that differs from the last build (i.e. was hand-edited)")
    ap.add_argument("--src", default=SRC)
    ap.add_argument("--out", default=OUT)
    ap.add_argument("--stamp", default=STAMP)
    ap.add_argument("-q", "--quiet", action="store_true")
    a = ap.parse_args(argv)
    root = os.path.dirname(os.path.abspath(a.src))
    try:
        text, used = build(read(a.src), root)
    except (BuildError, OSError) as e:
        print("rts-build: " + str(e), file=sys.stderr)
        return 1
    new = sha(text)
    have = read(a.out) if os.path.exists(a.out) else None
    cur = sha(have) if have is not None else None
    if a.check:
        if cur == new:
            return 0
        print("rts-build: %s is %s — run: python3 %s/tools/rts-build.py"
              % (os.path.relpath(a.out), "missing" if cur is None else "stale", REL), file=sys.stderr)
        return 1
    if cur == new:
        if not a.quiet:
            print("rts-build: rts.html is current (%d unit files)" % len(used))
        return 0
    last = read(a.stamp).strip() if os.path.exists(a.stamp) else None
    if cur is not None and cur != last and not a.force:
        print("rts-build: REFUSING to overwrite %s — it differs from the last build output, so it was\n"
              "  edited directly. rts.html is generated: port the change into rts.src.html or the unit\n"
              "  file under art/units/ (diff against a fresh build: --out /tmp/rts.html --stamp /tmp/x),\n"
              "  or rerun with --force to discard it." % os.path.relpath(a.out), file=sys.stderr)
        return 2
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(os.path.abspath(a.out)), prefix=".rts-build-")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(text)
    os.chmod(tmp, 0o444)                       # a tell for anyone about to edit the output
    os.replace(tmp, a.out)
    with open(a.stamp, "w") as f:
        f.write(new + "\n")
    if not a.quiet:
        print("rts-build: %s <- rts.src.html + %d unit files (%d lines)"
              % (os.path.relpath(a.out), len(used), text.count("\n") + 1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
