// Iron Frontier — ui/dom.js
// GENERATED by apps/games/rts/tools/modularize from rts.src.html + art/units/**.

// ===================================================================== //
//  Everything below is presentation — skipped entirely when headless.
// ===================================================================== //

export var cv = document.getElementById('cv');

export var ctx = cv.getContext('2d');

export var mini = document.getElementById('mini');

export var mctx = mini.getContext('2d');

export var stage = document.getElementById('stage');

export var cvW = 800, cvH = 600;

export var IS_TOUCH = (function () { try { return window.matchMedia('(hover: none) and (pointer: coarse)').matches; } catch (e) { return false; } })();

// --- generated ---
// ESM import bindings are read-only, so a write from another module goes
// through the owner. Reads stay verbatim everywhere: the binding is live.
export function setCvH(v) { cvH = v; }
export function setCvW(v) { cvW = v; }
