// Iron Frontier — bake/bake.js
// GENERATED by apps/games/rts/tools/modularize from rts.src.html + art/units/**.

import { BLDS } from '../blds.js';
import { FACTIONS } from '../factions.js';
import { UNITS } from '../roster.js';
import { COL, bakeBuilding } from './buildings.js';
import { bakeAirport, bakeBridge, bakeBridgeWreck, bakeCiv, bakeCivLit, bakeCrate, bakeGem, bakeHospital, bakeHut, bakeOilDerrick, bakeRamp, bakeStreetTree, bakeUrbanDecal, bakeUrbanRoad, tintSet } from './civ.js';
import { SHIP_KINDS, infArt } from './infantry.js';
import { bakeSandbags, bakeShip, dogArt } from './ships.js';
import { CLIFF_VAR, ORE_VAR, SPR, bakeApronSheet, bakeBoulder, bakeDeadTree, bakeDecal, bakeFloe, bakeGroundSheet, bakeLat, bakeOre, bakeRoad, bakeRockSheet, bakeRuin, bakeScree, bakeShallow, bakeShore, bakeShroudEdge, bakeSparkle, bakeTree, bakeWaterSheet, cliffBank, lazySheet, sheetTiles, waterTiles } from './terrain.js';
import { bakeVehicle } from './vehicles.js';
import { artBox, artTop, artTopSolid, bakeAirShadow, bakeCraterDecal, bakeExplosions, bakeMuzzleFlash, bakeRadDecal, bakeScorchDecal, set_gateSpr, set_wallSpr } from './walls.js';

// ---- unit art: one function per unit (art/units/<class>/<kind>.js) ----
// @@include art/units/infantry/conscript.js
// @@include art/units/infantry/rocketeer.js
// @@include art/units/infantry/guardian-gi.js
// @@include art/units/infantry/flak-trooper.js
// @@include art/units/infantry/engineer.js
// @@include art/units/infantry/tanya.js
// @@include art/units/infantry/teslatrooper.js
// @@include art/units/infantry/ivan.js
// @@include art/units/infantry/desolator.js
// @@include art/units/infantry/yuri.js
// @@include art/units/infantry/cleg.js
// @@include art/units/infantry/spy.js
// @@include art/units/infantry/gi.js
// @@include art/units/infantry/dog.js
// @@include art/units/ships/destroyer.js
// @@include art/units/ships/aegis.js
// @@include art/units/ships/carrier.js
// @@include art/units/ships/dread.js
// @@include art/units/ships/seascorp.js
// @@include art/units/ships/lcraft.js
// @@include art/units/ships/sub.js
// @@include art/units/ships/dolphin.js
// @@include art/units/ships/squid.js
// @@include art/units/aircraft/kirov.js
// @@include art/units/aircraft/harrier.js
// @@include art/units/vehicles/lancer.js
// @@include art/units/vehicles/spectre.js
// @@include art/units/vehicles/mammoth.js
// @@include art/units/vehicles/ifv.js
// @@include art/units/vehicles/rhino.js
// @@include art/units/vehicles/flaktrack.js
// @@include art/units/vehicles/v3.js
// @@include art/units/vehicles/drone.js
// @@include art/units/vehicles/teslatank.js
// @@include art/units/vehicles/mirage.js
// @@include art/units/vehicles/chronominer.js
// @@include art/units/vehicles/warminer.js
// @@include art/units/vehicles/mcv.js
// @@include art/units/vehicles/nighthawk.js
// @@include art/units/vehicles/apc.js
// @@include art/units/structures/shipyard.js
// @@include art/units/structures/base.js
// @@include art/units/structures/power.js
// @@include art/units/structures/refinery.js
// @@include art/units/structures/barracks.js
// @@include art/units/structures/factory.js
// @@include art/units/structures/sentry.js
// @@include art/units/structures/tesla.js
// @@include art/units/structures/airforce.js
// @@include art/units/structures/depot.js
// @@include art/units/structures/lab.js
// @@include art/units/structures/purifier.js
// @@include art/units/structures/prism.js
// @@include art/units/structures/radar.js
// @@include art/units/structures/reactor.js
// @@include art/units/structures/sentrygun.js
// @@include art/units/structures/patriot.js
// @@include art/units/structures/flakcannon.js
// @@include art/units/structures/chrono.js
// @@include art/units/structures/weather.js
// @@include art/units/structures/curtain.js
// @@include art/units/structures/nuke.js
// @@include art/units/structures/gapgen.js
// @@include art/units/structures/grandcannon.js
// @@include art/units/structures/spysat.js
// @@include art/units/structures/psisensor.js
// @@include art/units/structures/cloningvats.js
// @@include art/units/structures/wall.js
// @@include art/units/structures/gate.js

export function bakeAll() {
  // Terrain is cut from seamless screen-space sheets (see bakeGroundSheet):
  // 64 tiles per theatre that reassemble into one continuous surface, so
  // there is no tile edge anywhere on the ground. `SPR.groundT[th][gi]` is
  // indexed by position — ((x-y)&7)<<3 | ((x+y)&7) — not by a hash.
  SPR.groundT = { temperate: sheetTiles(bakeGroundSheet('grass', 41)), snow: sheetTiles(bakeGroundSheet('snow', 51)),
                  urban: sheetTiles(bakeGroundSheet('pave', 61)) };
  SPR.ground = SPR.groundT.temperate;
  // The theatre's SECOND ground, and the 16 LAT masks that blend the two.
  var altS = { temperate: bakeGroundSheet('sand', 43), snow: bakeGroundSheet('scour', 53), urban: bakeGroundSheet('grit', 63) };
  SPR.groundAltT = { temperate: sheetTiles(altS.temperate), snow: sheetTiles(altS.snow), urban: sheetTiles(altS.urban) };
  SPR.lat = { temperate: [], snow: [], urban: [] };
  for (var lm = 1; lm < 16; lm++) {
    SPR.lat.temperate[lm] = bakeLat(altS.temperate, lm, 1);
    SPR.lat.snow[lm] = bakeLat(altS.snow, lm, 2);
    SPR.lat.urban[lm] = bakeLat(altS.urban, lm, 3);
  }
  // The apron: the theatre continuing past the playable diamond, darkened.
  SPR.apron = { temperate: sheetTiles(bakeApronSheet('grass', 41)), snow: sheetTiles(bakeApronSheet('snow', 51)),
                urban: sheetTiles(bakeApronSheet('pave', 61)) };
  SPR.rockT = { temperate: sheetTiles(bakeRockSheet('grass', 88)), snow: sheetTiles(bakeRockSheet('snow', 89)),
                urban: sheetTiles(bakeRockSheet('urban', 90)) };
  SPR.rock = SPR.rockT.temperate;
  // Decals ride over one tile in eight on an uncorrelated hash, which
  // breaks the sheet's 8-tile period.
  SPR.decal = { temperate: [], snow: [], urban: [] };
  for (var dv = 0; dv < 8; dv++) { SPR.decal.temperate[dv] = bakeDecal('grass', dv); SPR.decal.snow[dv] = bakeDecal('snow', dv); SPR.decal.urban[dv] = bakeUrbanDecal(dv); }
  // Water: 4 position tiles x 4 phase frames, flattened to [pos*4+frame].
  SPR.water = { temperate: [], snow: [] };
  for (var wk = 0; wk < 2; wk++) {
    var wkind = wk ? 'snow' : 'grass', wth = wk ? 'snow' : 'temperate';
    for (var wf = 0; wf < 4; wf++) {
      var wt = waterTiles(bakeWaterSheet(wkind, wf));
      for (var wp = 0; wp < 16; wp++) SPR.water[wth][wp * 4 + wf] = wt[wp];
    }
  }
  SPR.water.urban = SPR.water.temperate;                       // a river is a river in any theatre
  // Cliffs: 16 neighbour masks x CLIFF_VAR rock variants, keyed
  // `mask | variant << 4`, baked LAZILY. A match uses one theatre and a
  // handful of masks, so eagerly baking 48 sheets for each of three
  // theatres would cost more load than the rest of the terrain set put
  // together -- and every slot a match never asks for is free.
  SPR.cliff = {};
  ['temperate', 'snow', 'urban'].forEach(function (cth) {
    var ck = cth === 'temperate' ? 'grass' : cth;
    SPR.cliff[cth] = lazySheet(16 * CLIFF_VAR, function (k) { return cliffBank(k & 15, ck, k >> 4); });
  });
  // Roads are keyed by the neighbour mask, not by a decorative variant.
  SPR.road = { temperate: [], snow: [], urban: [] };
  for (var rv = 0; rv < 32; rv++) {
    var rmk = rv >> 1, rvv = rv & 1;
    SPR.road.temperate[rv] = bakeRoad('grass', rmk, rvv);
    SPR.road.snow[rv] = bakeRoad('snow', rmk, rvv);
    SPR.road.urban[rv] = bakeUrbanRoad(rmk, rvv);
  }
  SPR.floe = [bakeFloe(0), bakeFloe(1), bakeFloe(2)];
  SPR.shore = { temperate: [], snow: [] };
  SPR.shallow = { temperate: [], snow: [] };
  SPR.scree = { temperate: [], snow: [], urban: [] };
  var rkF = { temperate: bakeRockSheet('grass', 88, 1), snow: bakeRockSheet('snow', 89, 1), urban: bakeRockSheet('urban', 90, 1) };
  for (var sm = 1; sm < 16; sm++) {
    SPR.shore.temperate[sm] = bakeShore('grass', sm); SPR.shore.snow[sm] = bakeShore('snow', sm);
    SPR.shallow.temperate[sm] = bakeShallow('grass', sm); SPR.shallow.snow[sm] = bakeShallow('snow', sm);
    SPR.scree.temperate[sm] = bakeScree('grass', sm, rkF.temperate);
    SPR.scree.snow[sm] = bakeScree('snow', sm, rkF.snow);
    SPR.scree.urban[sm] = bakeScree('urban', sm, rkF.urban);
  }
  SPR.shore.urban = tintSet(SPR.shore.temperate, '#767a7e', 0.36);
  SPR.shallow.urban = tintSet(SPR.shallow.temperate, '#767a7e', 0.28);
  // Eight terrain objects per theatre, not four: RA2 temperate alone ships
  // dozens, and a field of one repeated conifer is the tell. Five trees,
  // a dead trunk and two rock outcrops on the wild theatres; five street
  // trees and three bombed shells in the city.
  SPR.tree = { temperate: [], snow: [], urban: [] };
  for (var tv = 0; tv < 5; tv++) {
    SPR.tree.temperate[tv] = bakeTree(tv, false);
    SPR.tree.snow[tv] = bakeTree(tv, true);
  }
  SPR.tree.temperate[5] = bakeDeadTree(0, false);
  SPR.tree.temperate[6] = bakeBoulder('grass', 0);
  SPR.tree.temperate[7] = bakeBoulder('grass', 1);
  SPR.tree.snow[5] = bakeDeadTree(1, true);
  SPR.tree.snow[6] = bakeBoulder('snow', 0);
  SPR.tree.snow[7] = bakeBoulder('snow', 2);
  for (tv = 0; tv < 5; tv++) SPR.tree.urban[tv] = bakeStreetTree(SPR.tree.temperate[tv]);
  SPR.tree.urban[5] = bakeRuin(0); SPR.tree.urban[6] = bakeRuin(1); SPR.tree.urban[7] = bakeRuin(2);
  SPR.ramp = { temperate: [], snow: [], urban: [] };
  SPR.rampF = { temperate: [], snow: [], urban: [] };
  for (var rd = 0; rd < 16; rd++) {
    var rdd = rd >> 2, rdw = rd & 3;
    SPR.ramp.temperate[rd] = bakeRamp('grass', rdd, 0, rdw); SPR.ramp.snow[rd] = bakeRamp('snow', rdd, 0, rdw); SPR.ramp.urban[rd] = bakeRamp('pave', rdd, 0, rdw);
    SPR.rampF.temperate[rd] = bakeRamp('grass', rdd, 1, rdw); SPR.rampF.snow[rd] = bakeRamp('snow', rdd, 1, rdw); SPR.rampF.urban[rd] = bakeRamp('pave', rdd, 1, rdw);
  }
  SPR.bridge = [bakeBridge(0), bakeBridge(1)];
  SPR.bwreck = bakeBridgeWreck();
  SPR.civ = []; for (var cv = 0; cv < 10; cv++) SPR.civ[cv] = bakeCiv(cv);
  SPR.crate = bakeCrate();
  // Neutral structures, keyed by BLDS key exactly like SPR.bld, but with
  // ONE set: house -1 has no colour and no faction, so there is nothing to
  // vary. `lit` is the occupied frame.
  SPR.neut = {};
  (function () {
    var mk = { oilderrick: bakeOilDerrick, hospital: bakeHospital, airport: bakeAirport, bhut: bakeHut };
    var k;
    for (k in mk) SPR.neut[k] = mk[k]();
    for (k in BLDS) {
      if (!BLDS[k].civ) continue;
      var cs = SPR.civ[BLDS[k].art];
      SPR.neut[k] = { s: cs, ax: cs.ax, ay: cs.ay };
    }
    for (k in SPR.neut) {
      var A = SPR.neut[k];
      A.s.bb = artBox(A.s);
      A.rise = A.ay - artTop(A.s);
      A.mass = A.ay - artTopSolid(A.s, 12);
      if (BLDS[k].civ) A.lit = { s: bakeCivLit(A.s, A.ax, A.ay), ax: A.ax, ay: A.ay, rise: A.rise, mass: A.mass };
      if (A.lit) { A.lit.s.bb = A.s.bb; }
    }
  })();
  SPR.shroudE = [];
  for (var sm = 0; sm < 16; sm++) SPR.shroudE.push(bakeShroudEdge(sm));
  SPR.oreLv = []; SPR.gemLv = [];
  SPR.oreSpark = [bakeSparkle(0, 'rgba(255,214,120,ALPHA)', 0), bakeSparkle(1, 'rgba(255,214,120,ALPHA)', 1), bakeSparkle(2, 'rgba(255,214,120,ALPHA)', 0)];
  SPR.gemSpark = [bakeSparkle(0, 'rgba(198,178,255,ALPHA)', 0), bakeSparkle(1, 'rgba(198,178,255,ALPHA)', 1), bakeSparkle(2, 'rgba(198,178,255,ALPHA)', 0)];
  for (var lv = 0; lv < 3; lv++) {
    var oV = [], gV = [];
    for (var ov = 0; ov < ORE_VAR; ov++) { oV.push(bakeOre(lv, ov)); gV.push(bakeGem(lv, ov)); }
    SPR.oreLv.push(oV); SPR.gemLv.push(gV);
  }
  SPR.expl = bakeExplosions();
  SPR.decal_fx = { scorch: [bakeScorchDecal(0), bakeScorchDecal(1), bakeScorchDecal(2)],
                   crater: [bakeCraterDecal(0), bakeCraterDecal(1), bakeCraterDecal(2)],
                   rad:    [bakeRadDecal(0), bakeRadDecal(1), bakeRadDecal(2)] };
  SPR.flash = bakeMuzzleFlash();
  SPR.shadow = bakeAirShadow();
  bakeOwned();
}

// Everything whose art carries an owner's house colour. Split out of
// bakeAll so picking one of the eight RA2 colours re-bakes THESE and not
// the terrain sheets, the explosions or the decals — see
// docs/design-decisions.md. Every lazy per-frame cache (infantry facings,
// damage states, aimed turrets, the build-up wipe) hangs off the art
// objects this rebuilds, so it goes with them.
export function bakeOwned() {
  set_wallSpr({}); set_gateSpr({});
  // Units are keyed like structures: [player][faction][type]. Only the
  // harvester actually differs by faction (Chrono Miner vs War Miner), but
  // baking the whole set per faction keeps every lookup uniform.
  SPR.bags = [bakeSandbags(COL[0]), bakeSandbags(COL[1])];   // deployed-GI emplacement {back, front}, one per owner
  SPR.unit = [{ dir: {}, col: {} }, { dir: {}, col: {} }];
  for (var p = 0; p < 2; p++) {
    for (var ufk in FACTIONS) {
      for (var uk in UNITS) {
        var U;
        if (UNITS[uk].dog) {
          U = dogArt(COL[p], ufk);              // a shepherd, not a man in another coat
        } else if (UNITS[uk].cls === 'i') {
          U = infArt(COL[p], uk, ufk);          // one frame now, the rest on demand
        } else {
          // The Prism Tank's art kind is still called `spectre` inside
          // bakeVehicle — the sprite it names is the Prism Tank's.
          var vk = UNITS[uk].harv ? 'harv' : (uk === 'prismtank' ? 'spectre' : uk);
          U = SHIP_KINDS[vk] ? bakeShip(COL[p], vk, ufk) : bakeVehicle(COL[p], vk, ufk);
          // Harvesters get a second 8-facing set with the scoop working;
          // drawUnit alternates the two while mining.
          if (vk === 'harv') U.mine = bakeVehicle(COL[p], vk, ufk, 'mine');
          if (vk === 'kirov') U.anim = bakeVehicle(COL[p], vk, ufk, 'prop');      // propeller turned 45 degrees
          if (vk === 'nighthawk') U.anim = bakeVehicle(COL[p], vk, ufk, 'prop');  // main and tail rotors, half a blade on
          if (vk === 'harrier') U.empty = bakeVehicle(COL[p], vk, ufk, 'empty');  // missile racks fired
        }
        // Selection brackets and the HP bar are placed off the art's real
        // bounds, not off the stat-table width: a ground ring sized from
        // UNITS[].w vanished under the wider rebuilt hulls. A vehicle's
        // sheets fill `bb` inside their own lazy getter, so walking them
        // here (which would bake all 32 bearings of every unit in the game)
        // is exactly what must NOT happen; only the eager art needs it.
        if (!Array.isArray(U) && U && !U.bb) U.bb = artBox(U);
        SPR.unit[p][ufk][uk] = U;
      }
    }
  }
  // Two players x two factions: a Soviet barracks is a different structure
  // from an Allied one, not the same shape in another colour.
  SPR.bld = [{ dir: {}, col: {} }, { dir: {}, col: {} }];
  for (var q = 0; q < 2; q++)
    for (var fk in FACTIONS)
      for (var k in BLDS) {
        var A = bakeBuilding(k, COL[q], fk);
        // Rows above the footprint that the art actually reaches, so the HP
        // bar and the unpowered glyph sit above the sprite rather than being
        // painted across a stack or a statue (they used to be placed off the
        // footprint size alone, which the taller RA2 shapes outgrew).
        A.rise = A.ay - artTop(A.s);
        A.mass = A.ay - artTopSolid(A.s, 12);   // over the mass, not a mast tip
        A.s.bb = artBox(A.s);
        if (k === 'shipyard' || k === 'base' || k === 'power' || k === 'refinery' || k === 'factory' || k === 'barracks'
            || k === 'airforce' || k === 'radar' || k === 'depot' || k === 'lab' || k === 'purifier' || k === 'reactor'
            || k === 'sentry' || k === 'sentrygun' || k === 'prism' || k === 'tesla'
            || k === 'patriot' || k === 'flakcannon'
            || k === 'spysat' || k === 'psisensor' || k === 'cloningvats' || k === 'gapgen'
            || k === 'chrono' || k === 'weather' || k === 'curtain' || k === 'nuke') {
          // The yard's crane works: six phases, cycled by drawBld like the
          // RA2 idle animation. The bbox is the union so the brackets and
          // the build-up clip cover every phase.
          A.frames = [A.s];
          for (var bfP = 1; bfP < 6; bfP++) {
            var BF = bakeBuilding(k, COL[q], fk, bfP / 6).s, fbb = artBox(BF);
            A.s.bb = { x0: Math.min(A.s.bb.x0, fbb.x0), y0: Math.min(A.s.bb.y0, fbb.y0),
                       x1: Math.max(A.s.bb.x1, fbb.x1), y1: Math.max(A.s.bb.y1, fbb.y1) };
            A.frames.push(BF);
          }
          A.rise = Math.max(A.rise, A.ay - A.s.bb.y0);
        }
        SPR.bld[q][fk][k] = A;
      }
}
