// Iron Frontier — bake/buildings.js
// GENERATED by apps/games/rts/tools/modularize from rts.src.html + art/units/**.

import { bspecFor } from '../combat-tables.js';
import { HOUSE, OPT_DEF } from '../opts.js';
import { bint, brnd, bsr } from '../rng.js';
import { setLineupCache, setThumbDots } from '../ui/menus.js';
import { setCameoCache } from '../ui/panel.js';
import { drawAirforce } from '../units/structures/airforce.js';
import { drawBarracks } from '../units/structures/barracks.js';
import { drawBase } from '../units/structures/base.js';
import { drawChrono } from '../units/structures/chrono.js';
import { drawCloningvats } from '../units/structures/cloningvats.js';
import { drawCurtain } from '../units/structures/curtain.js';
import { drawDepot } from '../units/structures/depot.js';
import { drawFactory } from '../units/structures/factory.js';
import { drawFlakcannon } from '../units/structures/flakcannon.js';
import { drawGapgen } from '../units/structures/gapgen.js';
import { bakeGateSeg } from '../units/structures/gate.js';
import { drawGrandcannon } from '../units/structures/grandcannon.js';
import { drawLab } from '../units/structures/lab.js';
import { drawNuke } from '../units/structures/nuke.js';
import { drawPatriot } from '../units/structures/patriot.js';
import { drawStructurePower } from '../units/structures/power.js';
import { drawPrism } from '../units/structures/prism.js';
import { drawPsisensor } from '../units/structures/psisensor.js';
import { drawPurifier } from '../units/structures/purifier.js';
import { drawRadar } from '../units/structures/radar.js';
import { drawReactor } from '../units/structures/reactor.js';
import { drawRefinery } from '../units/structures/refinery.js';
import { drawSentry } from '../units/structures/sentry.js';
import { drawSentrygun } from '../units/structures/sentrygun.js';
import { drawShipyard } from '../units/structures/shipyard.js';
import { drawSpysat } from '../units/structures/spysat.js';
import { drawTesla } from '../units/structures/tesla.js';
import { bakeWallSeg } from '../units/structures/wall.js';
import { drawWeather } from '../units/structures/weather.js';
import { TH, TW } from '../world.js';
import { bakeOwned } from './bake.js';
import { outline } from './kit.js';
import { SPR, diamond, mkCanvas, shade } from './terrain.js';
import { FOOT0, PIXBLD, VPOW, bakePix, cylinder, prism } from './vehicles.js';

export function bakeBuilding(key, col, fac, bph, bdir, dopen) {
  var srand = bsr, rnd = brnd, rint = bint;   // the ART generator: a baker must never move the simulation's stream (two-player desync, 2026-09-11)
  var DOP = dopen == null ? 0 : dopen;
  if (PIXBLD[key]) return bakePix(PIXBLD[key], col);
  // Walls and gates are drawn from their own neighbour-mask atlas
  // (wallSprite/gateSprite); what bakeBuilding hands back is the frame the
  // CAMEO and the placement ghost use — RA2's wall icon is a four-way piece.
  if (key === 'wall') return bakeWallSeg(col, fac, 15);
  if (key === 'gate') return bakeGateSeg(col, fac, false, 0);
  var sov = fac === 'col';                    // Collective reads as RA2's Soviets
  // RA2's Foundation= is per FACTION, not per key: a Soviet Battle Lab is
  // 3x3 where the Allied one is 3x2, a Tesla Reactor 3x2 where the Allied
  // plant is 2x2. The art must be baked from the faction-resolved spec or
  // the sprite and the cells it occupies disagree.
  var b = bspecFor(key, fac);
  var fw = (b.gw + b.gh) * TW / 4, fh = (b.gw + b.gh) * TH / 4;
  // How far the drawn plot leans off a square diamond. In 2:1 iso a gw x gh
  // block of cells is a PARALLELOGRAM, not a rhombus: its E corner sits at
  // (+fw, +fh*FKW) and its S corner at (+fw*FKW, +fh). Drawing a rhombus
  // instead is exactly why adjacent structures looked as though they grew
  // through each other -- the plate covered cells the building did not own
  // and missed cells it did. plot() traces the true cell outline; every
  // ground plate, apron and bib in here goes through it.
  var FKW = (b.gw - b.gh) / (b.gw + b.gh);
  function plot(gg, px, py, sw, sh) {
    // Undo the vertical mass scale: the plate must be exactly as tall as the
    // cells it covers, whatever the superstructure above it is doing.
    var hw = sw / 2, hh = sh / 2 / VS, kx = FKW * hw, ky = FKW * hh;
    var pyy = baseY + (py - baseY) / VS;
    gg.beginPath();
    gg.moveTo(px + hw, pyy + ky); gg.lineTo(px + kx, pyy + hh);
    gg.lineTo(px - hw, pyy - ky); gg.lineTo(px - kx, pyy - hh);
    gg.closePath();
  }
  var pad = (key === 'factory' || key === 'airforce' || key === 'radar') ? 24 : 18;   // factory rails, the Airforce helipad and the Radar's front wedge overhang the plot
  if (key === 'factory') pad = 34;   // the Soviet exit ramp runs a long way past the plot's S corner, and grows with VS
  var head = { base: 108, power: 90, refinery: 72, factory: 104, barracks: 190, sentry: 56, tesla: 106,
               airforce: 96, radar: 110, depot: 70, lab: 100, purifier: 96, reactor: 100, prism: 110, sentrygun: 56,
               patriot: 64, flakcannon: 84 }[key] || 70;
  // The Battle Lab's antenna thicket and the Service Depot's projector head
  // both outgrew the shared head allowance (added on their own line so the
  // per-key `head` map above stays untouched).
  if (key === 'lab') head = 152; else if (key === 'depot') head = 88;
  // The lab's drums overhang their plot sideways by ~18 px a side, and its
  // `pad` used to be paid for by VPOW scaling it with VS. With `lab: 0` that
  // subsidy is gone and the Soviet 3x3 sprite came back 228 px wide in a
  // 228 px canvas — both edges CUT, caught by clip.structuresTouchingSheetEdge
  // on the very run that introduced it. The margin is now stated instead of
  // borrowed.
  if (key === 'lab') pad = 30;
  else if (key === 'shipyard') head = 226;   // the crane is the tallest thing on either rig
  // Superweapons are the tallest things on the board: the Chronosphere's
  // dome, the Weather Device's mast, the Curtain's emitter, the silo tower.
  if (key === 'gapgen') head = 116; else if (key === 'grandcannon') head = 84;
  if (key === 'spysat') head = 118; else if (key === 'psisensor') head = 128;
  else if (key === 'cloningvats') head = 92;
  if (key === 'chrono') head = 100; else if (key === 'weather') head = 168;
  else if (key === 'curtain') head = 124; else if (key === 'nuke') head = 152;
  // Every `head`/`pad` above was tuned against the OLD footprint. The art
  // itself is parametric in `fw` (`u = fw / 3`), so moving a structure to
  // its RA2 Foundation= scales the whole drawing -- and the headroom and
  // the canvas margin have to scale with it or a taller mast is clipped
  // off the top of its own sprite. FOOT0 is the (gw+gh) each allowance was
  // drawn at; anything not listed never moved.
  // VS also scales the structure's VERTICAL mass. RA2's sprite for a bigger
  // Foundation= is bigger in both axes; ours was parametric in `fw` across
  // the plan but every HEIGHT is a literal pixel count, so moving the yard
  // to 4x4 grew it 33% wider and only 13% taller and the silhouette flopped
  // out toward the plate's own 2:1 (measured: aspect 1.50 -> 1.70 against a
  // 1.26 reference). The whole drawing therefore runs under a vertical
  // scale about the ground line, and plot() pre-divides by it so the ground
  // plate still lands exactly on its cells. Never below 1: the two
  // footprints that SHRANK (Gap Generator 2x2->1x1, Cloning Vats 3x2->2x2)
  // already read correctly and squashing them would undo that.
  // The exponent: half the art's vertical detail is drawn in literal pixels
  // (which do not scale at all) and half off `fh` (which scales twice over
  // once the plot grows), so the square root of the plot's growth is what
  // holds a sprite's aspect against its RA2 reference across the set. Two
  // keys measured better at the full factor and are listed in VPOW -- both
  // are cases where no second faction pulls the other way (the Airforce
  // Command is Allied-only; the Allied Service Depot's plot did not move at
  // all, so only the 4x3 Soviet one is affected).
  var f0 = FOOT0[key] || (b.gw + b.gh);
  // `!= null`, not `||`: a VPOW of 0 (grow the plot, do NOT grow the art)
  // is a real setting and `0 || 0.5` silently threw it away.
  var vp = VPOW[key + ':' + fac];
  if (vp == null) vp = VPOW[key] != null ? VPOW[key] : 0.5;
  var VS = Math.max(1, Math.pow((b.gw + b.gh) / f0, vp));
  if (window.__dbgVS && (key === 'refinery' || key === 'factory')) { console.log('VSDBG', fac, b.gw, b.gh, f0, vp, VS, fw, fh); }
  if (VS !== 1) { head = Math.round(head * VS); pad = Math.round(pad * VS); }
  var s = mkCanvas(fw * 2 + pad * 2, fh * 2 + head + pad * 2), g = s.g;
  var cx = s.w / 2, baseY = s.h - pad - fh;
  if (window.__dbgVS && (key === 'refinery' || key === 'factory')) { console.log('VSDBG2', fac, 'cx', cx, 'baseY', baseY, 's.w', s.w, 's.h', s.h, 'fw', fw, 'fh', fh, 'pad', pad, 'head', head); }
  if (VS !== 1) { g.translate(0, baseY * (1 - VS)); g.scale(1, VS); }   // heights grow with the plot

  // ------------------------------------------------------------------- //
  //  [GAYARD] / [NAYARD] — the Shipyard. It is the ONE structure in the
  //  game that stands on water (`WaterBound=yes`), so it skips the concrete
  //  plate and the olive platform every land building shares. Rebuilt
  //  against docs/ra2-ref/allied-naval-yard-anim-last.png and
  //  soviet-naval-yard-anim-last.png; the earlier quay-and-boathouse draft
  //  was simply the wrong building. RA2's two yards are not docks along a
  //  shore, they are OFFSHORE RIGS standing in open water on their own
  //  legs, and the tallest thing in either silhouette is a lattice CRANE
  //  JIB reaching out over the sea with a hook on a cable.
  //
  //  Directorate ([GAYARD]): four fat cylindrical caissons at the corners,
  //  each on a concrete collar with a foam ring at the waterline, ribbed
  //  steel above it, capped by a glossy hemispherical dome over a house
  //  ring; a pale stepped tower on a spoked deck rosette in the middle; a
  //  dark steel arch springing over it from behind with a house band and a
  //  small domed head; a yellow lattice jib out to the right on a yellow
  //  grab.
  //
  //  Collective ([NAYARD]): a low rectangular pontoon riding the water on
  //  corner pilings, its rim painted in the house colour top and bottom;
  //  four squat brick blockhouse pylons with cream slab caps carrying a
  //  house-colour grille each; a black crane tower with a house band, a
  //  cream lattice jib and a wrecking ball on the fall.
  //
  //  Six idle phases: the jib slews, the fall rises, the launch-bay gate
  //  parts, the welding arc flashes in the bay, the swell runs through the
  //  basin and the two floodlights blink in turn.
  // ------------------------------------------------------------------- //
  var C = { baseY: baseY, bph: bph, col: col, cx: cx, fh: fh, fw: fw, g: g, plot: plot, s: s,
            sov: sov };
  if (key === 'shipyard') return drawShipyard(C);

  // RA2 structures are poured concrete and painted steel; the HOUSE colour
  // is trim — a door, a ridge, a flag, a chevron — never the whole shell.
  var CONC = '#b6ab92', STEEL = '#8f9490', ROOF = '#565c48';
  var dark = '#3a3a32', TAR = '#4c5240';
  var hi = shade(col, 1.15), lo = shade(col, 0.72);
  var u = fw / 3;                                        // one scale unit

  // Contact shadow, then a thin skirt of hardstanding — NOT a parade square.
  // The Sentry Gun skips the whole skirt: it is a spider-legged OPEN
  // machine standing straight on bare ground, and this fw*2 x fh*2 slab
  // shows clean through the wide gaps between its splayed legs, wiring
  // all four feet into one solid below-roofline mass that reads as an
  // enclosing drum the sprite has not got (§2.7's "zero enclosing drum or
  // roof"). The Patriot also skips it: its own block pours a translucent
  // olive pad of its own, and this opaque skirt's offset contact-shadow
  // diamond peeked out past it as a pure-black blob the §2.7 dark-tube-
  // mouth count picked up as spurious extra mouths. Every walled structure
  // fully covers this skirt with its own footprint, so skipping it here
  // changes nothing for them.
  // depot is excluded too: its clause needs a genuinely flat pad, so it
  // draws its own instead of this shared full-height platform.
  if (key !== 'sentrygun' && key !== 'patriot' && key !== 'depot') {
  g.fillStyle = 'rgba(0,0,0,.34)';
  plot(g, cx + 3, baseY + 4, fw * 2, fh * 2); g.fill();
  plot(g, cx, baseY, fw * 2, fh * 2);
  g.fillStyle = shade(CONC, 0.60); g.fill();
  outline(g, shade(CONC, 0.46));
  g.save();
  plot(g, cx, baseY, fw * 2, fh * 2); g.clip();
  srand(key.charCodeAt(0) * 13 + key.length);
  for (var pI = 0; pI < 7; pI++) {                       // oil stains / patches
    var pa = rnd() * Math.PI * 2, pr = Math.sqrt(rnd());
    g.fillStyle = rnd() < 0.5 ? shade(CONC, 0.56) : shade(CONC, 0.90);
    g.globalAlpha = 0.30;
    g.beginPath();
    g.ellipse(cx + Math.cos(pa) * pr * fw, baseY + Math.sin(pa) * pr * fh * 0.9,
              4 + rnd() * 6, 2 + rnd() * 3, 0, 0, 6.29);
    g.fill();
  }
  g.globalAlpha = 1; g.restore();
  } // sentrygun / patriot / depot skip the shared skirt

  // --- RA2 Allied structures ------------------------------------------
  // Rebuilt against the actual game sprites rather than written
  // descriptions of them. The whole art direction was wrong before: I was
  // drawing beige industrial concrete sheds, and RA2's Allied buildings are
  // steel blue-grey SCI-FI TECH - pale ribbed barrel-vault cylinders with
  // lavender panels, deep-blue spines with round ports, thick dark stacks
  // with open tops and blue collars, glowing amber cores, and yellow hazard
  // aprons, all sitting on a dark olive platform. No amount of detail on a
  // concrete shed was ever going to converge on that.
  var PLAT = '#4e5348', PLAT_E = '#2f332c';
  var BODY = '#7f8478', BODY_D = '#565b52';
  var RIBL = '#dfe2ea', RIB = '#b7bccc', RIBP = '#8b92b0';
  var BLU = '#2f5aa0', BLUL = '#4f86d6';
  var STK = '#6d726d', STK_T = '#23262a';
  var AMB = '#ffb347', AMBH = '#ffe7a8', HAZ = '#e0b028';

  // Dark bevelled platform every structure stands on. A SECOND universal
  // block, separate from the skirt above — the Sentry Gun skips this one
  // too: it was this fw*2 x fh*2 diamond (PLAT + its shade(1.16) inset),
  // not the skirt, that was actually the near-full-width olive plate
  // wiring the four splayed legs into one solid below-roofline mass
  // (measured, not guessed: it stayed byte-identical after guarding only
  // the skirt, and dumping the sprite's dominant opaque colour matched
  // shade(PLAT,1.16) exactly). Every walled structure fully covers this
  // plate with its own footprint, so skipping it here changes nothing for
  // them.
  if (key !== 'sentrygun' && key !== 'patriot' && key !== 'depot') {
  g.fillStyle = 'rgba(0,0,0,.34)';
  plot(g, cx + 3, baseY + 4, fw * 2, fh * 2); g.fill();
  plot(g, cx, baseY, fw * 2, fh * 2);
  g.fillStyle = PLAT; g.fill(); outline(g, PLAT_E);
  plot(g, cx, baseY - 2, fw * 1.94, fh * 1.94);
  g.fillStyle = shade(PLAT, 1.16); g.fill(); outline(g, PLAT_E);
  } // sentrygun / patriot / depot all skip the shared platform

  // Power-plant pylon: grey column, broad blue band, purple capsule, glowing rod.
  function pylon(px2, py2, r2, h2) {
    cylinder(g, px2, py2, r2 * 1.55, h2 * 0.30, '#25417a', '#37589c', PLAT_E);   // drum base
    g.fillStyle = '#5e83c8';
    g.beginPath(); g.ellipse(px2, py2 - h2 * 0.30, r2 * 1.55, r2 * 0.62, 0, 0, 6.29); g.fill();
    outline(g, PLAT_E);
    cylinder(g, px2, py2 - h2 * 0.30, r2, h2 * 0.42, shade(BODY, 0.92), shade(BODY, 1.12), PLAT_E);
    g.fillStyle = BLU;
    g.fillRect(px2 - r2, py2 - h2 * 0.62, r2 * 2, h2 * 0.16);
    g.fillStyle = '#3b3f7a';                               // capsule
    g.beginPath();
    g.moveTo(px2 - r2 * 0.86, py2 - h2 * 0.60); g.lineTo(px2 + r2 * 0.86, py2 - h2 * 0.60);
    g.lineTo(px2 + r2 * 0.70, py2 - h2 * 1.06); g.lineTo(px2 - r2 * 0.70, py2 - h2 * 1.06);
    g.closePath(); g.fill(); outline(g, '#1d1f3c');
    g.fillStyle = '#5b60b8';
    g.fillRect(px2 - r2 * 0.70, py2 - h2 * 0.98, r2 * 1.4, h2 * 0.10);
    g.fillStyle = AMB;                                     // glowing rod
    g.fillRect(px2 - r2 * 0.28, py2 - h2 * 1.34, r2 * 0.56, h2 * 0.76);
    g.fillStyle = AMBH;
    g.fillRect(px2 - r2 * 0.12, py2 - h2 * 1.34, r2 * 0.24, h2 * 0.76);
    g.fillStyle = 'rgba(255,190,90,.22)';
    g.beginPath(); g.ellipse(px2, py2 - h2 * 1.05, r2 * 1.5, h2 * 0.5, 0, 0, 6.29); g.fill();
  }

  // Hazard-striped apron: where vehicles come and go.
  function apron(axp, ayp, aw, ah) {
    diamond(g, axp, ayp, aw * 2, ah * 2);
    g.fillStyle = '#8d9288'; g.fill(); outline(g, PLAT_E);
    g.save(); diamond(g, axp, ayp, aw * 2, ah * 2); g.clip();
    for (var i = -5; i <= 5; i++) {
      g.fillStyle = i % 2 ? HAZ : '#2f332c';
      g.beginPath();
      g.moveTo(axp + i * 9, ayp - ah); g.lineTo(axp + i * 9 + 4.5, ayp - ah);
      g.lineTo(axp + i * 9 + 13.5, ayp + ah); g.lineTo(axp + i * 9 + 9, ayp + ah);
      g.closePath(); g.fill();
    }
    g.fillStyle = 'rgba(140,148,140,.55)';
    diamond(g, axp, ayp, aw * 1.4, ah * 1.4); g.fill();
    g.restore();
  }

  var C = { AMB: AMB, AMBH: AMBH, BODY: BODY, CONC: CONC, DOP: DOP, HAZ: HAZ, PLAT_E: PLAT_E,
            STEEL: STEEL, VS: VS, baseY: baseY, bdir: bdir, bph: bph, col: col, cx: cx,
            dark: dark, fh: fh, fw: fw, g: g, hi: hi, lo: lo, plot: plot, rnd: rnd, sov: sov,
            srand: srand };
  if (key === 'base') {
    drawBase(C);
  } else if (key === 'power') {
    drawStructurePower(C);
  } else if (key === 'refinery') {
    drawRefinery(C);
  } else if (key === 'barracks') {
    drawBarracks(C);
  } else if (key === 'factory') {
    drawFactory(C);
  } else if (key === 'sentry') {
    drawSentry(C);
  } else if (key === 'tesla') {
    drawTesla(C);
  } else if (key === 'airforce') {
    drawAirforce(C);
  } else if (key === 'depot') {
    drawDepot(C);
  } else if (key === 'lab') {
    drawLab(C);
  } else if (key === 'purifier') {
    drawPurifier(C);
  } else if (key === 'prism') {
    drawPrism(C);
  } else if (key === 'radar') {
    drawRadar(C);
  } else if (key === 'reactor') {
    drawReactor(C);
  } else if (key === 'sentrygun') {
    drawSentrygun(C);
  } else if (key === 'patriot') {
    drawPatriot(C);
  } else if (key === 'flakcannon') {
    drawFlakcannon(C);
  } else if (key === 'chrono') {
    drawChrono(C);

  } else if (key === 'weather') {
    drawWeather(C);

  } else if (key === 'curtain') {
    drawCurtain(C);

  } else if (key === 'nuke') {
    drawNuke(C);

  } else if (key === 'gapgen') {
    drawGapgen(C);

  } else if (key === 'grandcannon') {
    drawGrandcannon(C);

  } else if (key === 'spysat') {
    drawSpysat(C);

  } else if (key === 'psisensor') {
    drawPsisensor(C);

  } else if (key === 'cloningvats') {
    drawCloningvats(C);

  } else {
    // Placeholder until the item's real-sprite branch lands: a drab block
    // the size of the footprint with a house-colour band, never shipped as
    // final art (see docs/rts-roadmap.md, roster expansion).
    var lift = Math.min(40, 14 + (fw + fh) * 0.25);
    prism(g, cx, baseY, fw * 0.8, fh * 0.8, lift, '#6a6f78', '#8a9099', '#2a2e36');
    g.fillStyle = col; g.fillRect(cx - fw * 0.5, baseY - lift - 2, fw, 4);
  }
  return { s: s, ax: cx, ay: baseY };
}

export var COL = ['#4aa3db', '#e5646c'];            // player 0 blue, player 1 red — HOUSE[2], HOUSE[1]

// Picking a house colour re-bakes every owner-coloured sprite, because the
// colour is painted INTO the art at bake time (a per-pixel remap at draw
// time is what RA2's SHP palette does and what a canvas cannot do cheaply).
// Only bakeOwned() is redone, and only when the pair actually changed.
export function applyHouse(h, ah) {
  var a = (HOUSE[h] || HOUSE[OPT_DEF.colour]).c, b = (HOUSE[ah] || HOUSE[OPT_DEF.aiColour]).c;
  if (COL[0] === a && COL[1] === b) return false;
  COL[0] = a; COL[1] = b;
  if (SPR.unit) bakeOwned();                 // before the first bakeAll there is nothing to redo
  setLineupCache({});                          // the menu line-ups are painted in the player's colour
  setThumbDots({});                            // ...and so are the map preview's start dots
  setCameoCache({});                           // ...and so is every sidebar cameo's frame
  return true;
}
