// Iron Frontier — bake/states.js
// GENERATED by apps/games/rts/tools/modularize from rts.src.html + art/units/**.

import { TH, TW } from '../world.js';
import { COL, bakeBuilding } from './buildings.js';
import { FANG, NFACE, UPAD } from './kit.js';
import { SPR, mkCanvas, shade } from './terrain.js';
import { faceSheet } from './vehicles.js';

// --------------------------------------------------------------------- //
//  Structure STATE frames: damaged / unpowered / build-up / rubble.
//
//  RA2 ships a separate SHP for each of these, per building (208 `Buildup=`
//  keys, 39 `ActiveAnimDamaged=`, 174 `DamageFireOffset0=` in art.ini).
//  Hand-redrawing 22 keys x 2 factions x 4 states is not a thing anyone
//  maintains, so every state here is a GENERIC POST-PASS over the already
//  baked healthy canvas, masked to that canvas's own alpha. The one piece
//  of per-key data is the fire ports, and even those are read off the art
//  (a roofline scan) rather than typed in -- art.ini's DamageFireOffset
//  idea, derived from the sprite instead of transcribed.
//
//  All of it is baked LAZILY, on the first frame a structure actually
//  needs the state, so a match that never loses a building never pays.
// --------------------------------------------------------------------- //
// A PRIVATE random stream. The shared `srand`/`rnd` pair also drives AI
// decisions, so a lazy bake or a building death that reseeded it would let
// the RENDERER steer the match. Everything below uses its own generator.
export function lcg(seed) {
  var st = (seed >>> 0) || 1;
  return function () { st = (st * 1664525 + 1013904223) >>> 0; return st / 4294967296; };
}

export function copyArt(src) {
  var d = mkCanvas(src.w, src.h);
  d.g.drawImage(src.c, 0, 0, src.w, src.h);
  return d;
}

// Three FIXED fire ports per structure, on its own roofline: sample the
// alpha at 30/54/74% of the sprite's width and drop the port just under
// the first opaque row. Fixed per key, so the flames come out of the same
// holes every time (RA2's DamageFireOffset0..2), and they sit on roof and
// vent geometry because that is what the scan lands on.
function firePorts(src, ax, ay) {
  var ports = [];
  try {
    var W = src.c.width, H = src.c.height, k = W / src.w;
    var d = src.g.getImageData(0, 0, W, H).data;
    var x0 = W, x1 = -1;
    for (var y = 0; y < H; y++) for (var x = 0; x < W; x++)
      if (d[(y * W + x) * 4 + 3] > 40) { if (x < x0) x0 = x; if (x > x1) x1 = x; }
    if (x1 < 0) return ports;
    var fr = [0.30, 0.54, 0.76];
    for (var i = 0; i < fr.length; i++) {
      var pxx = Math.round(x0 + (x1 - x0) * fr[i]);
      for (var y2 = 0; y2 < H; y2++) {
        if (d[(y2 * W + pxx) * 4 + 3] > 40) {
          ports.push({ x: pxx / k - ax, y: y2 / k - ay + 4 });
          break;
        }
      }
    }
  } catch (e) {}
  if (!ports.length) ports.push({ x: 0, y: -18 });
  return ports;
}

// <=50% hp: the same art, broken. Bites out of the silhouette at the fire
// ports, soot rings round them, cracks running down from each, blackened
// patches, and broken panes -- all clipped to the sprite's own alpha, so
// nothing lands beside the building.
function bakeDamaged(src, ports, ax, ay, seed) {
  var d = copyArt(src), g = d.g, i, j;
  var rnd = lcg(seed);
  g.globalCompositeOperation = 'destination-out';
  for (i = 0; i < ports.length; i++) {                       // holes punched in the roof
    var hx = ax + ports[i].x, hy = ay + ports[i].y;
    for (j = 0; j < 4; j++) {
      g.beginPath();
      g.ellipse(hx + (rnd() - 0.5) * 11, hy - 1 + (rnd() - 0.5) * 6,
                1.8 + rnd() * 2.8, 1.2 + rnd() * 2.0, rnd() * 3, 0, 6.29);
      g.fill();
    }
  }
  g.globalCompositeOperation = 'source-atop';
  g.fillStyle = 'rgba(26,22,18,.18)';                        // overall grime
  g.fillRect(0, 0, src.w, src.h);
  for (i = 0; i < ports.length; i++) {                       // soot round every port
    var sxp = ax + ports[i].x, syp = ay + ports[i].y;
    g.fillStyle = 'rgba(14,12,10,.55)';
    g.beginPath(); g.ellipse(sxp, syp + 1, 12, 8, 0, 0, 6.29); g.fill();
    g.fillStyle = 'rgba(24,20,16,.48)';
    g.beginPath(); g.ellipse(sxp + 1, syp + 8, 9, 13, 0, 0, 6.29); g.fill();   // the streak it leaves
    g.strokeStyle = 'rgba(16,14,12,.62)'; g.lineWidth = 1.3; g.lineCap = 'round';
    for (j = 0; j < 2; j++) {                                // cracks running down
      var cxp = sxp + (rnd() - 0.5) * 8, cyp = syp + 2;
      g.beginPath(); g.moveTo(cxp, cyp);
      for (var k2 = 1; k2 <= 4; k2++) {
        cxp += (rnd() - 0.5) * 9; cyp += 4 + rnd() * 5;
        g.lineTo(cxp, cyp);
      }
      g.stroke();
    }
  }
  for (i = 0; i < 9; i++) {                                  // blackened patches
    var bxp = ax + (rnd() - 0.5) * src.w * 0.55, byp = ay - rnd() * src.h * 0.42 + 6;
    g.fillStyle = rnd() < 0.5 ? 'rgba(18,16,14,.30)' : 'rgba(46,38,30,.26)';
    g.beginPath();
    g.ellipse(bxp, byp, 3 + rnd() * 7, 2 + rnd() * 5, rnd() * 3, 0, 6.29); g.fill();
  }
  for (i = 0; i < 6; i++) {                                  // broken panes / bent plate
    var pxp = ax + (rnd() - 0.5) * src.w * 0.45, pyp = ay - 8 - rnd() * src.h * 0.34;
    var pw = 3 + rnd() * 5, phh = 2.5 + rnd() * 4;
    g.fillStyle = 'rgba(8,10,14,.62)';
    g.fillRect(pxp, pyp, pw, phh);
    g.fillStyle = 'rgba(196,214,236,.30)';                   // the lit edge of the break
    g.fillRect(pxp, pyp, pw, 0.9);
    g.strokeStyle = 'rgba(8,10,14,.5)'; g.lineWidth = 0.8;
    g.beginPath(); g.moveTo(pxp, pyp); g.lineTo(pxp + pw, pyp + phh); g.stroke();
  }
  g.globalCompositeOperation = 'source-over';
  return d;
}

// No power: RA2 stops the animation and puts the lights out. Desaturating
// (a `saturation` blend, re-masked with `destination-in`) is what actually
// kills a lit amber window; brightness alone leaves it glowing orange.
function bakeUnpowered(src) {
  var d = copyArt(src), g = d.g;
  g.globalCompositeOperation = 'saturation';
  g.fillStyle = '#808080'; g.fillRect(0, 0, src.w, src.h);
  g.globalCompositeOperation = 'destination-in';
  g.drawImage(src.c, 0, 0, src.w, src.h);
  g.globalCompositeOperation = 'source-atop';
  g.fillStyle = 'rgba(10,16,30,.50)'; g.fillRect(0, 0, src.w, src.h);
  g.globalCompositeOperation = 'source-over';
  return d;
}

// MAKE: the apron is poured first, then the structure comes up behind a
// rising wipe with a scaffold band and a crane in the uncovered strip.
// The band is what stops the old clipped rise reading as a wireframe glitch
// -- there is always something solid at the cut line.
function makeScaffold(g, x0, x1, y, col, ph) {
  var w = Math.max(14, x1 - x0);
  g.save();
  g.lineCap = 'butt';
  g.fillStyle = '#2b3038'; g.fillRect(x0 - 2, y - 3, w + 4, 5);            // girder
  g.fillStyle = '#79818e'; g.fillRect(x0 - 2, y - 3, w + 4, 1.4);
  g.fillStyle = col; g.fillRect(x0 - 2, y + 1.3, w + 4, 1.3);              // house band
  g.strokeStyle = 'rgba(126,136,152,.8)'; g.lineWidth = 1.2;
  var bays = Math.max(2, Math.round(w / 18));
  for (var k = 0; k < bays; k++) {                                          // cross braces
    var bx = x0 + w * k / bays, bx2 = x0 + w * (k + 1) / bays;
    g.beginPath();
    g.moveTo(bx, y - 3); g.lineTo(bx2, y - 14);
    g.moveTo(bx2, y - 3); g.lineTo(bx, y - 14);
    g.stroke();
  }
  g.strokeStyle = 'rgba(150,160,176,.62)';
  g.beginPath(); g.moveTo(x0, y - 14); g.lineTo(x0 + w, y - 14); g.stroke();
  g.fillStyle = '#242931';                                                  // legs
  g.fillRect(x0 - 1.2, y, 2.6, 11); g.fillRect(x0 + w - 1.4, y, 2.6, 11);
  var mx = x0 + w - 5;                                                      // crane
  g.fillStyle = '#3a4048'; g.fillRect(mx, y - 44, 3, 44);
  g.fillStyle = '#c9a227'; g.fillRect(mx - 26, y - 44, 29, 2.6);            // jib
  g.fillStyle = '#20242a'; g.fillRect(mx - 3, y - 48, 9, 4);                // cab
  var hx = mx - 9 - (ph % 3) * 5;
  g.strokeStyle = '#1a1e24'; g.lineWidth = 1;
  g.beginPath(); g.moveTo(hx, y - 42); g.lineTo(hx, y - 26); g.stroke();
  g.fillStyle = '#828a95'; g.fillRect(hx - 3, y - 26, 6, 4);                // hook block
  g.restore();
}

function bakeMake(src, bb, ay, col, n) {
  var out = [];
  var top = bb.y0;
  // Phase 0 is the poured apron: everything from the anchor row down, which
  // on every one of these sprites is the near half of the hardstanding
  // diamond and nothing else. The wipe then climbs from there to the top of
  // the art -- NOT from the bottom of the canvas, which left 45% of the
  // building standing in the first frame.
  var apronTop = Math.min(bb.y1 - 2, ay + 3);
  for (var i = 1; i < n; i++) {
    var p = i / n, d = mkCanvas(src.w, src.h), g = d.g;
    var revY = apronTop - (apronTop - top) * p;
    g.save();
    g.beginPath(); g.rect(0, revY, src.w, src.h - revY); g.clip();
    g.drawImage(src.c, 0, 0, src.w, src.h);
    g.restore();
    makeScaffold(g, bb.x0, bb.x1, revY, col, i);
    out.push(d);
  }
  return out;
}

// What a levelled structure leaves: a scorch decal, a crater, broken slabs
// and twisted pieces, sized to the footprint. Drawn on the GROUND layer
// (under units), passable, and faded out over a minute -- RA2's rubble.
var SPR_RUBBLE = {};

export function rubbleFor(gw, gh) {
  var key = gw + 'x' + gh;
  if (SPR_RUBBLE[key]) return SPR_RUBBLE[key];
  var fw = (gw + gh) * TW / 4, fh = (gw + gh) * TH / 4;
  var s = mkCanvas(fw * 2 + 26, fh * 2 + 30), g = s.g;
  var cx = s.w / 2, cy = s.h / 2 + 3, i;
  var rnd = lcg(gw * 131 + gh * 17 + 7);
  // Scorch: overlapping soft blots, not a hard tile diamond -- a burn does
  // not stop on the footprint edge.
  for (i = 0; i < 14; i++) {
    var sa2 = rnd() * 6.2832, sr2 = Math.sqrt(rnd());
    g.fillStyle = 'rgba(20,17,14,.10)';
    g.beginPath();
    g.ellipse(cx + Math.cos(sa2) * sr2 * fw * 0.85, cy + Math.sin(sa2) * sr2 * fh * 0.85,
              fw * (0.30 + rnd() * 0.30), fh * (0.28 + rnd() * 0.28), 0, 0, 6.29);
    g.fill();
  }
  g.fillStyle = 'rgba(30,25,20,.26)';
  g.beginPath(); g.ellipse(cx, cy, fw * 0.92, fh * 0.90, 0, 0, 6.29); g.fill();
  // The crater is CHURNED EARTH, not a hole: a warm dug-out bowl with a
  // lit far rim and only a shallow shadow on the near lip. Painted dark it
  // read as a black void punched through the map.
  g.fillStyle = 'rgba(96,80,58,.92)';
  g.beginPath(); g.ellipse(cx, cy, fw * 0.62, fh * 0.60, 0, 0, 6.29); g.fill();
  g.fillStyle = 'rgba(132,113,82,.85)';                                   // lit far rim
  g.beginPath(); g.ellipse(cx - 1, cy - 2.5, fw * 0.55, fh * 0.50, 0, 0, 6.29); g.fill();
  g.fillStyle = 'rgba(58,47,34,.85)';                                     // shadowed floor
  g.beginPath(); g.ellipse(cx + 1.5, cy + 2, fw * 0.42, fh * 0.36, 0, 0, 6.29); g.fill();
  g.fillStyle = 'rgba(150,130,96,.35)';                                   // spoil on the near lip
  g.beginPath(); g.ellipse(cx, cy + fh * 0.5, fw * 0.5, fh * 0.20, 0, 0, 6.29); g.fill();
  for (i = 0; i < 16; i++) {                                              // broken slabs
    var a = rnd() * 6.2832, r = Math.sqrt(rnd()) * 0.92;
    var qx = cx + Math.cos(a) * r * fw, qy = cy + Math.sin(a) * r * fh;
    var sw2 = 4 + rnd() * 9, sh2 = 2 + rnd() * 4, tl = (rnd() - 0.5) * 4;
    g.fillStyle = ['#4e4a40', '#5f5a4c', '#3a372f', '#6b6455'][(rnd() * 4) | 0];
    g.beginPath();
    g.moveTo(qx - sw2 / 2, qy); g.lineTo(qx - sw2 / 2 + tl, qy - sh2);
    g.lineTo(qx + sw2 / 2 + tl, qy - sh2 + 1); g.lineTo(qx + sw2 / 2, qy + 1);
    g.closePath(); g.fill();
    g.fillStyle = 'rgba(178,186,168,.22)';
    g.fillRect(qx - sw2 / 2 + tl, qy - sh2, sw2, 0.9);
    g.strokeStyle = 'rgba(24,26,22,.55)'; g.lineWidth = 0.8; g.stroke();
  }
  g.strokeStyle = 'rgba(46,44,36,.9)'; g.lineCap = 'round';                // twisted rebar
  for (i = 0; i < 8; i++) {
    var ra = rnd() * 6.2832, rr = Math.sqrt(rnd()) * 0.8;
    var rx = cx + Math.cos(ra) * rr * fw, ry = cy + Math.sin(ra) * rr * fh;
    g.lineWidth = 1 + rnd();
    g.beginPath(); g.moveTo(rx, ry);
    var bx2 = rx, by2 = ry;
    for (var k3 = 0; k3 < 3; k3++) { bx2 += (rnd() - 0.5) * 9; by2 -= 1 + rnd() * 4; g.lineTo(bx2, by2); }
    g.stroke();
  }
  var out = { s: s, ax: cx, ay: cy };
  SPR_RUBBLE[key] = out;
  return out;
}

// --- lazy per-art state caches ----------------------------------------
export function portsOf(art) {
  if (!art.ports) art.ports = firePorts(art.frames ? art.frames[0] : art.s, art.ax, art.ay);
  return art.ports;
}

function hashKey(s) { var h = 2166136261; for (var i = 0; i < s.length; i++) h = (h ^ s.charCodeAt(i)) * 16777619; return h >>> 0; }

export function dmgSetOf(art, key) {
  if (!art._dmg) {
    var ports = portsOf(art), base = art.frames || [art.s], out = [];
    for (var i = 0; i < base.length; i++) out.push(bakeDamaged(base[i], ports, art.ax, art.ay, hashKey(key) + i * 7919));
    art._dmg = out;
  }
  return art._dmg;
}

// Unpowered is a modifier on whatever frame is showing, not a frame of its
// own: a structure that is BOTH hurt and dark has to read as both.
export function offOf(art, tag, frame) {
  if (!art._off) art._off = {};
  if (!art._off[tag]) art._off[tag] = bakeUnpowered(frame);
  return art._off[tag];
}

export function makeOf(art, col) {
  if (!art._make) {
    var bb = art.s.bb || { x0: 0, y0: 0, x1: art.s.w, y1: art.s.h };
    art._make = bakeMake(art.frames ? art.frames[0] : art.s, bb, art.ay, col, 8);
  }
  return art._make;
}

// RA2 turns an animated SPINNING WRENCH over a structure that is repairing;
// ours was the '🔧' glyph, which is a different tool in every font. The
// sprite and the Repair-mode cursor are now drawn from ONE path so they read
// as the same tool: handle (-9,10) -> (3,-2) about the centre, open jaw of
// radius 5.4 at (5.5,-5.5) -- the cursor's own geometry, kept exactly.
export function wrenchPath(g, ox, oy, k, ang, which) {
  var c = Math.cos(ang), sn = Math.sin(ang), q, a, pp;
  var P = function (x, y) { return [ox + (x * c - y * sn) * k, oy + (x * sn + y * c) * k]; };
  if (which === 'jaw') {
    g.beginPath();
    for (q = 0; q <= 18; q++) {
      a = 0.95 + (5.75 - 0.95) * q / 18;
      pp = P(5.5 + Math.cos(a) * 5.4, -5.5 + Math.sin(a) * 5.4);
      if (q) g.lineTo(pp[0], pp[1]); else g.moveTo(pp[0], pp[1]);
    }
  } else {
    var h0 = P(-9, 10), h1 = P(3, -2);
    g.beginPath(); g.moveTo(h0[0], h0[1]); g.lineTo(h1[0], h1[1]);
  }
}

var SPR_WRENCH = null;

export function wrenchSpr() {
  if (SPR_WRENCH) return SPR_WRENCH;
  var out = [], i;
  for (i = 0; i < 8; i++) {
    var c = mkCanvas(26, 26), g = c.g, ang = i * Math.PI / 4;
    g.fillStyle = 'rgba(12,15,22,.60)';
    g.beginPath(); g.arc(13, 13, 11, 0, 6.2832); g.fill();
    g.strokeStyle = 'rgba(255,210,74,.30)'; g.lineWidth = 1; g.stroke();
    g.lineCap = 'round'; g.lineJoin = 'round';
    var pass = [['#3d3008', 5.4, 5.0], ['#ffd24a', 3.2, 2.9], ['#fff0b8', 1.1, 1.0]];
    for (var q2 = 0; q2 < 3; q2++) {
      wrenchPath(g, 13, 13, 0.60, ang, 'handle');
      g.strokeStyle = pass[q2][0]; g.lineWidth = pass[q2][1]; g.stroke();
      wrenchPath(g, 13, 13, 0.60, ang, 'jaw');
      g.strokeStyle = pass[q2][0]; g.lineWidth = pass[q2][2]; g.stroke();
    }
    out.push(c);
  }
  SPR_WRENCH = out;
  return out;
}

// [GACNST] Buildup=GACNSTMK: deploying an MCV is not a swap, it is the
// vehicle OPENING OUT into the yard -- the flanks fold down into aprons,
// four jacks drop, the gantry stands up -- and only then does the yard's own
// MAKE run. Four frames, baked lazily off this owner's MCV sprite at the
// facing it stopped on, so nothing is baked for a match with no MCV deploy.
var SPR_UNPK = {};

export function unpackOf(p, fk, face) {
  var ky = p + fk + face;
  if (SPR_UNPK[ky]) return SPR_UNPK[ky];
  var S = SPR.unit[p][fk].mcv[face & (NFACE - 1)], col = COL[p], out = [], i;
  for (i = 0; i < 4; i++) {
    var t = i / 3;
    var c = mkCanvas(S.w + 52, S.h + 24), g = c.g;
    var ax = c.w / 2, ay = c.h - UPAD;
    // hardstanding spreading out from under it
    g.globalAlpha = 0.20 + 0.55 * t;
    g.fillStyle = '#6f6a56';
    g.beginPath(); g.ellipse(ax, ay - 2, 20 + 30 * t, 10 + 15 * t, 0, 0, 6.29); g.fill();
    g.globalAlpha = 1;
    // the flanks folding down: two plates hinged on the hull sides, laid
    // flatter and pushed further out with every frame
    for (var sg = -1; sg <= 1; sg += 2) {
      var hxo = sg * (11 + 26 * t), hzo = 13 - 11 * t;
      g.beginPath();
      g.moveTo(ax + sg * 9, ay - 15); g.lineTo(ax + sg * 9, ay - 15 + hzo);
      g.lineTo(ax + hxo, ay - 4 + hzo * 0.45); g.lineTo(ax + hxo, ay - 4 - hzo * 0.55);
      g.closePath();
      g.fillStyle = sg < 0 ? shade(col, 0.78) : col; g.fill();
      g.strokeStyle = '#191b20'; g.lineWidth = 0.9; g.stroke();
      // hydraulic jack under the outer lip
      g.strokeStyle = '#3c414a'; g.lineWidth = 2.2;
      g.beginPath(); g.moveTo(ax + hxo, ay - 4 + hzo * 0.45);
      g.lineTo(ax + hxo, ay - 4 + hzo * 0.45 + 4 + 5 * t); g.stroke();
      g.fillStyle = '#20242b';
      g.fillRect(ax + hxo - 3, ay - 1 + hzo * 0.45 + 4 * t, 6, 2.4);
    }
    // the vehicle itself, settling on its jacks as the shell opens
    g.drawImage(S.c, ax - S.w / 2, ay - (S.h - UPAD) + t * 3, S.w, S.h);
    // gantry standing up out of the deck once the flanks are clear
    if (t > 0.30) {
      var gh2 = (t - 0.30) / 0.70 * 26;
      g.strokeStyle = '#7f8894'; g.lineWidth = 2.4;
      g.beginPath(); g.moveTo(ax - 6, ay - 18); g.lineTo(ax - 6, ay - 18 - gh2); g.stroke();
      g.beginPath(); g.moveTo(ax + 6, ay - 18); g.lineTo(ax + 6, ay - 18 - gh2); g.stroke();
      g.strokeStyle = '#c9d0da'; g.lineWidth = 1.6;
      g.beginPath(); g.moveTo(ax - 7, ay - 18 - gh2); g.lineTo(ax + 7, ay - 18 - gh2); g.stroke();
      g.fillStyle = col; g.fillRect(ax - 3, ay - 21 - gh2, 6, 3);
    }
    out.push({ s: c, ax: ax, ay: ay });
  }
  SPR_UNPK[ky] = out;
  return out;
}

export var MCV_T = 0;                                // no unpack delay either (see MAKE_T) — was ~0.8s of unpack before the MAKE

// RA2 plays a DOOR sequence when a unit comes out: [GAWEAP]'s UnderDoorAnim
// + RoofDeployingAnim, [NAWEAP]'s maw leaf, the [GAPILE]/[NAHAND] barracks
// door. Baked lazily the first time a structure produces -- whole frames at
// idle phase 0, indexed by door position, exactly like the aim frames.
var DOOR_N = 7;

export function doorOf(art, key, p, fk) {
  if (!art._door) {
    var out = [], i;
    for (i = 0; i < DOOR_N; i++) out.push(bakeBuilding(key, COL[p], fk, 0, null, i / (DOOR_N - 1)).s);
    art._door = out;
  }
  return art._door;
}

export function doorDmgOf(art, key, p, fk) {
  if (!art._doorD) {
    var dr = doorOf(art, key, p, fk), ports = portsOf(art), out = [], i;
    for (i = 0; i < dr.length; i++) out.push(bakeDamaged(dr[i], ports, art.ax, art.ay, hashKey(key) + 53));
    art._doorD = out;
  }
  return art._doorD;
}

// NFACE bearing frames for the defences whose art has a barrel, launcher
// or slit that should point at what they are shooting (art.ini
// `Turret=yes`) — a Grand Cannon traverses through the same 32 bearings a
// tank turret does. Lazy per bearing (`faceSheet`), so a defence that never
// acquires anything bakes none of them and one that holds a firing lane
// bakes the two or three it uses.
export var AIMED = { sentry: 1, sentrygun: 1, patriot: 1, flakcannon: 1, grandcannon: 1 };

export function aimOf(art, key, p, fk) {
  if (!art._aim) art._aim = faceSheet(function (i) { return bakeBuilding(key, COL[p], fk, 0, i * FANG).s; });
  return art._aim;
}

export function aimDmgOf(art, key, p, fk) {
  if (!art._aimD) {
    var aim = aimOf(art, key, p, fk), ports = portsOf(art);
    art._aimD = faceSheet(function (i) { return bakeDamaged(aim[i], ports, art.ax, art.ay, hashKey(key) + 31); });
  }
  return art._aimD;
}
