#!/usr/bin/env python3
"""Regenerate the table of contents in docs/design-decisions.md.

That file is 8k+ lines and 200+ entries, and CLAUDE.md tells every session to
read it "before re-litigating a design that looks odd" — which is only actionable
if you can FIND the relevant entry. Without an index the practical options were
scrolling or guessing a grep term.

Idempotent: run it after adding an entry. `test_design_decisions_toc_is_current`
fails when it is stale, so the index cannot silently rot.

    python3 tools/gen-dd-toc.py           # rewrite in place
    python3 tools/gen-dd-toc.py --check   # exit 1 if stale (what the test does)
"""
import io
import os
import re
import sys

DOC = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "docs", "design-decisions.md")
BEGIN = "<!-- BEGIN TOC (generated by tools/gen-dd-toc.py — do not edit by hand) -->"
END = "<!-- END TOC -->"


def slug(title):
    """GitHub-flavoured anchor: lowercase, drop punctuation, spaces to dashes."""
    s = title.strip().lower()
    s = re.sub(r"[`*_\[\]()<>.,:;!?\"'/\\]", "", s)
    s = re.sub(r"[^\w\s-]", "", s)
    return re.sub(r"\s+", "-", s).strip("-")


def build(src):
    titles = [m.group(1).strip() for m in re.finditer(r"^## (.+)$", src, re.M)]
    seen, lines = {}, [BEGIN, "", "## Contents", "",
                       f"_{len(titles)} entries. Generated — run "
                       "`python3 tools/gen-dd-toc.py` after adding one._", ""]
    for t in titles:
        a = slug(t)
        seen[a] = seen.get(a, 0) + 1          # GitHub disambiguates repeats with -1, -2
        if seen[a] > 1:
            a = f"{a}-{seen[a] - 1}"
        lines.append(f"- [{t}](#{a})")
    lines += ["", END]
    return "\n".join(lines)


def main():
    src = io.open(DOC, encoding="utf-8").read()
    # Strip an existing block so the generator is idempotent.
    body = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n*", "", src, flags=re.S)
    toc = build(body)
    marker = "\n---\n"
    i = body.index(marker) + len(marker)      # after the header block's rule
    out = body[:i] + "\n" + toc + "\n" + body[i:]
    if "--check" in sys.argv:
        if out != src:
            sys.stderr.write("design-decisions.md TOC is stale — run: "
                             "python3 tools/gen-dd-toc.py\n")
            return 1
        return 0
    io.open(DOC, "w", encoding="utf-8").write(out)
    print(f"TOC regenerated: {out.count(chr(10) + '- [')} entries indexed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
